R/colwise.R
man/n_distinct.Rd
man/summarise_each.Rd

also roxygenizes and catches something from `n_distinct.Rd`

makes small change to documentation `_q` -> `_`

---

vignettes/databases.Rmd

small typo

---

NEWS.md
R/tbl-dt.r
tests/testthat/test-filter.r

Minor glitch in call to lazyeval::common_env.
Fixes #906.

Fix filter_.data.table

---

vignettes/data_frames.Rmd

"in interactively use" -> "in interactive use"

Typo in vignettes/data_frames.Rmd

---

R/dataframe.R
tests/testthat/test-data_frame.R

see https://github.com/hadley/dplyr/issues/1101 for details

changed error message from elements to columns

---

NEWS.md
R/tbl-sql.r

Respect print(n = Inf) for remote sources

---

NEWS.md
inst/include/dplyr/Gatherer.h
tests/testthat/test-mutate.r

Bug na mutate

---

README.Rmd
README.md

You already fixed link to |Stat (https://github.com/hadley/dplyr/commit/980bfeff849b97bd1a51bde32cf3d364fed8eb93) but to not apply README.Rmd. And one more thing, data.table redirect to GitHub wiki now.

Test a README.Rmd

---

vignettes/data_frames.Rmd

In response to Issue #1345
If thought to be useful, I can also try to put something in the man page for tbl_df and/or data_frame. 
Up to you (of course).

first whack documenting `[` behavio(u)r for `tbl_df()` objects

---

tests/testthat/test-joins.r

Same as #1071, which doesn't seem to have made it into master.

Add test for join not changing source data tables

---

NEWS.md
R/frame-data.R
tests/testthat/test-frame-data.R

Fixes an unfortunate error in building the columns of `frame_data()`.

fix error in column building of 'frame-data'

---

R/do.r
man/do.Rd

Specify behavior of do() for empty input

---

NEWS.md
R/grouped-df.r

Use big_mark()

---

vignettes/nse.Rmd

fix typo in nse-vignette

---

R/join.r

Fix documentation error for inner join (I think). Should be all rows in x that match rows in *y*, not x.

Update join.r to fix doc

---

R/dataframe.R
man/data_frame.Rd

fix comment in data_frame example

---

R/group-indices.R
man/group_indices.Rd

Remove unused "add" argument to group_indices()

---

NEWS.md
R/tbl-cube.r
tests/testthat/test-tbl-cube.R

- new argument met_name = guess_met() in as.tbl_cube.data.frame
- all coercion methods generate identical cubes for the same data
- properly handle incomplete cubes and duplication of dimensions
With tests.

Improve construction and coercion of tbl_cube

---

R/tbl-cube.r

to allow as_data_frame.tbl_cube() (#1563 -> tibble)

as.data.frame.tbl_cube() forwards its ... arg

---

R/dbi-s3.r
R/tbl-sql.r

if incomplete results were retrieved: n = -1 raises an error with collect(), only n = Inf works.

Fix warning message for collect()

---

R/recode.R
man/recode.Rd

For me it was not obvious how to use `.default` with factors, therefore I think it's sensible to document this with an example.

document .default behaviour for factor.recode #1717

---

DESCRIPTION

so that Travis tests can find it.

Add dtplyr as remote dependency

---

src/api.cpp

for data frames, introduced in 31b1e2af82ea38f504b9f8bbefd94163177e4bd9

Fix join error message

---

.travis.yml

- check three R versions in a matrix
- build dependencies in parallel
Trimmed-down version of #1813.

Improve Travis checks

---

R/sql-escape.r
tests/testthat/test-sql-escape.r

change timestamp mask

---

inst/include/tools/match.h

that causes warnings with -Wpedantic .

Remove extra semicolon

---

NEWS.md
R/tbl-sql.r
tests/testthat/test-as-data-frame.R

- now defaults to n = Inf (no progress bar yet)
- with tests
Fixes #1752.

WIP: as_data_frame() on SQL sources

---

NEWS.md
src/arrange.cpp
tests/testthat/test-arrange.r

Arranging by matrix throws error

---

NEWS.md
R/data-temp.r

New argument ignore for test_frame()

---

inst/include/dplyr.h
inst/include/dplyr/OrderVisitorImpl.h
inst/include/dplyr/Result/RowwiseSubset.h
inst/include/dplyr/check_supported_type.h

to be used in place of switch(TYPEOF(x)).

WIP: SupportedType enum

---

R/case_when.R
R/recode.R

Minor fix to documentation in case_when.R and recode.R.

Minor typos in documentation.

---

NEWS.md
R/colwise.R
tests/testthat/test-colwise.R

Fix colwise issue when predicate returns a FALSE vector

---

dplyr.Rproj

for https://github.com/hadley/dtplyr/pull/24.

Update RStudio project settings to install tests

---

inst/include/dplyr/Hybrid.h
inst/include/dplyr/HybridHandler.h
inst/include/dplyr/NamedListAccumulator.h
inst/include/dplyr/Result/CallProxy.h
inst/include/dplyr/Result/CallbackProcessor.h
inst/include/dplyr/Result/GroupedCallProxy.h
inst/include/dplyr/Result/GroupedHybridCall.h
inst/include/dplyr/Result/ILazySubsets.h
inst/include/dplyr/Result/LazyGroupedSubsets.h
inst/include/dplyr/Result/LazyRowwiseSubsets.h
inst/include/dplyr/Result/LazySubsets.h
inst/include/dplyr/Result/all.h
inst/include/dplyr/get_column.h
inst/include/tools/SymbolMap.h
src/api.cpp
src/hybrid.cpp
src/hybrid_count.cpp
src/hybrid_in.cpp
src/hybrid_minmax.cpp
src/hybrid_nth.cpp
src/hybrid_offset.cpp
src/hybrid_simple.cpp
src/hybrid_window.cpp
vignettes/hybrid-evaluation.Rmd

- Logging
- Extract ILazySubsets interface
- Clean up ILazySubsets implementations

Nonfunctional changes

---

inst/include/dplyr/Gatherer.h
inst/include/dplyr/GroupedDataFrame.h
inst/include/dplyr/Groups.h
inst/include/dplyr/NamedListAccumulator.h
inst/include/dplyr/Result/GroupedCallProxy.h
inst/include/dplyr/check_supported_type.h
inst/include/tools/LazyDots.h
src/mutate.cpp

for column names. Not comprehensive.

Prefer Symbol to String

---

vignettes/introduction.Rmd

Fixed typo in introduction.Rmd

---

src/utils.cpp

to fix performance regression in #2220.

Avoid coercing pairlist to list

---

tests/testthat/test-if-else.R

Tests for factor handling in `if_else()`. The commits are discussed in #2197. This is my first PR so my apologies and please feel free to correct me if there's anything wrong with this one. BR

Tests for factor handling in if_else()

---

inst/include/tools/utils.h
src/utils.cpp

- fixes linking error in external package using DataFrameSubsetVisitors (https://github.com/rnabioco/valr/issues/163#issuecomment-269687419)

move copy_most_attributes to header

---

NEWS.md
R/sql-build.R
tests/testthat/test-sql-joins.R

Follow-up to #1997.
@javierluraschi: Could you please take a look?

SQL join cleanup

---

NEWS.md
R/data-temp.r
R/src-mysql.r
R/tbl-sql.r
tests/testthat/helper-src.R
tests/testthat/test-filter-windowed.R
tests/testthat/test-group-size.R
tests/testthat/test-mutate-windowed.R
tests/testthat/test-sets.R
tests/testthat/test-tbl-sql.r

- implementation by @demorenoc (closes #1975)
- test by @eduardgrebe (closes #2263)
- fix `group_size()` and `n_groups()` for MySQL
- minor tweaks so that tests pass
Fixes #2256.

Fix copy_to() for MySQL

---

tests/testthat/test-binds.R

Test for issue #2056

---

tests/testthat/test-select-helpers.R

Tests for #2184.
Closes #2266 (=includes it), CC @ngr-t.

Testing select helpers

---

inst/include/dplyr/Result/DelayedProcessor.h
inst/include/dplyr/check_length_one.h
src/summarise.cpp
tests/testthat/test-summarise.r

Harmonize error messages for summarise()

---

src/bind.cpp
tests/testthat/test-binds.R

Fixes #2303.
Follow-up to #2048.

Fix segfaults if all arguments to bind_cols() are NULL

---

inst/include/dplyr/BoolResult.h
inst/include/dplyr/DataFrameColumnSubsetVisitor.h
inst/include/dplyr/DataFrameColumnVisitor.h
inst/include/dplyr/MatrixColumnSubsetVectorVisitor.h
inst/include/dplyr/MatrixColumnVisitor.h
inst/include/dplyr/SubsetVectorVisitor.h
inst/include/dplyr/SubsetVectorVisitorImpl.h
inst/include/dplyr/VectorVisitor.h
inst/include/dplyr/VectorVisitorImpl.h
src/set.cpp
tests/testthat/test-equality.r

and cleanup.
Fixes #1819.
Fixes #2440.
@hadley: PTAL.

all_equal() fixes

---

inst/include/dplyr/JoinVisitorImpl.h
inst/include/dplyr/SubsetVectorVisitorImpl.h
inst/include/tools/utils.h
src/utils.cpp
tests/testthat/test-joins.r

Fixes encoding issues. I'll do a benchmark of all changes soon.
Fixes #2271.
Fixes #2118.
Fixes #1885.

Use R function match() for joining character vectors

---

R/db-sqlite.r
R/tbl-sql.r
tests/testthat/test-tbl-sql.r

- tbl_sql() works with string argument
- memdb_frame() returns visible output

Minor fixes

---

R/grouped-df.r

fixed typo in help text

---

R/bind.r
R/recode.R
R/tbl-df.r
R/utils.r
inst/include/tools/Quosure.h
tests/testthat/helper-astyle.R
tests/testthat/helper-hybrid.R
tests/testthat/test-group-by.r

Minor cleanup after rlang changes

---

src/set.cpp
tests/testthat/test-equality.r

Fix corner case segfault when comparing data frames with all_equal()

---

src/hybrid_window.cpp

Avoid try-catch for coercing to integer.

Cleanup for window hybrid handler

---

CMakeLists.txt
DESCRIPTION
inst/include/dplyr/Collecter.h
inst/include/dplyr/DataFrameJoinVisitors.h
inst/include/dplyr/Gatherer.h
inst/include/dplyr/OrderVisitorImpl.h
inst/include/dplyr/Replicator.h
inst/include/dplyr/Result/DelayedProcessor.h
inst/include/dplyr/Result/GroupedSubset.h
inst/include/dplyr/Result/Rank.h
inst/include/dplyr/checks.h
inst/include/dplyr/subset_visitor_impl.h
inst/include/dplyr/visitor_impl.h
src/api.cpp
src/arrange.cpp
src/bind.cpp
src/combine_variables.cpp
src/filter.cpp
src/group_indices.cpp
src/hybrid.cpp
src/hybrid_count.cpp
src/hybrid_debug.cpp
src/hybrid_in.cpp
src/hybrid_nth.cpp
src/hybrid_offset.cpp
src/init.cpp
src/join.cpp
src/join_exports.cpp
src/mutate.cpp
src/summarise.cpp

Cleanup based on static code analysis

---

R/dataframe.R
R/group-indices.R
tests/testthat/test-lazyeval-compat.R

Fix lazydots compatibility issues

---

src/hybrid.cpp
tests/testthat/test-summarise.r

Regression introduced in dev version. Fixes #2508.

Fix summarise(gdf, x)

---

NEWS.md
inst/include/dplyr/DataFrameAble.h
inst/include/tools/DotsOf.h
inst/include/tools/utils.h
src/bind.cpp
src/utils.cpp
tests/testthat/test-binds.R

Fixes #2373.
Fixes #2056.
Fixes #2175.

Fixes for various bind_rows() issues

---

DESCRIPTION
R/bind.r
R/colwise.R
R/compat-lazyeval.R
R/count-tally.R
R/dataframe.R
R/distinct.R
R/funs.R
R/group-by.r
R/group-indices.R
R/grouped-df.r
R/hybrid.R
R/manip.r
R/partial-eval.r
R/pull.R
R/recode.R
R/rowwise.r
R/select-vars.R
R/tbl-cube.r
R/tbl-df.r
R/tbl-lazy.R
R/tbl-sql.r
R/translate-sql-window.r
R/translate-sql.r
R/utils-expr.R
src/filter.cpp
tests/testthat/helper-hybrid.R
tests/testthat/test-group-by.r
tests/testthat/test-hybrid-traverse.R
tests/testthat/test-hybrid.R

Accounts for the changes in https://github.com/hadley/rlang/pull/59 and https://github.com/hadley/rlang/pull/64

Update to latest rlang API

---

NEWS.md
inst/include/dplyr/Result/DelayedProcessor.h
tests/testthat/test-summarise.r

Ordered factors can be created by summarise()

---

NEWS.md
inst/include/dplyr/Result/GroupedSubset.h
tests/testthat/test-summarise.r

Copy attributes for summary variables

---

inst/include/dplyr/NamedListAccumulator.h
tests/testthat/test-mutate.r

Shallow copy if must strip names

---

inst/include/dplyr/Result/DelayedProcessor.h
tests/testthat/test-summarise.r

Fix summary operations that collect factors with NA values

---

src/filter.cpp
src/group_by.cpp
src/group_indices.cpp
src/join_exports.cpp
src/summarise.cpp
tests/testthat/test-joins.r

Strip group indices for semi- and anti-joins

---

R/colwise-mutate.R
tests/testthat/test-colwise-mutate.R

Fix name handling in scoped manips

---

inst/include/dplyr/Collecter.h
inst/include/dplyr/DataFrameColumnVisitor.h
inst/include/dplyr/MatrixColumnSubsetVectorVisitor.h
inst/include/dplyr/MatrixColumnVisitor.h
inst/include/dplyr/Order.h
inst/include/dplyr/OrderVisitorImpl.h
inst/include/dplyr/Result/CallbackProcessor.h
inst/include/dplyr/Result/ConstantResult.h
inst/include/dplyr/Result/DelayedProcessor.h
inst/include/dplyr/Result/Rank.h
inst/include/dplyr/Result/Result.h
inst/include/dplyr/RowwiseDataFrame.h
inst/include/tools/SlicingIndex.h
inst/include/tools/SymbolString.h
src/hybrid_count.cpp
src/hybrid_debug.cpp
src/hybrid_in.cpp
src/hybrid_offset.cpp
src/mutate.cpp

- Unused arguments
- One instance of potentialy wrong behavior detected

Remove -Wall -Wextra warnings

---

DESCRIPTION
R/compat-lazyeval.R
R/count-tally.R
R/order-by.R
R/select-vars.R
man/select_vars.Rd
tests/testthat/test-funs-predicates.R
tests/testthat/test-funs.R
tests/testthat/test-hybrid-traverse.R
tests/testthat/test-hybrid.R

This should fix broom's builds with dev dplyr. cc @dgrtwo

rlang update: bare formulas stop being treated as quosures

---

src/join.cpp
tests/testthat/test-joins.r

Closes #2643
This was working on dplyr 0.5.0 so I did not add a news entry for this.

Join accepts again POSIXct with different timezones

---

R/manip.r
R/select-vars.R
man/select.Rd
man/select_vars.Rd
tests/testthat/test-select-helpers.R

Fix c() selection

---

NEWS.md
inst/include/tools/match.h

Fix coercion warning on Win32

---

NEWS.md
R/dplyr.r
R/tbl-df.r
man/dplyr-package.Rd
man/join.tbl_df.Rd
tests/testthat/test-joins.r

Joins use na_matches = "na" as default value

---

R/manip.r
R/select-vars.R
man/select.Rd
man/select_vars.Rd
tests/testthat/test-select-helpers.R
tests/testthat/test-select.r

Closes #2715
Also add advice about passing dots to `select_vars()` (forgot to do it in previous PR).

Handle data pronoun in select_vars()

---

appveyor.yml

to work around problems in CRAN version, https://github.com/krlmlr/r-appveyor/issues/88

Install remotes package from GitHub on AppVeyor

---

inst/include/dplyr/Result/CallbackProcessor.h
inst/include/dplyr/SubsetVectorVisitorImpl.h
src/set.cpp

Use backticks for column names

---

src/set.cpp
tests/testthat/test-equality.r
tests/testthat/test-sets.R

Fix backtick tests

---

appveyor.yml
tests/testthat/test-hybrid.R

Fix AppVeyor builds

---

inst/include/tools/utils.h
src/utils.cpp
tests/testthat/test-filter.r

Remove `vars` attribute when empty

---

DESCRIPTION
NEWS.md
R/grouped-df.r

See also https://github.com/tidyverse/tibble/issues/252.

Adapt to new tbl_sum()

---

R/grouped-df.r

for eechidna and perhaps others.

Compatibility fix for deserialized grouped dfs

---

R/RcppExports.R
inst/include/tools/SymbolVector.h
src/RcppExports.cpp
src/group_by.cpp
src/init_register.c
src/utils.cpp
tests/testthat/test-utils.R

Complements https://github.com/tidyverse/dplyr/pull/2786
This fixes the "Cannot handle STRSXP" revdep failure in highcharter.

Handle vars list on the C++ side

---

NEWS.md
R/colwise-mutate.R
R/dataframe.R
R/grouped-df.r
R/join.r
R/tbl-cube.r
R/utils.r
tests/testthat/test-colwise-mutate.R
tests/testthat/test-lazyeval-compat.R

instead of warnings, for cleaner revdep checks

Deprecation messages

---

R/select-vars.R

Haha this is not to be pedantic, but because my test that tests have the error string in them and I don't want them to fail later when this gets corrected

corrected very small spelling mistake

---

NEWS.md
src/between.cpp

Catched by https://cran.r-project.org/web/checks/check_results_dplyr.html (undefined behaviour sanitizer)

Fix assigment of NA_REAL to LogicalVector

---

src/rlang-export.c

https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/dplyr.out

Fix rchk errors

---

vignettes/programming.Rmd

This is an attempt to address issue #2865

programming vignette: rename object "group_by" to "group_var"

---

DESCRIPTION
tests/testthat/test-equality.r

that was broken with glue < 1.1.1.

Reenable test

---

NEWS.md
R/distinct.R
tests/testthat/test-distinct.R

This fixes #2867. Passes tests for distinct, also added a new test for this issue.

Return error when distinct is used on unknown columns (#2867).

---

R/rank.R
docs/reference/ranking.html
man/ranking.Rd

Spelling fix

---

NEWS.md
inst/include/tools/utils.h
src/select.cpp
src/summarise.cpp
src/utils.cpp
tests/testthat/test-group-by.r

Duplicate vars attribute before overwriting it

---

NEWS.md
R/case_when.R
R/if_else.R
R/utils-replace-with.R
man/case_when.Rd
tests/testthat/test-case-when.R

case_when() fixes

---

DESCRIPTION
appveyor.yml
src/hybrid.cpp
tests/testthat/test-select.r

Tests seem to pass with CRAN rlang.

Get rid of rlang remote

---

R/colwise-mutate.R
man/summarise_all.Rd

and note about needing to use vars when not quoting variables when this first appears (summarise_at example)

add example of using mutate_at() with vars() to summarise_all() docs

---

R/src_dbi.R

to `src_dbi()`. Reference: https://github.com/tidyverse/dbplyr/pull/18#discussion_r146617827

Explicit auto_disconnect argument

---

NEWS.md
inst/include/dplyr/Result/Mean.h
inst/include/dplyr/Result/Sd.h
inst/include/dplyr/Result/Sum.h
inst/include/dplyr/Result/Var.h
src/hybrid_simple.cpp
tests/testthat/test-summarise.r

Evaluate summaries of summaries in R for simplicity

---

NEWS.md
src/join_exports.cpp
tests/testthat/test-joins.r

Fix rare join column name clash

---

NEWS.md
src/bind.cpp
tests/testthat/test-binds.R

fix cbind() error message for vectors

---

R/utils.r
inst/include/dplyr/Result/GroupedHybridCall.h
inst/include/tools/utils.h
src/onload.cpp
tests/testthat/test-hybrid.R

Clean data mask ourselves

---

NEWS.md
R/dataframe.R
R/distinct.R
R/group-by.r
R/grouped-df.r
tests/testthat/test-distinct.R

Support renaming columns in distinct()

---

vignettes/dplyr.Rmd

Particular should be changed to particularly.

Small typo fix

---

NEWS.md
src/arrange.cpp
tests/testthat/test-arrange.r

This was due to weird code inherited from #765

fail gracefully on data.frame columns in arrange. closes #3153

---

NEWS.md
R/colwise-select.R
R/colwise.R
R/funs.R
tests/testthat/test-colwise-select.R

Include grouping in colwise select and rename

---

NEWS.md
R/RcppExports.R
R/grouped-df.r
R/join-vars.R
R/join.r
R/tbl-df.r
inst/include/dplyr/DataFrameJoinVisitors.h
src/RcppExports.cpp
src/api.cpp
src/group_by.cpp
src/join_exports.cpp
src/set.cpp
src/utils.cpp
tests/testthat/test-joins.r

Closes #3425.
Also fixes #3266 and fixes #3417.

Compute variable names for joins in R

---

R/funs.R
tests/testthat/test-funs.R

Show clear error message for bad arguments to funs()

---

R/manip.r
man/filter.Rd

Specify `[`-type base subsetting in filter docs.

---

R/recode.R
tests/testthat/test-recode.R

Support !!! in recode_factor()

---

R/case_when.R
man/case_when.Rd

 Update `case_when()` param and return descriptions.

---

R/recode.R
man/recode.Rd

Add example of `recode()` w/ !!!.

---

R/sets.r

Fixes #3238.
I added explicit comments on duplicates handling, also added one example.
I am new to R package documentation, do I also need to build the documentation?
Let me know what you think.

improved documentation for set operations - fixes #3238

---

inst/include/dplyr/HybridHandler.h
src/hybrid.cpp
src/hybrid_count.cpp
src/hybrid_debug.cpp
src/hybrid_in.cpp
src/hybrid_minmax.cpp
src/hybrid_nth.cpp
src/hybrid_offset.cpp
src/hybrid_simple.cpp
src/hybrid_window.cpp

closes #3456
I had to copy and slightly change findFun, because the one from the R api would potentially lead to C++ destructors not being called.

no search with findFun when we know the function comes from dplyr.

---

.travis.yml
R/compat-dbplyr.R
R/tbl-df.r
man/ident.Rd
src/hybrid.cpp
src/hybrid_nth.cpp
tic.R

WIP: Support R 3.1 again

---

R/rowwise.r
cran-comments.md
inst/include/dplyr/Result/DelayedProcessor.h
inst/include/tools/pointer_vector.h
man/rowwise.Rd
src/bind.cpp

Fix UBSAN and Valgrind errors

---

DESCRIPTION
tests/testthat/test-case-when.R
tests/testthat/test-summarise.r

Related to issues #3019 and #3422

Follow up on rlang fixes

---

R/na_if.R

@romainfrancois @krlmlr added two na_if examples to address issue #3346

add na_if examples on vectors within mutate

---

R/recode.R

This closes #3221 by improving `recode()` and `recode_factor()` documentation, specifically about matching by position.
New _Rd_ has not been included in this PR. Tell me if I have to launch `devtools::document()` on my side.

Improve recode documentation

---

README.Rmd
README.md

Add cheatsheet thumbnail to README.

---

.github/lock.yml

* Add lock bot that goes into effect after 365 days.

Add lock bot 🔒🤖

---

ISSUE_TEMPLATE.md

* Avoid the link redirect (ht @mine-cetinkaya-rundel)

Update reprex link in ISSUE TEMPLATE

---

.github/CODEOWNERS

* Minimise comments and point to not-yet-existing understudies URL per HW request https://github.com/tidyverse/dplyr/commit/c9a9f2797b7fda5678209aa4fa85507318cf8258#commitcomment-29350364.

Minimise CODEOWNERS commentary

---

src/api.cpp
src/join_exports.cpp

Related to https://github.com/r-lib/conflicted/issues/8#issuecomment-395228008

Evaluate the sort call in the base environment. closes #3644

---

README.Rmd
README.md

* Add community.rstudio.com to places to get help

Separate chunk re. installing dev version

---

R/count-tally.R
man/tally.Rd

I did the roxygen documentation as well as the fix in count-tally.R It's not clear to me from the guidelines if that's a bad thing to do.

Fixed typo in tally docs.

---

vignettes/programming.Rmd

Remove UQE() examples

---

NEWS.md
src/set.cpp
tests/testthat/test-sets.R

Now keep order, for consistency with base R operations. Includes a refactoring.

Set operations

---

inst/include/dplyr/hybrid/Expression.h
src/mutate.cpp

for `mutate()` and hybrid evaluation.

More logging

---

inst/include/tools/utils.h

Fix return type for rlang::is_quosure()

---

R/utils.r

This is straightforward cleaning up

cleaning up unused functions

---

R/utils-bindings.R
inst/include/dplyr/data/DataMask.h
src/utils-bindings.cpp
tests/testthat/test-active-bindings.R
vignettes/future/dplyr_0.8.0_new_hybrid.Rmd

Refactoring, logging and tests for active bindings

---

src/filter.cpp
tests/testthat/test-filter.r

(Depends on #3854, should be merged after). 
instead of custom made `FilterVisitor` which only worked for trivial vectors (i.e. without R fallback when it's an object)

Using column_subset in filter/slice

---

R/manip.r
man/mutate.Rd

Be explicit about overwriting existing variables in mutate()

---

R/colwise.R
R/compat-dbplyr.R
R/compat-lazyeval.R
R/distinct.R
R/do.r
R/funs.R
R/group-by.r
R/join-vars.R
R/manip.r
R/order-by.R
R/tbl-cube.r
R/tbl-df.r
R/utils-expr.R
docs/articles/compatibility.html
docs/dev/articles/compatibility.html
tests/testthat/helper-dplyr.R
tests/testthat/test-binds.R
tests/testthat/test-funs.R
tests/testthat/test-joins.r
tests/testthat/test-mutate.r
vignettes/compatibility.Rmd

Cleanup rlang deprecate

---

R/colwise-arrange.R
R/colwise-distinct.R
R/colwise-filter.R
R/colwise-group-by.R
R/colwise-select.R
R/colwise.R
man/arrange_all.Rd
man/distinct_all.Rd
man/filter_all.Rd
man/group_by_all.Rd
man/scoped.Rd
man/select_all.Rd
tests/testthat/test-colwise-arrange.R
tests/testthat/test-colwise-distinct.R
tests/testthat/test-colwise-filter.R
tests/testthat/test-colwise-mutate.R
tests/testthat/test-colwise-select.R

Document semantics of colwise operations on grouping variables

---

R/recode.R

* Per https://github.com/tidyverse/dplyr/issues/3899#issuecomment-430041569

Change unquote splicing `recode()` ex. to char vec

---

DESCRIPTION
R/dataframe.R
R/funs-predicates.R
R/tbl-df.r
inst/include/dplyr/visitors/subset/column_subset.h
src/filter.cpp
tests/testthat/test-slice.r

```r
> iris %>% group_by(Species) %>% slice(1, n())
Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
<dbl>       <dbl>        <dbl>       <dbl> <fct>     
1          5.1         3.5          1.4         0.2 setosa    
2          5           3.3          1.4         0.2 setosa    
3          7           3.2          4.7         1.4 versicolor
4          5.7         2.8          4.1         1.3 versicolor
5          6.3         3.3          6           2.5 virginica 
6          5.9         3            5.1         1.8 virginica 
```

slice(.data, ...)

---

R/group-by.r
man/group_by.Rd

which is the source of the problem of #3877

illustrate empty groups in ?group_by

---

R/manip.r
man/filter.Rd

Related to #3929 
closes #3581

about order of rows in a filter() or a grouped tibble.

---

R/grouped-df.r
man/new_grouped_df.Rd

Tweak documentation for new_grouped_df()

---

DESCRIPTION
tests/testthat/test-slice.r

Just needed to skip one test about column matrices

compatibility with tibble 1.4.2

---

NEWS.md

Delete lines which seems to have been deleted in 5819434a887bb9c6221c9df608730197986d041f

Remove some duplicated lines in NEWS.md

---

R/case_when.R
R/compat-purrr.R
R/lengths.R
R/rbind.R
R/tbl-cube.r
R/zzz.r

https://github.com/tidyverse/dplyr/pull/4008#discussion_r242462915

lengths() cleanup

---

NEWS.md

I've just reorganized in sections so far. Part of #3931.

Polishing NEWS for release 0.8.0

---

DESCRIPTION
inst/include/dplyr/data/DataMask.h
inst/include/dplyr/standard/GroupedCallReducer.h
inst/include/dplyr/symbols.h
inst/include/tools/Quosure.h
inst/include/tools/utils.h
src/arrange.cpp
src/filter.cpp
src/init.cpp
src/mutate.cpp
src/summarise.cpp
tests/testthat/test-filter.r
tests/testthat/test-summarise.r
vignettes/two-table.Rmd

Fix tidyeval infloop

---

inst/include/dplyr/hybrid/scalar_result/mean_sd_var.h
inst/include/dplyr/hybrid/scalar_result/min_max.h
inst/include/dplyr/hybrid/scalar_result/sum.h
inst/include/tools/default_value.h
tests/testthat/test-summarise.r

``` r
library(dplyr)
data.frame(x = c(1, NaN)) %>%
summarise(sum = sum(x), mean = mean(x), max = max(x), min = min(x))
#>   sum mean max min
#> 1 NaN  NaN NaN NaN
```

treating NaN and NA differently

---

src/window.cpp
tests/testthat/test-window.R

Fix NA propagation rule in cumall() and cumany()

---

R/count-tally.R
man/tally.Rd

adapt doc for tally() according to new name argument. #4076

---

.travis.yml
tests/testthat/helper-combine.R

detected by `devtools::check_win_devel()`, otherwise we did get this: 
```
> test_check("dplyr")
----------- FAILURE REPORT -------------- 
--- failure: length > 1 in coercion to logical ---
--- srcref --- 
at d:\RCompile\CRANguest\R-devel\dplyr.Rcheck\tests_i386\testthat\helper-combine.R#130: 
--- package (from environment) --- 
dplyr
--- call from context --- 
combine_result(item1, item2, class1, class2, all_na1, all_na2, 
known_to_dplyr1, known_to_dplyr2, pairs$can_combine[i], pairs$warning[i])
--- call from argument --- 
class1 == "factor" && class2 == "character"
--- R stacktrace ---
where 1 at d:\RCompile\CRANguest\R-devel\dplyr.Rcheck\tests_i386\testthat\helper-combine.R#220: combine_result(item1, item2, class1, class2, all_na1, all_na2, 
known_to_dplyr1, known_to_dplyr2, …
```

remove potential length > 1 if() cases

---

R/colwise-mutate.R
tests/testthat/test-colwise-mutate.R

revert #4094 until we find a better idea. 
The fix for it was breaking a few packages, see #4174

revert #4094 for now

---

cran-comments.md

This updates the `cran-comments.md` based on results from `revdepcheck::revdep_report_cran()` ...

cran comments for release 0.8.0

---

DESCRIPTION
_pkgdown.yml

as requested in #3931. 
Should I temporarily switch back to 0.8.0 in DESCRIPTION so that it is built ?

Add link to blog post in the NEWS section

---

R/funs.R
man/funs.Rd

Closes #4150 .
Wording is taken from my suggestion in the issue thread.

Update documentation of `.args` argument in `funs()`

---

DESCRIPTION
inst/include/dplyr/data/DataMask.h
inst/include/dplyr/hybrid/Expression.h
src/filter.cpp
src/hybrid.cpp
src/utils.cpp

See #4242 for details. original findings from rchk on dplyr 0.8.0.1: https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/dplyr.out

Fix some rchk findings

---

R/colwise-filter.R
man/filter_all.Rd

fix documentation for `filter_*()`

---

NEWS.md
src/bind.cpp
tests/testthat/test-rbind.R

bind_rows() correctly handles consecutive NULLs.

---

DESCRIPTION
R/colwise-mutate.R
R/colwise-select.R
R/colwise.R
R/funs.R
revdep/README.md
revdep/problems.md
tests/testthat/test-colwise-mutate.R
tests/testthat/test-colwise.R
tests/testthat/test-funs.R

see #4287 and #4199 
``` r
df <- tibble::tibble(year = seq(2015, 2050, 5), P = 5.0 + 2.5 * year)
year <- 2037
summarise_at(df, vars(-year), ~approx(x = year, y = ., xout = !!year)$y)
#>       P
#>   <dbl>
#> 1 5098.
df <- tibble(a = 1:10, b = runif(1:10), c = letters[1:10])
varname <- "a"
symname <- rlang::sym(varname)
quoname <- enquo(symname)
df %>% mutate_at(vars(matches("b")), list(~mean(!!quoname)))
#> # A tibble: 10 x 3
#>        a     b c    
#>    <int> <dbl> <chr>
#>  1     1   5.5 a    
#>  2     2   5.5 b    
#>  3     3   5.5 c    
#>  4     4   5.5 d    
#>  5     5   5.5 e    
#>  6     6   5.5 f    
#>  7     7   5.5 g    
#>  8     8   5.5 h    
#>  9     9   5.5 i    
#> 10    10   5.5 j
```
<sup>Created on …

unquote in formulas

---

DESCRIPTION
R/funs.R
tests/testthat/test-funs.R

``` r
library(dplyr)
data.frame(x = 1:10) %>% 
summarise_at("x", c("mean", "sum"))
#>   mean sum
#> 1  5.5  55
```
<sup>Created on 2019-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

as_fun_list() auto names chr vectors.

---

NEWS.md
R/funs.R
tests/testthat/test-colwise.R

This removes the last point of pain (if I'm not missing anything) for transitioning from `funs()` to lists of formulas.

Fix colwise autonaming

---

.github/CONTRIBUTING.md

Still seeing some `“` and `”` :
```r
library(fs)
library(readr)
library(purrr)
fs::dir_ls(all = TRUE, recursive = TRUE, regexp = "[.](cpp|h|R|r|Rmd|md)$") %>% 
map_df(.id = "file", ~tibble(text = read_lines(.), line = seq_along(text))) %>% 
filter(
str_detect(file, "^([.]Rproj|revdep)", negate = TRUE), 
str_detect(text, "(\u2012|\u2013|\u2014|\u2015|\u2018|\u2019|\u201A|\u201B|\u201C)")
)
```
giving: 
```
file       text                                                                line
<chr>      <chr>                                                              <int>
1 LICENSE.md files (the “Software”), to deal in the Software without                8
2 LICENSE.md THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,       18
3 README.md  perform any …
```

using ascii apostrophe instead of right quotation mark

---

R/colwise-mutate.R
R/compat-lazyeval.R
R/dataframe.R
R/funs-predicates.R
R/funs.R
R/group-by.r
R/group-indices.R
R/grouped-df.r
R/manip.r
R/rowwise.r
R/tbl-cube.r
R/tbl-df.r

Use enquos() insted of quos()

---

NEWS.md
R/colwise.R

Ensuring `i` refers to internal loop variable, not column name

---

R/rank.R

simpler `dense_rank()`

---

R/bench-compare.r
man/bench_compare.Rd

Hello,
I hope you accept this and I to this is the correct way to make a pull request. 
David

A very small grammar mistake

---

R/case_when.R
man/case_when.Rd

update case_when() docs

---

DESCRIPTION
R/top-n.R

Second round of `top_n()` simplication :)
One hard part of tidy eval is to know when to use a function to work on values instead of manipulating expressions. Using a function is always better unless it gets in the way of translation to other backends, but here that doesn't seem to be the case.

Replace ranking expression by a function in `top_n()`

---

README.Rmd
README.md

Not sure whether or not to mention [multidplyr](https://multidplyr.tidyverse.org) — I'm hoping to get on CRAN in the next couple of weeks.

Add section on backends

---

DESCRIPTION

Change URL from `http://` to `https://`

Use https for all URLs in DESCRIPTION

---

inst/include/dplyr/data/DataMask.h
inst/include/dplyr/hybrid/Expression.h
inst/include/dplyr/hybrid/HybridVectorVectorResult.h
inst/include/dplyr/hybrid/hybrid.h
inst/include/dplyr/hybrid/scalar_result/first_last.h
inst/include/dplyr/hybrid/scalar_result/group_indices.h
inst/include/dplyr/hybrid/scalar_result/mean_sd_var.h
inst/include/dplyr/hybrid/scalar_result/min_max.h
inst/include/dplyr/hybrid/scalar_result/n.h
inst/include/dplyr/hybrid/scalar_result/n_distinct.h
inst/include/dplyr/hybrid/scalar_result/sum.h
inst/include/dplyr/hybrid/vector_result/echo.h
inst/include/dplyr/hybrid/vector_result/in.h
inst/include/dplyr/hybrid/vector_result/lead_lag.h
inst/include/dplyr/hybrid/vector_result/ntile.h
inst/include/dplyr/hybrid/vector_result/rank.h
inst/include/dplyr/hybrid/vector_result/row_number.h
inst/include/dplyr/symbols.h
src/init.cpp
src/mutate.cpp
src/summarise.cpp

requested by CRAN because not part of the official api.

Not using R_UnboundValue

---

NEWS.md
R/group_map.R
tests/testthat/test-group_map.R

Allow group_modify() to work with ... args (Fix #4509)

---

R/colwise-mutate.R
man/mutate_all.Rd
man/summarise_all.Rd

Review documentation for naming in scoped functions

---

R/tbl-cube.r
man/as.tbl_cube.Rd

This incorrect ordering of lines was introduced in pull request #1374

Fix documentation typo

---

R/group-indices.R
R/tbl-df.r
inst/bench/bench-mean.R
inst/bench/bench.R
src/dplyr.cpp
src/dplyr/symbols.h

I'm just opening this here to have a place for this conversation, so I can upload screenshots of profvis results.

Performance improvements for summarise()

---

DESCRIPTION
NEWS.md
R/dataframe.R
R/group-by.r
R/grouped-df.r
R/rowwise.r
man/group_by.Rd
man/group_indices.Rd
tests/testthat/test-dataframe.R
tests/testthat/test-grouped-df.r

Selectively ungroup variables

---

NEWS.md
R/tbl-df.r
tests/testthat/test-transmute.R

Preserve order of variables in transmute

---

R/grouped-df.r

`distinct_vars` is used on the lhs of a `%<-%` so gives a NOTE on check

avoiding a NOTE with %<-%

---

DESCRIPTION

Set tibble version

---

R/across.R
R/summarise.R
man/across.Rd
tests/testthat/test-across-errors.txt
tests/testthat/test-across.R

closes #4781 
``` r
iris %>%
group_by(Species) %>%
summarise(across(starts_with("Sepal"), mean, names = "mean_{col}"))
#>   Species    mean_Sepal.Length mean_Sepal.Width
#>   <fct>                  <dbl>            <dbl>
#> 1 setosa                  5.01             3.43
#> 2 versicolor              5.94             2.77
#> 3 virginica               6.59             2.97
iris %>%
group_by(Species) %>%
summarise(across(starts_with("Sepal"), mean, names = "{fn}_{col}"))
#> Error: {fn} cannot be used in the single function case
iris %>%
group_by(Species) %>%
summarise(across(starts_with("Sepal"), list(mean = mean, sd = sd), names = "{col}.{fn}"))
#> # A tibble: 3 x 5
#>   Species  Sepal.Length.me… Sepal.Length.sd Sepal.Width.mean …
```

+ across(names=)

---

vignettes/programming.Rmd

Proofread programming vignette

---

README.Rmd
README.md

update computational backend links

---

R/distinct.R
man/distinct.Rd

Refresh distinct docs

---

R/join.r
man/filter-joins.Rd
man/mutate-joins.Rd
man/nest_join.Rd

Proofread and update documentation for *_join functions

---

vignettes/dplyr.Rmd

fixes #4777, please review for organization changes and deletion of sections.  I still need to replace sample with slice, add relocate and switch examples from nycflights13 to starwars.

re-organized and deleted some sections.

---

R/select.R
man/select.Rd

Fixes #4793 including proofreading, updated examples, improved datasets, etc.

Refresh select() docs

---

NEWS.md

correct package name

---

R/join.r
man/filter-joins.Rd
man/mutate-joins.Rd
man/nest_join.Rd

Per [this twitter thread](https://twitter.com/dgkeyes/status/1230130159455481858)

Expanded join help for multiple variables

---

NEWS.md
vignettes/dplyr.Rmd
vignettes/grouping.Rmd

Create group by vignette

---

R/across.R
man/across.Rd
tests/testthat/test-across.R

``` r
df <- tibble(x = c(1, NA))
summarise(df, across(everything(), mean, na.rm = TRUE))
#>       x
#>   <dbl>
#> 1     1
summarise(df, across(everything(), list(mean = mean, median = median), na.rm = TRUE))
#> # A tibble: 1 x 2
#>   x_mean x_median
#>    <dbl>    <dbl>
#> 1      1        1
```
<sup>Created on 2020-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

across() passes ... to functions

---

tests/testthat/test-bind.R
tests/testthat/test-rbind.R

closes #4876 
depends on https://github.com/r-lib/vctrs/issues/855

bind_rows() puts "id" first

---

R/summarise.R
tests/testthat/test-group-by.r
tests/testthat/test-pull.R

Tweak tests

---

.github/workflows/R-CMD-check.yaml

I just re-ran `usethis::use_github_actions_tidy()`, ensuring that the `_R_CHECK_FORCE_SUGGESTS_: false` variable is kept, which seems like something that was manually turned off.
This should ensure that codecov starts working again

Update to latest actions workflow

---

DESCRIPTION
NEWS.md
R/colwise-arrange.R
R/colwise-distinct.R
R/colwise-filter.R
R/colwise-group-by.R
R/colwise-mutate.R
R/colwise-select.R
R/colwise.R
R/deprec-do.r
R/sample.R
R/top-n.R
man/all_vars.Rd
man/arrange_all.Rd
man/distinct_all.Rd
man/do.Rd
man/filter_all.Rd
man/group_by_all.Rd
man/mutate_all.Rd
man/sample_n.Rd
man/scoped.Rd
man/select_all.Rd
man/summarise_all.Rd
man/top_n.Rd
man/vars.Rd
vignettes/rowwise.Rmd

Use latest lifecycle conventions

---

R/arrange.R
tests/testthat/test-arrange.r
tests/testthat/test-filter.r
tests/testthat/test-group-by.r
tests/testthat/test-mutate.r
tests/testthat/test-select.r
tests/testthat/test-summarise.r

arrange() with 0 quosures returns input

---

DESCRIPTION
tests/testthat/test-mutate.r

Being released: https://github.com/tidyverse/glue/issues/174
This fixes a few revdeps

Depend on glue 1.3.2

---

DESCRIPTION

for https://github.com/r-lib/vctrs/pull/931

using dev vctrs 

---

R/group_data.R

use [, 0] instead of [0]

---

R/data-mask.R
R/mutate.R
tests/testthat/test-mutate.r

close #4996
``` r
df <- data.frame(x = 1, y = 2)
df %>% mutate(x2 = x, x3 = x2 + 1)
#>   x y x2 x3
#> 1 1 2  1  2
df %>% mutate(x2 = x + 0, x3 = x2 + 1)
#>   x y x2 x3
#> 1 1 2  1  2
```
<sup>Created on 2020-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Support for = <symbol> in mutate()

---

R/group_map.R
tests/testthat/test-colwise-mutate-errors.txt
tests/testthat/test-group-by-errors.txt
tests/testthat/test-group_map.R

group_map() not warning about keep= for rowwise data frame.

---

R/conditions.R
R/group_map.R
R/sets.r
tests/testthat/test-all-equal.r
tests/testthat/test-group_map-errors.txt
tests/testthat/test-mutate-errors.txt
tests/testthat/test-summarise-errors.txt

Remove extra space before ":" from error messages

---

tests/testthat/test-distinct.R
tests/testthat/test-filter.r
tests/testthat/test-join.r
tests/testthat/test-mutate.r

Revert "Don't count regroups in tests"

---

_pkgdown.yml
vignettes/base.Rmd
vignettes/colwise.Rmd
vignettes/compatibility.Rmd
vignettes/dplyr.Rmd
vignettes/grouping.Rmd
vignettes/programming.Rmd
vignettes/rowwise.Rmd
vignettes/two-table.Rmd
vignettes/window-functions.Rmd

I can't think of a particularly easy way to share the rendered result, but here's a screenshot. Hopefully that will give you a sense of how each bit of the yaml affects the final page.

Improve website navbar + article index

---

R/select-helpers.R
README.Rmd
README.md
man/group_cols.Rd

- Update link for `vars()`to point to `vars()` docs instead of scoped docs
- README updates: 
- Chapter title referred to in R4DS
- Minor copy editing
- Code formatting for multiple `filter()` conditions
- Output using starwars dataset is updated for new gender and sex columns

Minor edits

---

R/arrange.R
tests/testthat/test-arrange.r

Related: https://github.com/tidyverse/tibble/issues/767

Avoid unname() on tibbles

---

R/generics.R
man/dplyr_extending.Rd

Incorporates fixes and considerably improves the documentation along the lines suggested by @davisvaughan.
Fixes #5161

Improvements to dplyr extensibility

---

R/across.R
R/arrange.R
R/conditions.R
R/filter.R
R/grouped-df.r
R/mutate.R
R/summarise.R
R/ts.R
src/conditions.cpp
src/dplyr.h
src/filter.cpp
src/mutate.cpp
tests/testthat/test-across-errors.txt
tests/testthat/test-arrange-errors.txt
tests/testthat/test-colwise-mutate-errors.txt
tests/testthat/test-filter-errors.txt
tests/testthat/test-mutate-errors.txt
tests/testthat/test-summarise-errors.txt

error messages improvements

---

R/generics.R

instead of dplyr_reconstruct.data.frame()
closes #5195

dplyr_col_modify.data.frame() calling dplyr_reconstruct()

---

R/group_map.R
R/group_nest.R
R/group_split.R
R/nest_by.R
man/group_map.Rd
man/group_split.Rd
tests/testthat/test-group_map.R
tests/testthat/test-group_split.R

probably also needs `group_map()` and `group_modify()`

group_split(keep=) -> group_split(.keep=)

---

R/filter.R
tests/testthat/test-filter.r

Ensure that `filter()` always calls `dplyr_row_slice()`

---

R/pull.R
man/pull.Rd

To make it easier for generics to extend

Add ... to pull()

---

.github/workflows/R-CMD-check.yaml

Fix the r-devel job

---

R/funs.R
man/between.Rd

Given that many people may encounter `between` after only having experience with the tidyverse, a `filter` example might be nice so that they can readily see how they'd use it in there code.

Add filter example to between

---

vignettes/window-functions.Rmd

Make the comment a bit clearer

Update a comment in window-functions.Rmd

---

R/rows.R
tests/testthat/test-rows.R

Remove error classes for now

---

vignettes/programming.Rmd

Fix typo reported by kyzphong in 'Programming with dplyr' vignette example

#5283 - Fix Typo in Vignette

---

R/colwise.R
tests/testthat/test-colwise-mutate.R

Use `.env$i` in `tbl_if_vars()`

---

R/arrange.R
man/arrange.Rd

A couple of typos

---

vignettes/dplyr.Rmd

Fix typo in example comment

---

R/join-rows.R
tests/testthat/test-join.r

This seems to be fixing #5359 but quite possible I'm missing cases.

full_join(na_matches = "never")

---

R/summarise.R
man/summarise.Rd

closes #5350.
Minor documentation addenddum. @jam1015 does that help ?

phrase in terms of number of rows instead of size.

---

R/mutate.R
tests/testthat/test-mutate.r

Only unchop mutate() result when needed

---

vignettes/programming.Rmd

Should be `summarise_var` instead of `group_var` here I think

Small error in line 317

---

R/bind.r
revdep/README.md
revdep/failures.md
revdep/problems.md
tests/testthat/test-bind.R

Converting to tibble in bind_rows() as in dplyr 1.0.0

---

R/slice.R
tests/testthat/test-slice.r

check for empty ellipsis in slice_*()

---

DESCRIPTION
NEWS.md
R/bind.r
man/bind.Rd
tests/testthat/test-bind.R

+ bind_cols(.name_repair=) passed to vctrs::vec_cbind().

---

NEWS.md
R/across.R
tests/testthat/test-across.R

Fix scoping issue with `across()` in nested mutates

---

R/progress.R

Super trivial but I happened upon this line and figured I'd just fix it.

Fix typo in inline comment

---

R/group_data.R
src/dplyr.h
src/group_data.cpp
tests/testthat/test-group_data.R

avoid INTEGER(x) when x is size 0.

---

R/mutate.R
tests/testthat/test-mutate-errors.txt
tests/testthat/test-mutate.r

use mask$get_current_group() to get the current group, rather than `i`

---

src/dplyr.h

instead of the defunct `R_NOREMAP`.

Use R_NO_REMAP

---

R/data-starwars.R
man/starwars.Rd

update doc for starwars.

---

R/group_data.R
man/group_data.Rd

Mention cur_group_id() in group_indices() documentation.

---

NEWS.md
R/relocate.R
man/relocate.Rd
tests/testthat/test-relocate.R

relocate() can rename columns that are moved

---

NEWS.md
R/generics.R
tests/testthat/test-generics.R
tests/testthat/test-mutate.r

Preserve row names in mutate

---

R/summarise.R
tests/testthat/test-summarise-errors.txt

clearer summarise() information on unspecified .groups=

---

R/group_data.R
man/group_data.Rd

wrong function name in `group_data()` documentation

typo in `group_data` doc

---

R/lead-lag.R
tests/testthat/test-lead-lag-errors.txt
tests/testthat/test-lead-lag.R

lead() and lag() assert the size of default=

---

R/deprec-do.r
tests/testthat/test-do-errors.txt

- lifecycle warning about progress_estimated() on legitimate uses of do()

---

.github/workflows/R-CMD-check.yaml
vignettes/window-functions.Rmd

Don't evaluate window vignette if no Lahman

---

R/arrange.R
R/mutate.R
tests/testthat/test-arrange-errors.txt
tests/testthat/test-mutate-errors.txt
tests/testthat/test-summarise-errors.txt

Attempt to improve arrange(<column>) error cwhen <column> is not found.

---

_pkgdown.yml

Add ?rows to pkgdown index

---

R/conditions.R
R/mutate.R

warnings not masquarading as errors in the bullets.

---

R/grouped-df.r

... as https://github.com/r-lib/vctrs/issues/1298 is now resolved

simplify vec_split_id_order()

---

R/distinct.R
man/n_distinct.Rd

Hi there 👋 "set of vector" seems like a spelling mistake (maybe because the `f` key is adjecent to `r`). Should it be "or vector" or "of vectors", maybe?

Correct typo in n_distinct title

---

NEWS.md
R/group-by.r
tests/testthat/test-group-by.r

Closes tidyverse/lubridate#959

Fix quosure handling in `group_by()`

---

R/mutate.R
R/summarise.R
tests/testthat/test-across.R

reset current column with top_across()

---

README.Rmd
README.md

Related: https://github.com/rstudio/cheatsheets/pull/163

Readme.Rmd spelling of `Cheatsheet` -> `Cheat Sheet`

---

NEWS.md
R/select.R
tests/testthat/_snaps/select.md
tests/testthat/test-select.r

select() not creating duplicate variable on grouped data frames.

---

R/across.R
R/conditions.R
R/filter.R
R/mutate.R
R/summarise.R
tests/testthat/_snaps/across.md
tests/testthat/_snaps/arrange.md
tests/testthat/_snaps/colwise-mutate.md
tests/testthat/_snaps/distinct.md
tests/testthat/_snaps/filter.md
tests/testthat/_snaps/group-by.md
tests/testthat/_snaps/mutate.md
tests/testthat/_snaps/summarise.md

simplify error messages

---

NEWS.md
R/summarise.R
tests/testthat/_snaps/summarise.md

`summarise.rowwise_df()` is quiet when the result is ungrouped

---

R/across.R
man/across.Rd
man/reexports.Rd

add detail to doc for if_any() and if_all().

---

vignettes/two-table.Rmd

- Remove quotes in library 
- Clarify sentence

Minor edits in two table vignette

---

vignettes/colwise.Rmd

using n_distinct() instead of length(unique()) in colwise vighnette.

---

R/colwise-arrange.R
R/colwise-distinct.R
R/colwise-filter.R
R/colwise-group-by.R
R/colwise-mutate.R
man/arrange_all.Rd
man/distinct_all.Rd
man/filter_all.Rd
man/group_by_all.Rd
man/mutate_all.Rd
man/pull.Rd
man/summarise_all.Rd

Just noticed that these were still listed in the package docs; I think it's time to delist them.

Mark colwise functions as internal

---

NEWS.md
R/slice.R
man/slice.Rd
tests/testthat/_snaps/slice.md
tests/testthat/test-slice.r

Allow negative `n` in `slice_head` and `slice_tail`

---

DESCRIPTION
R/compat-dbplyr.R
R/compute-collect.r
R/deprec-dbi.R
R/deprec-do.r
R/explain.r
R/group_map.R
R/nest_by.R
R/pull.R
man/across.Rd
man/check_dbplyr.Rd
man/compute.Rd
man/do.Rd
man/explain.Rd
man/group_map.Rd
man/ident.Rd
man/nest_by.Rd
man/pull.Rd
man/select.Rd
man/src_dbi.Rd
tests/testthat/test-count-tally.r

Requires dev roxygen2 for `@examplesIf` .

Only run example if RSQLite is installed

---

.github/workflows/R-CMD-check.yaml

xenial is EOL, currently RSQLite fails to install there (https://github.com/r-dbi/RSQLite/issues/378).

Check with bionic instead of xenial

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/test-coverage.yaml

There were a few issues with the pkgdown workflow in the last GH workflows update which have been fixed upstream now (along with a number of other changes)

Update GitHub Actions to latest r-lib/actions workflows

---

NEWS.md
R/group-by.r
man/group_by.Rd
man/nest_by.Rd
man/new_grouped_df.Rd
man/pull.Rd
man/slice.Rd
tests/testthat/test-group-by.r

group_by(<computation>) always done on the ungrouped data

---

R/bind.r
man/bind.Rd

Remove `\dontrun{}` in favor of `try()`

---

.github/workflows/R-CMD-check.yaml
.github/workflows/continuous-benchmarks.yaml
README.Rmd

update GitHub actions

---

R/grouped-df.r
R/rowwise.r

For https://github.com/r-lib/pillar/issues/250.

Add ellipsis to tbl_sum()

---

tests/testthat/_snaps/across.md
tests/testthat/_snaps/arrange.md
tests/testthat/_snaps/bind.md
tests/testthat/_snaps/colwise-mutate.md
tests/testthat/_snaps/distinct.md
tests/testthat/_snaps/filter.md
tests/testthat/_snaps/group-by.md
tests/testthat/_snaps/grouped-df.md
tests/testthat/_snaps/mutate.md
tests/testthat/_snaps/slice.md
tests/testthat/_snaps/summarise.md

remove noise from using rlang after this commit: https://github.com/r-lib/rlang/commit/1bf56d02f363a7df31c54f33c059894d029529c3

cancel snapshot noise

---

NEWS.md
R/arrange.R
R/mutate.R
man/mutate.Rd
tests/testthat/_snaps/arrange.md
tests/testthat/test-transmute.R

Closes #6086, see that issue for the full details

Separate `transmute()` and `mutate(.keep = "none")`

---

R/sample.R
R/slice.R
tests/testthat/test-slice.r

slice_*() careful about {{ }}

---

R/across.R
tests/testthat/test-across.R

Fix lambda expansion

---

R/mutate.R
R/summarise.R
tests/testthat/_snaps/arrange.md
tests/testthat/_snaps/conditions.md
tests/testthat/_snaps/mutate.md
tests/testthat/_snaps/summarise.md

And use "can't" instead of "cannot".

Use cross symbol for "can't" and "must" bullets

---

R/colwise-select.R
man/select_all.Rd

This simple PR is for https://github.com/tidyverse/dplyr/issues/6010.  Let me know if I should include the updated .Rd file in the PR as well.  Thanks!

Add where() mention in colwise-select documentation (#6010)

---

R/slice.R
tests/testthat/test-slice.r

This is a follow up to https://github.com/tidyverse/dplyr/pull/6172
Not doing `min(, n)` made `slice_head(n = Inf)` break. This was causing failure for package `modeltime`.

slice_head,tail() handle n,prop = Inf

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/test-coverage.yaml
README.Rmd
README.md

Many of these were still on v1! I'm hoping this fixes whatever weird pkgdown issue we are having

Update GitHub Actions workflows

---

R/bind.r
man/bind.Rd

Name of .id argument was a bit ambiguous - clarified to state that it defines the name of the column

update bind.r documentation

---

DESCRIPTION
man/ident.Rd

A typo was fixed there that we import here

Redocument with CRAN dbplyr

---

NEWS.md
R/order-by.R
tests/testthat/test-order-by.R

Closes #6334 
Admittedly rare, but easy to fix for completeness

Fix `with_order()` with data frame `order_by` values

---

NEWS.md
R/desc.r
tests/testthat/_snaps/desc.md
tests/testthat/test-desc.r

Check type of `desc()`

---

NEWS.md
R/distinct.R
tests/testthat/_snaps/distinct.md
tests/testthat/test-distinct.R

Respect requested variable order in distinct()

---

NEWS.md
R/all-equal.r
man/all_equal.Rd
tests/testthat/_snaps/all-equal.md
tests/testthat/test-all-equal.r
tests/testthat/test-group_nest.R

Deprecate `all_equal()`

---

R/doc-params.R
man/dplyr_data_masking.Rd
vignettes/programming.Rmd

Fixes #5836. Fixes #5823. Fixes #5859.

Describe name injection; add two new examples

---

NEWS.md
R/arrange.R

Use consistent definiton of desc in arrange()

---

NEWS.md
R/arrange.R
tests/testthat/test-arrange.r

Ignore NULLs in arrange()

---

NEWS.md
R/mutate.R
tests/testthat/_snaps/mutate.md
tests/testthat/test-mutate.r

Automatically unlist() lists of length 1 vectors

---

R/join-by.R
R/join-cols.R
R/join.r
tests/testthat/_snaps/join-by.md
tests/testthat/_snaps/join-cols.md
tests/testthat/_snaps/join.md
tests/testthat/test-join.r

Check possible values of keep

---

NEWS.md
R/mutate.R
src/chop.cpp
tests/testthat/test-mutate.r

Better handling of zero-row rowwise mutates()

---

NEWS.md
R/nth-value.R
man/nth.Rd
tests/testthat/_snaps/nth-value.md
tests/testthat/test-nth-value.R

Closes #6257 
Closes #6242 
@tnederlof you did a great job with #6257, but unfortunately I rewrote `nth()` after you sent in your PR and it was a little complicated to line everything back up. I've built off your PR here, and credited you in the NEWS bullet. Thanks!
Fairly straightforward implementation. Main thing is to remember to update the `size` variable and to also slice `order_by` if it exists.

Add `na_rm` to `nth()`, `first()`, and `last()`

---

tests/testthat/_snaps/mutate.md
tests/testthat/test-mutate.r

Tweak test to refine beliefs hashed out in #6305

---

R/summarise.R

Fix typo in signature

---

man/nest_join.Rd
man/select.Rd

Document with pillar 1.8.1

---

R/mutate.R
tests/testthat/_snaps/conditions.md
tests/testthat/test-conditions.R

Force dots before setting up error handlers

---

NEWS.md
R/rank.R
man/ntile.Rd
man/percent_rank.Rd
man/row_number.Rd
tests/testthat/_snaps/rank.md
tests/testthat/test-rank.R

Closes #6428 
Also now enforcing that the `n` argument of `ntile()` is a single positive integer

Use `vec_rank()` in ranking functions

---

DESCRIPTION

Use CRAN lifecycle

---

R/join-rows.R
tests/testthat/_snaps/join-rows.md
tests/testthat/test-join-rows.R

Tweak multi-match warning

---

R/sample.R
man/sample_n.Rd

Improve sample_n() docs

---

R/conditions.R
R/filter.R
src/dplyr.h
src/filter.cpp
src/init.cpp
tests/testthat/_snaps/filter.md

Set up for https://github.com/tidyverse/dplyr/issues/6091

Use lifecycle infrastructure for `filter()` deprecation warnings

---

src/dplyr.h
src/filter.cpp
tests/testthat/_snaps/filter.md
tests/testthat/test-filter.R

Also has the tiny behavior change of ensuring that we actually error on logical arrays of >2 dimensions now
I was able to remove quite a bit of dead code too!

Update `filter.cpp` style

---

R/conditions.R
tests/testthat/_snaps/across.md
tests/testthat/_snaps/conditions.md
tests/testthat/_snaps/mutate.md

Mention "argument" in input context bullet

---

R/join-cols.R
tests/testthat/_snaps/join-cols.md

Incremental error message improvement noticed while looking at #6499

Improve on `check_join_vars()` error messages

---

tests/testthat/test-join-cols.R
tests/testthat/test-join.R

Making sure we test the current behavior of the issues in #6499 before making any changes

Test current behavior of unique non-equi keys and `keep = FALSE`

---

R/slice.R
man/slice.Rd

Since there is a note about `tail()`, I think it would be better if about `head()` was also written.

Docs: Add note about `head()`

---

R/copy-to.R
R/rows.R
man/copy_to.Rd
man/nest_join.Rd
man/rows.Rd

Fixes #6452
@DavisVaughan this just needs a second pair of eyes to make sure I didn't make any copy and paste errors.

Link to more methods

---

NEWS.md
R/slice.R
tests/testthat/_snaps/conditions.md
tests/testthat/_snaps/slice.md
tests/testthat/test-conditions.R
tests/testthat/test-slice.R

Use `check_dots_unnamed()` in `slice()`

---

R/mutate.R
tests/testthat/test-mutate.R

@krlmlr I think I've managed to simplify the `mutate()` refactor even further.
This merges directly into your branch, would you mind taking a look?

Simplify `mutate()` even further

---

R/slice.R

Closes #6600 
Part of https://github.com/tidyverse/dplyr/issues/6262
Confirmed that this fixes tidyterra

Move empty dots check to the methods

---

R/join.R
tests/testthat/_snaps/join.md

Closes #6599
Part of #6262 
Confirmed that this fixes dm and table.express

Move check into methods and switch to empty dots check

---

R/group-by.R
tests/testthat/_snaps/group-by.md
tests/testthat/test-group-by.R

Fix partial ungrouping

---

R/deprec-lazyeval.R

Closes https://github.com/tidyverse/dplyr/issues/6641

Pass `env` and `user_env` through `lazy_deprec()`

---

DESCRIPTION
R/sets.R

Can wait until vctrs is released to merge.

Use `vec_set_*()` in set operation methods

---

R/slice.R

This is what was causing `Run tests` in `test-slice.R` to always change the snapshots related to this

Pass correct environments to `deprecate_warn()` in `slice_eval()`

---

R/compute-collect.R

This slightly simplifies extraction from dplyr's implementation needed elsewhere.

Add braces to methods

---

vignettes/compatibility.Rmd

Closes #6668 
Probably worth rewriting the whole vignette at some point. I doubt we really need the dbplyr sections anymore.

Tweak advice about conditional usage of new functions

---

NEWS.md
R/generics.R
man/dplyr_extending.Rd

Closes https://github.com/tidyverse/dplyr/issues/6695

Refresh `?dplyr_extending`

---

src/dplyr.h
src/imports.cpp
src/mutate.cpp
src/summarise.cpp

Related to https://github.com/r-lib/vctrs/pull/1786

Switch from `vec_is_vector()` to `obj_is_vector()`

---

tests/testthat/test-mutate.R
tests/testthat/test-summarise.R

This is easy to get wrong, an implicit test helps.

Add test implied by other test in deprec-lazyeval.R

---

NEWS.md
R/pick.R
man/pick.Rd
tests/testthat/_snaps/pick.md
tests/testthat/test-pick.R

Force `pick()` empty selections to result in 1 row tibbles

---

R/across.R
man/across.Rd

Closes https://github.com/tidyverse/dplyr/issues/6754

Add named `all_of()` examples to `across()` docs

---

R/slice.R
tests/testthat/_snaps/slice.md
tests/testthat/test-slice.R

Only refer to our `clamp()` and base functions `floor()`, `ceiling()` and arithmetics.

Generate better code in get_slice_size()

---

NEWS.md
R/copy-to.R
tests/testthat/_snaps/copy-to.md
tests/testthat/test-copy-to.R

Closes https://github.com/tidyverse/dplyr/issues/6798

Improve `auto_copy()` different source error

---

NEWS.md
R/join-cols.R
tests/testthat/test-join-cols.R
tests/testthat/test-join.R

Finalize the join key ptype

---

tests/testthat/test-deprec-combine.R

Which now actually checks the imaginary part of complex numbers
We'll also need to do a patch release in the next couple of weeks.

Fix for dev waldo

---

vignettes/rowwise.Rmd

Avoid selecting `id` in the `rowSums()` / `rowMeans()` examples

---

tests/testthat/test-join.R

I haven't found any behavior tests in the test suite.

Add tests for closest()

---

data-raw/starwars.R

The following is an edit on the starwars.R dataset source file which amends a trivial issue to improve readability.

trivial change to dataset documentation

---

DESCRIPTION
man/bind_cols.Rd
man/case_match.Rd
man/coalesce.Rd
man/if_else.Rd
man/na_if.Rd

For the `theory-faq-recycling` change

Redocument with CRAN vctrs

---

tests/testthat/_snaps/across.md
tests/testthat/_snaps/by.md
tests/testthat/_snaps/colwise-mutate.md
tests/testthat/_snaps/conditions.md
tests/testthat/_snaps/group-by.md
tests/testthat/_snaps/pick.md
tests/testthat/_snaps/select.md

For:
- https://github.com/r-lib/tidyselect/pull/326
- https://github.com/r-lib/tidyselect/commit/1822141ae972ee23a2f307855583f9728bac3a8e

Update snapshots for tidyselect 1.2.1

---

R/funs.R
man/cumall.Rd

Fix typo in cumulative function docs #7062

Fix typo in cumulative function docs

---

R/group-by.R
man/group_by.Rd
man/nest_by.Rd

Closes https://github.com/tidyverse/dplyr/issues/7030

[document] group_by works with data-masking, issue #7030

---

R/context.R
R/utils.R
tests/testthat/_snaps/context.md
tests/testthat/_snaps/summarise.md
tests/testthat/test-summarise.R

Fixes snapshot test failures, related to the fix for https://github.com/r-lib/cli/issues/681

Force comma separated group labels at all times

---

man/rmd/select.Rmd
man/select.Rd

Add rename feature of dplyr select to docs

---

NEWS.md
R/slice.R
man/slice.Rd

Add example for slice_sample
