tidyverse/dplyr

- R/cluster.R
I believe you need to remove the cluster in `cluster_env` rather than setting it to `NULL` because you use `exists` to check if the clusters have been initialized or not in `has_cluster`.
> Properly remove cluster in stop_cluster

- README.md
I had to search the news to find out that MonetDB support is now via MonetDB.R. So the README was updated to reflect this fact.
> MonetDB is supported via MonetDB.R

- inst/include/dplyr/Gatherer.h
This would send messages like
Error : incompatible size (%d), expecting %d (the group size) or 1
This adds the right arguments to stop().
> Gatherer: fix "incompatible size" error message.

- vignettes/hybrid-evaluation.Rmd
And because `cpp` is not an existing engine name in knitr, this will lead to errors.
> ```{cpp} means ```{r, engine='cpp'} in the next version of knitr

- .gitignore
- inst/include/dplyr/Result/Reducer.h
`OUT` is `#define`'d in such a way on Windows that it breaks `Reducer.h`. This PR just renames that template parameter to avoid the problem.
> avoid using name OUT

- R/dplyr.r
- man/dplyr.Rd
"focussed" has been corrected to "focused."
Rd documentation has been regenerated accordingly using roxygen.
> Fix typo in dplyr.R documentation

- R/colwise.R
In the commit https://github.com/hadley/dplyr/commit/65aef3a99725cd8bdd70e936f56e61f95acbc500, `summarise_each()` was modified from
```r
summarise_each <- function(tbl, funs, ...) {
env <- parent.frame()
summarise_each_q(tbl, funs, dots(...), env)
}
```
to
```r
summarise_each <- function(tbl, funs, ...) {
summarise_each_(tbl, funs, lazyeval::lazy_dots(...))
}
```
And `mutate_each()` was modified from
```r
mutate_each <- function(tbl, funs, ...) {
env <- parent.frame()
mutate_each_q(tbl, funs, dots(...), env)
}
```
to
```r
mutate_each <- function(tbl, funs, ...) {
mutate_each_(tbl, funs, dots(...))
}
```
I think you forgot to replace `dots()` with `lazy_dots()` in `mutate_each()`.
This will cause the following problem.
```r
match_str <- "Width"
iris %>% mutate_each(funs(max), …
```
> You forgot to replace dots() with lazy_dots() in mutate_each()

- R/colwise.R
Please add these aliases as well, I default to summarize and get caught out when using summarise_each. 
Cheers, Mike.
> summarize spelling for summarise_each as well

- tests/testthat/test-joins.r
Tests that join operations don't change the source data tables. Fails if data.table::copy is omitted in `join_dt()`.
Related to #659.
> Test for join over data tables

- vignettes/new-sql-backend.Rmd
> Fixed typo in new-sql-backend.Rmd

- vignettes/new-sql-backend.Rmd
The argument x in the function was not referenced and the variable con was used in the body of the function but not an argument. The intention was for the argument to be called con.
> x -> con to be consistent with rest of the example

- R/src-postgres.r
Introduce validation on the values parameter to be inserted into the database before constructing the SQL. This is a proposed solution to the issue #1214
> More gracefully handle 0 row insert

- R/translate-sql-base.r
Do this to make it easier to write adaptable code with the recently
added n_distinct() convenience function available in dplyr.  The
DISTINCT option to SQL's COUNT() was part of the SQL-92 standards.
> Add n_distinct() to SQL base_aggs.

- inst/include/dplyr/Collecter.h
- tests/testthat/test-rbind.r
related to the comment here: https://github.com/hadley/dplyr/commit/683445aac7d1f56b34d1ca4e674c52b230a71c63#commitcomment-12865692
Two `POSIXct` are always considered compatible, and I updated the way we determine the `tzone` of the result.
> bind_rows can handle POSIXct of various time zones

- NEWS.md
- R/RcppExports.R
- R/rbind.r
- inst/include/tools/DotsOf.h
- man/bind.Rd
- src/RcppExports.cpp
- src/bind.cpp
- tests/testthat/test-rbind.r
This makes row_binds append an identifier column when the `.id` argument is supplied.
This is useful for the common use case of combining data frames to be used for example by ggplot2. Best used with lowliner :-)
```
fits <- list(lm(disp ~ cyl, mtcars), lm(disp ~ mpg, mtcars)) %>%
map(broom::tidy) %>%
bind_rows(.id = "model")
##
```
> Add .id argument to bind_rows

- NEWS.md
- R/src-postgres.r
```R
con = src_postgres()
data = copy_to(con, tbl_df( data.frame(l=LETTERS)), name = dplyr:::random_table_name() )
print( summarize(data, m=paste(l, collapse="/")))
```
The code above fails yielding:
```
Error in postgresqlExecStatement(conn, statement, ...) :
RS-DBI driver: (could not Retrieve the result : ERROR:  type "l" does not exist
LINE 2: FROM (SELECT string_agg("l"'/') AS "m"
```
Simply missing a comma. With this patch applied you get the expected:
```
Source: postgres 9.4.4 [gt5392c@localhost:5432/gt5392c]
From: <derived table> [?? x 1]
m
1  A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X/Y/Z
..                                                 ...
> Postgres: Add missing comma to build_sql call used translate paste()

- R/tbl-cube.r
Fixed 2 typos:
"An cube" --> "A cube"
"supported for" --> "support for"
> fixed typo in tbl-cube.R

- NEWS.md
- R/tbl-cube.r
- man/as.tbl_cube.Rd
- to make it consistent with the `tbl_cube` constructor
- to allow adding a `met_name` argument to `as.tbl_cube.data.frame` later
Also, the `met_name` argument to `as.tbl_cube.table` now defaults to `"Freq"` for consistency with `as.data.frame.table`.
This is a breaking change, but perhaps justified since
> `tbl_cube` support is currently experimental
> Swap order of dim_names and met_name in as.tbl_cube

- src/matrixToDataFrame.cpp
Probably we also want a meaningful error message if the type is not supported (`default` branch).
Related: hadley/tidyr#134.
> Support complex values in matrixToDataFrame

- R/do.r
- tests/testthat/test-do.R
- tests/testthat/test-rbind.r
Otherwise, every use of `do()` generates the deprecation warning. I assume it should change in the tests as well?
``` r
library(dplyr)
library(broom)
iris %>% 
group_by(Species) %>% 
do(tidy(lm(Sepal.Width ~ Sepal.Length, .)))
#> Warning: `rbind_all()` is deprecated. Please use `bind_rows()` instead.
#> Source: local data frame [6 x 6]
#> Groups: Species [3]
#> 
#>      Species         term   estimate  std.error statistic      p.value
#>       (fctr)        (chr)      (dbl)      (dbl)     (dbl)        (dbl)
#> 1     setosa  (Intercept) -0.5694327 0.52171193 -1.091470 2.805148e-01
#> 2     setosa Sepal.Length  0.7985283 0.10396505  7.680738 6.709843e-10
#> 3 versicolor  (Intercept)  0.8721460 0.44465989  1.961378 5.564956e-02
#> 4 versicolor Sepal.Length  0.3197193 0.07463300  4.283887 …
```
> Use bind_rows instead of rbind_all in do()

- R/src-sqlite.r
The current behavior of src_sqlite when create = TRUE is to connect to
the existing database if it is present and to create a new database if
there is no file at the specified path. The docs are not explicit about
using the existing database if it is present, which has caused some
confusion in at least one instance [1].
This change makes the current behavior explicit in the documentation.
[1] https://github.com/weecology/bbs-forecasting/pull/16#discussion_r52901968
> Make current behavior of create argument in src_sqlite explicit

- NEWS.md
- R/glimpse.R
`glimpse` currently breaks a chain of dplyr verbs:
e.g.
```R
my_iris <- 
iris %>%
glimpse %>%
rename(species = Species)
```
gives an error.
This pull request lets `glimpse` return its inputs and  makes it possible to "debug"  your data processing chain by including it at various locations.
> Let `glimpse` invisibly return original `x`

- .gitattributes
- NEWS.md
- R/tbl-sql.r
Solved by forcing the `vars` argument in `tbl_sql()`. The default for this argument is an attribute of the `from` argument, but that argument gets overwritten before this attribute is extracted.
Currently, `update.tbl_sql()` always needs to run `db_query_fields()` e.g. for a `left_join()`.
Closes #1549.
> Don't execute query for determining variable names if they are known

- vignettes/hybrid-evaluation.Rmd
trivial fix for correctly formatted MD lists in HTML output.
> add blank lines so md lists render correctly.

- inst/include/tools/complex.h
passes R CMD check with both Rcpp 0.12.1 and 0.12.2
> make operator<<() definition for Rcomplex conditional on Rcpp <= 0.12.2

- R/case_when.R
- R/utils.r
- tests/testthat/test-case-when.R
by showing the expression that fails.  Useful for `transmute()` fests where many variables are recoded.
~~Implementation: New eval_with_expr() and expr() that store the original expression along with the result.~~
Also fixes glitch in the first LHS error message ([ vs. [[).
With test.
Related to #631.
> More verbose error messages in case_when()

- NEWS.md
- R/progress.R
I noticed that RStudio has a high CPU load while running `do` on data frames with many groups and short operations. I traced this to the fact that the progress bar is re-drawn for each tick, even if it hasn't changed since the last update. 
I therefore added a check for when the progress bar has been drawn the last time, and update only if this is more than 50 ms ago. A simple test revealed that this can save a lot of overhead without noticeable changes (first run: normal dplyr, second run: with `last_update` check):
```
> d <- data.frame(x=1:100000)
> system.time(invisible(d %>% group_by(x) %>% do(x=0)))
|==========================================================================================|100% ~0 s remaining        
user  system elapsed
33.535   2.976  28.715 
Restarting R …
```
> update the progress bar only 20 times per second

- R/tbl-sql.r
@hadley: Am I subclassing a `tbl_sql` incorrectly or are we missing to subclass this in dplyr?
This is what I'm doing:
```
#' @export
tbl.src_s <- function(src, from, ...) {
tbl_sql("s", src = src, from = from, ...)
}
```
However, the generated table is not of type "s". The change in the PR solves this issue.
> allow tables to be subclassed

- R/over.R
- R/sql-build.R
@hadley: While trying to generate a dplyr partition for this expression for a new backend:
`tbl(db, "flights") %>% filter(min_rank(dep_time) < 2) %>% collect`
the generated SQL was this: 
```
<SQL> SELECT *
FROM (SELECT `year`, `month`, `day`, `dep_time`, `dep_delay`, `arr_time`, `arr_delay`, `carrier`, `tailnum`, `flight`, `origin`, `dest`, `air_time`, `distance`, `hour`, `minute`
FROM (SELECT `year`, `month`, `day`, `dep_time`, `dep_delay`, `arr_time`, `arr_delay`, `carrier`, `tailnum`, `flight`, `origin`, `dest`, `air_time`, `distance`, `hour`, `minute`, rank() OVER (PARTITION BY ORDER BY `dep_time`) AS `zzz4`
FROM `flights`) `mflbvzuway`
WHERE ("zzz4" < 2.0)) `kgbnssdkik`
LIMIT 100000
```
Notice:
1) The `PARTITION BY ORDER BY` clause, this was being caused by, `op_grps.op_base <- …
> avoid generating PARTITION BY for empty ones

- DESCRIPTION
devtools can't currently handle this in a nice way, I've tried quite a few different configurations.
Looks like dplyr -> (suggests) dtplyr -> (imports, with version) dplyr, in combination with remotes, is the problem here.
Fixes #1809.
> Remove dtplyr from Remotes

- R/translate-sql.r
Need to escape partition fields, for instance, this sql:
```
... rank() OVER (PARTITION BY "playerID" ORDER BY "H" DESC) AS `zzz4` ...
```
Now generates as:
```
... rank() OVER (PARTITION BY `playerID` ORDER BY `H` DESC) AS `zzz4` ...
```
> escape partition fields for window functions

- inst/include/dplyr/DataFrameSubsetVisitors.h
- src/api.cpp
(Disclaimer: I'm not familiar with C++)
This temporarily fixes #1814.
As I wrote in #1814, this problem is about template class. Since the compiler compiles templates only with the types that are actually used, if the type purrr uses is not used in dplyr, it is not compiled and occurs `undefined reference to ...` error. In this case, exporting the class whole in header file is right way in my understanding.
So, could you consider reverting 04704bf for now? I know this may not be an ultimate solution, but not a few people must suffer from failing to install purrr with dev version of dplyr.
> revert 04704bf to enable installing purrr again

- NEWS.md
- R/RcppExports.R
- R/rowwise.r
- src/RcppExports.cpp
- src/dplyr.cpp
- tests/testthat/test-arrange.r
- tests/testthat/test-filter.r
- tests/testthat/test-group-by.r
- tests/testthat/test-mutate.r
- tests/testthat/test-select.r
- tests/testthat/test-summarise.r
This problem already exists in v0.4.3.
Fixes #1803.
> Fix type check for unclassed objects

- NEWS.md
- R/select-utils.R
- man/select_helpers.Rd
- tests/testthat/test-select-helpers.R
I want to say "if variable x is present, keep it; but don't worry if it's not" inside `dplyr::select()`. I have a pipeline where a certain variable will be there sometimes but not others.
```
select(head(iris, 3), one_of(c("Sepal.Length", "Stem.Length")))
#>   Sepal.Length
#> 1          5.1
#> 2          4.9
#> 3          4.7
#> Warning message:
#> In one_of(c("Sepal.Length", "Stem.Length")) :
#>   Unknown variables: `Stem.Length`
```
> tolerate unknown vars in one_of()

- R/recode.R
- man/recode.Rd
- tests/testthat/test-recode.R
This fixes a couple of issues for recoding factors:
- `recode.factor()` now uses `.x` as default when `.default` is NULL, just like the other methods
- `recode_factor()` handles vector default better
> Improve default handling in recode.factor() and recode_factor()

- inst/include/dplyr/Collecter.h
from POSIXctCollecter class, introduced in 2743b605a496b734e8
@romainfrancois: Looks to me like this was intended, but please double-check.
> Remove dead code

- R/join.r
Now:
```
Joining, by = "a"
Joining, by = c("b", "c")
```
The user can copy the text starting at the comma until the end and just paste it into the join call.
Original issue: https://github.com/hadley/dplyr/issues/1783#issuecomment-221874823
> Valid R syntax for message printed when performing a natural join

- NEWS.md
- src/dplyr.cpp
- tests/testthat/test-equality.r
- legible error message for raw types which cannot be handled currently
- show message if types are incompatible and convert = TRUE
- tests
> all_equal() fixes

- inst/include/dplyr/Collecter.h
- inst/include/dplyr/Result/GroupedSubset.h
- tests/testthat/test-binds.R
instead of segfaulting.
Fixes #1789.
Also fixes another instance with the same pattern, but I'm not sure if this is strictly necessary.
NEWS line:
```
* `bind_rows()` cleanly aborts if one of the data frames contains a `POSIXlt` column
(#1789, #1875, @krlmlr).
```
> bind_rows() rejects POSIXlt columns

- inst/include/dplyr/Collecter.h
- inst/include/dplyr/Gatherer.h
- inst/include/dplyr/Order.h
- inst/include/dplyr/OrderVisitorImpl.h
- inst/include/dplyr/Replicator.h
- inst/include/dplyr/Result/GroupedSubset.h
- inst/include/dplyr/Result/RowwiseSubset.h
- inst/include/dplyr/subset_visitor.h
- inst/include/dplyr/visitor.h
- src/nth.cpp
- tests/testthat/test-arrange.r
so that break works inside switch() without surprises
https://github.com/hadley/dplyr/pull/1875#issuecomment-223000740
Working on further cleanup based on this commit. Also looking for a way to generalize the omnipresent switch(): http://stackoverflow.com/q/37576790/946850.
> Call stop() outside of switch() statement

- R/dbi-s3.r
- man/backend_db.Rd
Closes #1910. Summary:
* Have clarified which methods are thin wrappers for DBI methods; which ones build and execute their own SQL code (and summarised what this SQL code); and which do not have methods.
* Corrected return value doc. Though what I have put could be refined somewhat.
* Fixed references to sql_* functions to db_* where appropriate 
* I have not documented details of db_create_indexes because this is not exported. See #1911
> Expanded and corrected backend DB doc

- R/sql-generic.R
- tests/testthat/test-sql-render.R
> Allow fractional number of rows for head() for SQL sources

- R/data-temp.r
and prints a message if source is unavailable. Helpers now seem to be executed by devtools::load_all(), too -- this adds a little safety.
> test_register_src() always succeeds

- R/sql-generic.R
- tests/testthat/test-sql-render.R
to support limits > 2³¹ and to ensure that no decimal point is added to the SQL.
Follow-up to #1929.
See https://github.com/hannesmuehleisen/MonetDBLite/issues/56#issuecomment-227065094.
> Hand-format limit when rendering SQL

- NEWS.md
- R/sql-build.R
- tests/testthat/test-distinct.R
- tests/testthat/test-sql-render.R
Without columns:
- `.keep_all` is ignored if no columns are selected
With columns:
- `.keep_all = FALSE` is implemented using a grouped select
- `.keep_all = TRUE` still raises an error, because DISTINCT syntax seems to vary between SQL dialects
Adapted tests.
Fixes #1937.
> Fix distinct() for SQL sources

- tests/testthat/helper-output.R
- tests/testthat/output/iris--70.txt
- tests/testthat/output/iris-3-5.txt
- tests/testthat/output/iris-5-30.txt
- tests/testthat/output/iris-head-30-80.txt
- tests/testthat/output/mtcars-8-30.txt
- tests/testthat/test-arrange.r
- tests/testthat/test-as-data-frame.R
- tests/testthat/test-filter.r
- tests/testthat/test-output.R
All tests now succeed with *both* CRAN and bleeding-edge tibble, to faciliate dplyr CRAN release.
> tibble > 1.0 compatibility

- NEWS.md
- inst/include/dplyr/MultipleVectorVisitors.h
- inst/include/dplyr/visitor_set/VisitorSetHash.h
- src/dplyr.cpp
- tests/testthat/test-summarise.r
- hash(): return index
- nrows(): stop() instead of segfault
Fixes #1957.
With tests, which pass locally. Travis fails because of tibble update (#1949).
Currently I have no idea how to make the forward of n_distinct() to n() explicit in the code for hybrid evaluation.
> Support zero-column corner case in vector visitors

- src/bind.cpp
- tests/testthat/test-binds.R
> bind_cols() handles empty argument list

- R/case_when.R
- tests/testthat/test-case-when.R
#1999. `case_when` stores results of formula evaluations as vectors in `query`. These values are used to determine which elements in the input vector need to be overwritten. But an NA in an earlier query result would infect TRUE values in other queries. Therefore, I've updated the function to treat NAs as FALSE (when it comes to determining which values need to be replaced).
Also, added a unit test.
> case_when support of NA values

- .Rbuildignore
- README.Rmd
- appveyor.yml
- tests/testthat/test-group-by.r
- tests/testthat/test-mutate.r
to prepare for release.
Also remove NOTE that occurs with RSQLite 1.0.0 (current CRAN version), check now succeeds with both CRAN and bleeding-edge RSQLite.
Closes #1949 (=includes it).
Please visit https://ci.appveyor.com to enable testing.
Passes win-builder tests, too.
> AppVeyor testing

- src/address.cpp
- src/api.cpp
- src/arrange.cpp
- src/between.cpp
- src/bind.cpp
- src/combine_variables.cpp
- src/distinct.cpp
- src/dplyr.cpp
- src/filter.cpp
- src/group_indices.cpp
- src/init.cpp
- src/join.cpp
- src/nth.cpp
- src/select.cpp
- src/strings_addresses.cpp
- src/summarise.cpp
- src/test.cpp
- src/window.cpp
- tests/testthat/helper-astyle.R
- tests/testthat/test-astyle.R
via
```bash
astyle -n --indent=spaces=2 --indent-namespaces --indent-switches *.cpp
sed -i "" 's/[)] *[{]$/){/' *.cpp
git checkout RcppExports.cpp
```
> astyle formatting

- R/translate-sql.r
- man/translate_sql.Rd
- vignettes/databases.Rmd
```
library(RSQLite)
library(nycflights13)
dat <- nycflights13_sqlite() %>% tbl("flights")
dat %>% filter(dest %like% "IA*") %>% tally() # returns 0 rows
dat %>% filter(dest %like% "IA%") %>% group_by(dest) %>% tally() 
```
> SQL like wildcard is % not *

- NEWS.md
- R/funs.R
- tests/testthat/test-colwise.R
So that we can do:
```r
df %>% mutate_all(round, 2)
```
Found a weird R inconsistency while writing this:
```r
c <- call("fun", quote(arg))
names(c)[2] <- "n"
names(c)
#> [1] ""  "n"
l <- list(1, 2)
names(l)[2] <- "n"
names(l)
#> [1] NA  "n"
```
also
```r
names(c) <- c(NA, NA)
names(c)
#> NULL
names(l) <- c(NA, NA)
names(l)
#> [1] NA NA
```
> Allow unnamed additional arguments in colwise verbs

- DESCRIPTION
- NEWS.md
- R/query.r
> use dbFetch() instead of fetch()

- NEWS.md
- inst/include/dplyr/FullDataFrame.h
- inst/include/dplyr/Gatherer.h
- inst/include/dplyr/GroupedDataFrame.h
- inst/include/dplyr/Hybrid.h
- inst/include/dplyr/Result/GroupedCallProxy.h
- inst/include/dplyr/Result/GroupedHybridCall.h
- inst/include/dplyr/Result/Lag.h
- inst/include/dplyr/Result/LazyGroupedSubsets.h
- inst/include/dplyr/Result/LazySubsets.h
- inst/include/dplyr/Result/Lead.h
- inst/include/dplyr/Result/Mutater.h
- inst/include/dplyr/Result/Rank.h
- inst/include/dplyr/RowwiseDataFrame.h
- inst/include/tools/SlicingIndex.h
- src/bind.cpp
- src/distinct.cpp
- src/filter.cpp
- src/group_indices.cpp
- src/hybrid.cpp
- src/join_exports.cpp
- src/summarise.cpp
- src/utils.cpp
- allows removing redundant code
- preparation for hybrid evaluation refactoring
- reduces allocations
- a template solution (instead of virtual functions) may give better performance, can be refactored later
@hadley: PTAL.
> New RowwiseSlicingIndex, NaturalSlicingIndex and OffsetSlicingIndex

- tests/testthat/test-group-by.r
- tests/testthat/test-mutate.r
This PR adds the failing test associated with https://github.com/hadley/dplyr/issues/1892 (`group_by coerces integer + double -> double (#1892)`) and another (apparently related) failing test (`group_by coerces factor + character -> character (WARN)`).  Please confirm that the second failing test is indeed an issue and not a misunderstanding on my part before merging.
> Add Failing Test for #1892 and a Related Failing Test

- tests/testthat/test-summarise.r
Two tests added for #2200 :
- One where an ordered factor is created inside `summarize` (order gets dropped)
- One where `min` and `max` are calculated on an already existing ordered factor column (order gets dropped)
> Add failing tests for summarize preserving ordered factors (#2200)

- R/translate-sql-base.r
This resolves an issue in stricter SQL engines where `double` values are not accepted.
> enforce integer 'n' for lag()

- DESCRIPTION
- NEWS.md
- R/hybrid.R
- R/nth-value.R
- R/rank.R
- inst/include/dplyr/HybridHandlerMap.h
- src/hybrid.cpp
- src/hybrid_debug.cpp
- tests/testthat/helper-hybrid.R
- tests/testthat/test-hybrid.R
Extracted from #2298, will implement argument matching and constant folding after this is merged. @hadley: PTAL.
Fixes #1691.
> Hybrid tests

- inst/include/dplyr/Gatherer.h
- inst/include/dplyr/Result/GroupedCallProxy.h
- inst/include/dplyr/Result/GroupedHybridCall.h
- src/hybrid.cpp
- src/mutate.cpp
- src/summarise.cpp
- tests/testthat/test-mutate.r
- Split in three classes
- Introduce VariableResult, a hybrid handler that returns a data frame variable
- Simplify mutate_grouped()
Performance doesn't seem to be affected. @hadley: PTAL. CC @lionel-.
> Refactor GroupedHybridCall

- R/sql-build.R
- R/sql-generic.R
- tests/testthat/test-sql-build.R
- tests/testthat/test-sql-joins.R
@hadley Spark and SQL Server have issues with the `USING` statement and natural joins respectively. This change removes the use of `USING` by making joins explicit at all times. Feedback welcomed. Example follows:
```
library(dplyr)
src <- src_sqlite(tempfile(), create = TRUE)
data_frame(a = 1:3, b = letters[1:3]) %>% copy_to(src, ., "df1")
data_frame(b = letters[1:3], c = letters[24:26]) %>% copy_to(src, ., "df2")
```
Without this PR: `left_join(tbl(src, "df1"), tbl(src, "df2"))`:
```
<SQL> SELECT * FROM 'df1'
LEFT JOIN
'df2'
USING ('b')
```
with this PR: `left_join(tbl(src, "df1"), tbl(src, "df2"))`:
```
SELECT 'a', 'c', 'b.x' AS 'b'
FROM (
SELECT * FROM 
(SELECT 'a' AS 'a', 'b' AS 'b.x' FROM 'df1')
LEFT JOIN
(SELECT 'b' AS 'b.y', 'c' AS 'c' FROM 'df2')
ON ('b.x' = 'b.y')
)
```
> make inner joins explicit to avoid using

- R/compute-collect.r
This documentation seems to be out of date since collapse in `R/tbl-sql.r` has grouping  https://github.com/hadley/dplyr/blob/165b7603f17d66e2caf2b837f716c9c1ec977bd4/R/tbl-sql.r#L374. And there is a test to make sure that collapse preserves grouping: https://github.com/hadley/dplyr/blob/master/tests/testthat/test-group-by.r#L25.
> fix documentation about collapse grouping

- vignettes/new-sql-backend.Rmd
This updates documentation `Adding a new SQL backend` (here:  https://github.com/hadley/dplyr/blob/master/vignettes/new-sql-backend.Rmd#copy_to ) to reflect changes made in naming conventions (`Consistent use of db_ vs sql_`) https://github.com/hadley/dplyr/commit/736e6dc4ede6962f9f262a7d9a762dd4c61770b4
> Fix typo in backend vignette to use db_ vs sql_

- src/group_indices.cpp
- src/join_exports.cpp
- tests/testthat/test-group-by.r
- tests/testthat/test-group-indices.R
- tests/testthat/test-joins.r
* Fix subset_join to update group column names in attribute
vars when they are duplicate column names and get renamed.
* Add a test to verify that the group column names after
join are all columns in the data frame.
* Fix build_index_cpp to report correct missing group
column name. Currently when a group column name does not
exist in the data frame, it reports a name from the names 
vector (all columns) instead of the vars vector (group columns).
Fixes #2330.
> Fix groups when joining grouped data frames with duplicates (#2330)

- R/RcppExports.R
- R/group-indices.R
- src/RcppExports.cpp
- src/group_indices.cpp
The implementation looks pretty similar to build_index_cpp(), I guess there's not much difference if we compute the index with a regular grouping operation.
The new implementation is a tad slower for `nycflights13::flights %>% group_indices(year, month, day)` (~95 ms vs. ~91 ms), I suspect this is because `group_by()` always computes labels. Do we need to care about that?
@hadley: PTAL.
> Get rid of grouped_indices_impl()

- NEWS.md
- inst/include/dplyr/DataFrameSubsetVisitors.h
- src/select.cpp
- tests/testthat/helper-encoding.R
- tests/testthat/test-group-by.r
Fixes #2284. Similar to #2058 but at a lower level.
Fixes #2005 and #2277.
> Fix group_by() for column names in UTF-8 on Windows

- DESCRIPTION
Since `functionmap2` was renamed to `pkgapi` https://github.com/r-pkgs/pkgapi/commit/b8342cc58a241dbb5ed6f2ccc779a7cb9dd97c18
> Change references to functionmap2 to pkgapi

- tests/testthat/test-nth-value.R
Summarise nth and order_by crashes R in both Windows and Ubuntu.
This commit triggers that crash, with code pulled from @avsmith's issue.
Apparently this issue does not affect Macs.
> Add test for crash in issue #2166.

- R/top-n.R
- src/hybrid_window.cpp
- tests/testthat/helper-hybrid.R
- tests/testthat/test-hybrid.R
- tests/testthat/test-top-n.R
also check arguments in top_n().
Fixes #2279.
@hadley: PTAL.
> Fix segfault when using min_rank("string") in hybrid evaluation

- inst/include/dplyr/Collecter.h
- tests/testthat/test-binds.R
Not checking other verbs yet.
Fixes #2015.
@hadley: PTAL.
> Explicitly reject data frame columns in bind_rows()

- src/join_exports.cpp
- tests/testthat/test-joins.r
Avoids endless loop.
Fixes #2228.
@hadley: PTAL.
> Allow one join suffix to be the empty string

- inst/include/dplyr/Result/GroupedHybridCall.h
- tests/testthat/helper-hybrid.R
- tests/testthat/test-hybrid.R
to avoid leaking of broken bindings via environments of function objects or formulas.
Closes #2358.
@hadley: PTAL.
> Cleanup active environment

- R/translate-sql-base.r
In commit 421b569 the function `win_over()` was added. Today, I used `lag()` with `src_postgres()` on the master and I got the following error:
Error in lag(value, order = "date") : could not find function "over"
When I looked in translate-base-sql.R, it looks like you changed all of the other base_win functions to use `win_over()` but you might have just missed `lag()`.
> fix translate sql

- tests/testthat/helper-encoding.R
- tests/testthat/test-group-by.r
- tests/testthat/test-joins.r
- run in latin1 locale on Linux/OS X for now
- infrastructure to run test with one "complicated" string
> Refactor language tests

- R/recode.R
Make the description of the `...` argument in `recode` more clear.
Currently the documentation does not state whether the names or values of the arguments are the replacement, leaving the reader to infer it from the examples.
This is particularly confusing since `forcats::fct_recode` uses the opposite convention (names are replacements, values are the values to be replaced).
> minor documentation edit

- DESCRIPTION
- inst/include/dplyr/Collecter.h
- tests/testthat/helper-combine.R
- tests/testthat/test-combine.R
This commit closes #2406.
- If we `collect` objects of unknown classes there is risk of losing attributes, so we raise a warning unless we know it is safe.
- `bit64::integer64` is now supported by `dplyr::combine` and `dplyr::bind_rows` (partially deals with https://github.com/hadley/dplyr/issues/1092)
- Tests updated to reflect current status
> Combine strips unknown classes. Support integer64.

- NEWS.md
- inst/include/dplyr/Collecter.h
- tests/testthat/helper-combine.R
When we collect a factor into a character vector we should warn as well of the coercion of the factor to a character for consistency. This PR adds the warning and fixes the test case.
Closes #2317
> Combine character and factor show warning. Closes #2317

- DESCRIPTION
- NEWS.md
- inst/include/dplyr/Collecter.h
- inst/include/dplyr/Gatherer.h
- tests/testthat/test-binds.R
- tests/testthat/test-combine.R
- tests/testthat/test-mutate.r
This PR is a continuation to #2486 and closes #1892.
`mutate(col2 = fun(col1))` on a grouped data frame calls `fun` once per group.
It used to require that `fun` returns the exact same type on each call. That is not desirable in functions that may return different (but compatible) types, such as integer and numeric.
This PR changes that behavior, so the returned vectors from each of the `fun` calls are combined using the same coercion rules than `combine` and `bind_rows`, defined in `Collecter.h`.
Comments are welcome. Feel free to be picky, so I can improve a bit my C++ and Rcpp skills. :smiley:
> Make mutate use collecter h

- inst/include/dplyr/Result/VectorSliceVisitor.h
- src/hybrid_nth.cpp
- tests/testthat/test-hybrid.R
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise.r
- avoid segfault when using `order_by`
- support complex
- fall back to standard if `n` is a `LANGSXP`
Fixes #1980.
> Fix hybrid handler for first(), last(), and nth()

- src/hybrid_offset.cpp
- tests/testthat/test-hybrid.R
- Better argument matching
- Fall back to standard evaluation if `n` is a `LANGSXP`
Fixes #946.
> Clean up hybrid handler for lead() and lag()

- inst/include/dplyr/Result/Lag.h
Also gets rid of hidden `i` variable.
> Simplify computation of hybrid lag

- R/translate-sql.r
- man/translate_sql.Rd
I believe these were in error or from older versions, and the documentation should read `translate_sql()` not `sql_translate()`.
> Change 'sql_translate' to 'translate_sql' in doc

- R/translate-sql-window.r
Queries with ORDER BY in OVER() failed with a SQL backend that uses non-standard identifier quoting because double quotes were inserted around identifiers.
> Add missing con = win_current_con()

- inst/include/dplyr/NamedListAccumulator.h
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise.r
in ungrouped `mutate()` and `summarise()`.
Fixes #1689.
> Always strip names from result

- .travis.yml
- inst/include/dplyr/Result/DelayedProcessor.h
- tests/testthat/test-summarise.r
to copy all attributes.
Fixes #2231.
> Duplicate summary values of type list

- NEWS.md
- inst/include/dplyr/JoinVisitorImpl.h
Under the following conditions, a false match during a join could have occurred theoretically:
- Joining an integer and a numeric column
- Two numeric values have the same integer component but different fractional components, **and** hash to the same value
It is unlikely that this has been ever observed, but it might be possible to construct an artificial example.
> Fix very rare case of false match during join

- NEWS.md
- inst/include/dplyr/Gatherer.h
- tests/testthat/test-mutate.r
> mutate() recycles list columns of length 1

- R/sql-generic.R
- R/sql-render.R
This would fix #2526 by removing the leading underscore from tables in joins. Change made essentially via a Perl `s/_(LEFT|RIGHT)/TBL_$1/g;`. I have tested this with my `db2` package and it fixes my problems.
> Remove leading underscores from join tables

- R/db-postgres.r
- R/translate-sql-base.r
- tests/testthat/test-sql-translation.r
This gets around the issue that postgres doesn't support two-argument
`log(base, x)` for floating point `x`.
- For default SQL: if log base is *e*, use `ln()`.
- For postgres: if log base is *e*, use `ln()`.
- For postgres: if log base isn't *e*, use `log(x) / log(base)`.
- Add tests.
> Add translation for log in postgres (#2464)

- R/manip.r
You can't pass a `list()` to `select()`/`rename()`. 
But, the documentation suggests you can. I rephrased the documentation to make it clear a `list()` won't work.
The documentation for the `...` parameter in `select()`/`rename()` parameters begins: 
```r
#' @param ... One or more unquoted expressions separated by commas.
```
But that docstring is incorrect: you can't use R's formal `list()` to pass in multiple unquoted expressions. As evidence, the following are some examples of statements that fail when trying to use `list()`
```r
rename(iris, list(petal_length = Petal.Length))
rename(iris, list(Petal.Length = petal_length))
select(iris, list(Petal.Length))
select(iris, list(Petal.Length, Petal.Width))
```
> Fix documentation for the `...` parameter in rename/select

- inst/include/dplyr/DataFrameColumnSubsetVisitor.h
- inst/include/dplyr/DataFrameSubsetVisitors.h
- inst/include/dplyr/MatrixColumnSubsetVectorVisitor.h
- inst/include/dplyr/SubsetVectorVisitor.h
- inst/include/dplyr/SubsetVectorVisitorImpl.h
- inst/include/dplyr/VectorVisitorImpl.h
- remove unused LogicalVector methods
- use partial specialization instead of traits
- use preallocated integer vector instead of counting
- this trades memory for speed; a more conservative solution could be used to estimate the final size of the vector (similarly to readr) and to reserve accordingly
> Cleanup around subset()

- NEWS.md
- inst/include/dplyr/DataFrameSubsetVisitors.h
- inst/include/dplyr/EmptySubset.h
- tests/testthat/test-slice.r
Fixes #2490.
Builds on top of #2558.
> Fix slice() for zero-column data frames

- DESCRIPTION
- R/grouped-df.r
- R/rowwise.r
- R/tbl-sql.r
- R/translate-sql.r
- inst/include/dplyr/Result/GroupedHybridCall.h
I go from 6s to 1.4s with the `mutate.dplyr_df` test case. This could still be divided by 2 by using `Rf_eval()` instead of `Rcpp_eval()` once we get proper stack unwinding.
> Fix performance gap with tidyeval

- codecov.yml
So a red mark means that the build is broken rather than the coverage has dropped.
> Make codecov quiet

- NEWS.md
- R/colwise.R
- R/manip.r
- tests/testthat/test-colwise.R
Includes #2569, fixes #2129 
- Lazy tables are first collected (100 first rows)
- S3 vectors are supported if they implement `tbl_vars()`, `length()` and `[[`.
> Fix colwise genericity

- tests/testthat/test-do.R
- tests/testthat/test-hybrid-traverse.R
- tests/testthat/test-hybrid.R
- tests/testthat/test-if-else.R
- tests/testthat/test-nth-value.R
- tests/testthat/test-window.R
Now only two remaining. We could also move them to the corresponding GitHub issues.
> Get rid of skip() calls in tests

- R/count-tally.R
- R/tbl-df.r
- tests/testthat/test-underscore.R
These tests all pass with v0.5.0. Overall, the underscored versions seem to work pretty well, I'm getting only two kinds of failures.
Closes #2592.
@lionel-: Could you please take a look? Feel free to push to this branch.
> Add tests for underscored version for all verbs

- inst/include/dplyr/Result/GroupedHybridCall.h
- tests/testthat/test-overscope.R
I think strict matching for .env needs to be fixed in rlang, CC @lionel-.
Fixes #2591.
> Strict matching for .data

- src/hybrid.cpp
- tests/testthat/test-summarise.r
So this works: `summarise(group_by(mtcars, cyl), x = 1, z = x)`
Closes #2632
> Fix hybrid handling of summarised symbols

- inst/include/dplyr/main.h
- inst/include/dplyr/workarounds/xlen.h
- src/bind.cpp
- need to wrap `R_xlen_t` for building error messages
@hadley: The code seems to use `int`, `size_t` and `R_xlen_t` pretty much interchangeably, and calls `Rf_length()` instead of `Rf_xlength()`. This will cause trouble for vectors or data frames with > 2G rows. How important is this? (The GCC switch `-Wconversion` detects these mistakes.)
Closes #2638.
> Fix compilation on Windows

- vignettes/dplyr.Rmd
The vignette "Introduction to dplyr" refers to some deleted/moved vignettes yet. Do you have some other plan to rewrite this vignette?
> Remove references to obsolete vignettes in "Introduction to dplyr"

- inst/include/dplyr/NamedListAccumulator.h
after removing names.
This is just a hotfix, I'll work separately on getting names right.
Fixes #2680.
> Protect duplicated data

- inst/include/dplyr/NamedListAccumulator.h
- src/mutate.cpp
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise.r
Includes a refactoring, the second commit contains the essential change.
Fixes #2675.
Closes #2679.
Do we support unnesting grouped data frames in tidyr?
> Remove names only for grouped summarise() and mutate()

- R/dataframe.R
- R/grouped-df.r
- tests/testthat/test-select.r
Fixes #2692 
It is probably too late to rename `vars` to `.vars`, even if it is first argument.
@topepo did you copy `select_vars()` implementation for recipes? If so it's better to prefix arguments of functions taking data via dots with `.` to avoid this issue. Any variable named `var` passed to `select_vars()` will partial match on `vars` :/
> Avoid partial matching on select_vars() arguments

- src/bind.cpp
- tests/testthat/helper-combine.R
- tests/testthat/test-binds.R
~~The 2nd commit holds an unrelated fix I needed to pass tests. I can remove if that is somehow peculiar to me.~~ *removed* Also added `rlang::` while poking around this test. Some rlang calls are namespaced in the tests while others are not, so not sure how it should be.
> Fix off-by-one error in bind_rows() error msg

- R/top-n.R
- tests/testthat/test-tbl.R
- tests/testthat/test-top-n.R
Closes #2705
The new tidyeval implementation of `filter()` has fixed https://github.com/tidyverse/dplyr/issues/2279. However it makes sense to check that `wt` evaluate to a vector as long as the number of rows.
@hadley I'm not sure what's the generic way of retrieving the number of rows. Should `tbl_rows_n()` (added in this PR) be exported at some point?
> Allow top_n() argument `wt` to be a call

- R/error.R
- inst/include/dplyr/bad.h
instead of throwing from R, to avoid formatting of error messages by recent versions of Rcpp.
Fixes #2702.
> Throw exceptions from C++

- inst/include/dplyr/Result/GroupedCallProxy.h
- inst/include/dplyr/Result/ILazySubsets.h
- inst/include/dplyr/Result/LazyGroupedSubsets.h
- inst/include/dplyr/Result/LazySubsets.h
- src/hybrid.cpp
- src/hybrid_in.cpp
- src/hybrid_minmax.cpp
- src/hybrid_nth.cpp
- src/hybrid_offset.cpp
- src/hybrid_simple.cpp
- src/hybrid_window.cpp
- tests/testthat/test-hybrid.R
for handlers that don't support them.
Many handlers actually do have special handling for summary variables, but I think this unnecessarily complicates the code. This PR falls back to R if a summary variable is detected, it remains to be seen when the reuse of a summary variable requires the performance benefits of hybrid evaluation.
Closes #2721.
Fixes #2673. Related to #2312.
Review might be easier if you look at individual commits.
> Turn off hybrid evaluaton of summary variables

- R/compat-dbplyr.R
I believe the expression for `dplyr_call` should use `dplyr_sym` not `dbplyr_sym`.
> Fix typo in wrap_dbplyr_obj

- R/utils.r
- inst/include/dplyr/JoinVisitorImpl.h
- src/join.cpp
- tests/testthat/test-joins.r
The main purpose of this PR is to switch from an error to a warning when the attributes don't match.  I also used this as an opportunity to pull down the join variable names so that we can start to make better warnings and errors.
> Join warnings

- DESCRIPTION
- R/dataframe.R
- R/group-by.r
- R/grouped-df.r
- R/manip.r
- R/tbl-cube.r
- R/tbl-df.r
- R/utils-expr.R
- tests/testthat/test-group-by.r
- tests/testthat/test-mutate.r
Requires https://github.com/hadley/rlang/pull/109 (Travis will fail due to rlang version mismatch).
That currently only deals with pronouns at the top of the call tree.
> Tidy naming for pronouns

- NEWS.md
- inst/include/dplyr/Column.h
- inst/include/dplyr/JoinVisitor.h
- inst/include/dplyr/JoinVisitorImpl.h
- src/api.cpp
- src/join.cpp
- src/join_exports.cpp
- src/set.cpp
- tests/testthat/test-joins.r
- New `Column` class
- Remove duplicate warnings
- Warn about inconsistencies in semi- and anti-joins
- Reverse order of column names in warnings for left join
Closes #2733. Fixes #2739.
> Fix join warnings

- R/RcppExports.R
- inst/include/dplyr/workarounds/xlen.h
- inst/include/tools/match.h
- src/RcppExports.cpp
- src/init_register.c
- src/test.cpp
- tests/testthat/test-internals.r
because `R_xlen_t` is typedef'd to `int`, and our wrapper then takes precedence for *all* `int` values.
Fixes #2736.
> Wrap ptrdiff_t instead of R_xlen_t

- NEWS.md
- R/dataframe.R
- R/grouped-df.r
- R/rowwise.r
- tests/testthat/test-group-by.r
Fixes tidyverse/tibble#256.
Ideally, `classes_grouped()` and `classes_not_grouped()` should be exported functions and called throughout, maybe later.
> tbl_df always inherits from tbl

- R/join.r
- tests/testthat/test-joins.r
We need to be careful, the correct substitute for `message()` seems to be `inform(paste0(..., collapse = ""))`.
> Fix common_by() message for many columns

- R/rowwise.r
- man/rowwise.Rd
Is this a bug in roxygen2?
This document
```r
#' use `[[1]]`. This makes `summarise()` on a rowwise tbl 
#' effectively equivalent to [plyr::ldply()].
```
was converted to this. Weird.
```rd
use \code{[[1]]}. This makes \code{summarise()} on a rowwise tbl
effectively equivalent to [plyr::ldply()].
[[1]: R:[1
[plyr::ldply()]: R:plyr::ldply()
}
```
> Fix rowwise.Rd

- vignettes/programming.Rmd
- Remove obsolete comment about error message
- `rlang::eval_tidy` doesn't work with base R's formulas (I think this is intentional). Before changing from `~` to `quo`, the output looked like: 
>When we evaluate those formulas using rlang::eval_tidy(), we see that they yield different values:
```
library(rlang)
eval_tidy(x1)
#> ~x
#> <environment: 0x0000000007a12958>
eval_tidy(x2)
#> ~x
#> <environment: 0x000000000c5e48e8>
```
> Fix a few out of date things in programming.rmd

- NEWS.md
- R/top-n.R
Closes #2848
@javierluraschi sparklyr now creates this request with your reprex:
```
Selecting by  X
<SQL> SELECT `X`
FROM (SELECT `X`, rank() OVER (ORDER BY `X` DESC) AS `zzz2`
FROM `test_data`) `kmanvoxmpk`
WHERE (`zzz2` <= 10.0)
```
> Implement top_n() lazily

- NEWS.md
- inst/include/dplyr/Result/LazySubsets.h
- src/summarise.cpp
- tests/testthat/test-mutate.r
Regression introduced in 0.7.0, probably in #2453.
Fixes #2842, fixes #2856.
> Ungrouped mutate() doesn't mark new or overwritten variables as summaries

- inst/include/dplyr/bad.h
I have no idea why I used `wrap()` originally, but this results in a naked `SEXP` which may be destroyed even before the function is called. Tests with gctorture are still running.
> Fix protection error when constructing error messages

- R/src_dbi.R
because DBI specs ask for a warning if a client forgets to disconnect.
I'm aware that RSQLite connections are cheap compared to connections to other DBMS, but I prefer a uniform interface definition.
> Auto-disconnect SQLite connection

- R/case_when.R
Likely a typo resulted from copy-pasting code immediately above. The intent seems to be to show an example that works.
> Show case_when()'s splicing support with arguments in order.

- DESCRIPTION
This line in dplyr https://github.com/tidyverse/dplyr/blob/master/inst/include/tools/SymbolString.h#L21 uses `Rcpp::String::String(const char*, cetype_t)`, available in Rcpp since this commit https://github.com/RcppCore/Rcpp/commit/0bf8e97e46ff85d02d7f158c6b476369f7912cc1 that was included in 0.12.7.
That's why dplyr needs to depend on Rcpp 0.12.7 instead of 0.12.6.
Closes #2902
> Depend on Rcpp >= 0.12.7

- .travis.yml
that set additional warning flags. The build is aborted in case of warnings.
This requires RcppCore/Rcpp#671 or a workaround.
> Create Makevars on Travis

- NEWS.md
- inst/include/dplyr/Collecter.h
- tests/testthat/test-mutate.r
Need `SET_STRING_ELT()` to copy `CHARSXP`.
Fixes #2971.
> Fix protection errors with strings for grouped mutate()

- DESCRIPTION
- R/select-vars.R
- tests/testthat/test-equality.r
- tests/testthat/test-mutate.r
- tests/testthat/test-select.r
and fix `rename()` with a hack.
> Fix UTF-8 column name test for Windows

- README.Rmd
The README contains a duplicate "the"
> Remove typo from README.Rmd

- NEWS.md
- src/join_exports.cpp
- tests/testthat/test-joins.r
> Semi- and anti-join maintain sort order of first argument

- NEWS.md
- src/hybrid_nth.cpp
- tests/testthat/test-hybrid.R
> Fall back to standard evaluation with non-const default argument

- NEWS.md
- R/case_when.R
- R/utils-replace-with.R
- tests/testthat/test-case-when.R
Closes #3041.
The second commit is optional, it simplifies error handling but the message is less verbose.
> Support zero-length vectors in case_when()

- NEWS.md
- src/hybrid.cpp
- tests/testthat/test-summarise.r
Fixes #2915 by disabling hybrid evaluation in the problematic (and a few other) cases.
> Turn off hybrid evaluation for non-summary variables

- NEWS.md
- R/distinct.R
- tests/testthat/test-distinct.R
This reverts #2867 and fixes the regressions found in the "epidata", "fold", and "metaplot" packages (and their downstream dependency "nonmemica").
I've set up a reminder to revert this change later.
> Revert unintended API change

- NEWS.md
- src/slice.cpp
- tests/testthat/test-slice.r
if the range stretches over the number-of-rows boundary.
Fixes downstream problems with waccR.
> Fix slice() for negative indices

- NEWS.md
- R/order-by.R
- tests/testthat/test-window.R
Part of #3065. This patch fixes the crash.
> Proper type check for enquoted `call` argument in order_by()

- NEWS.md
- src/bind.cpp
- tests/testthat/test-binds.R
Fixes #3024.
Related: https://github.com/billdenney/pknca/issues/48#issuecomment-326768053
> Better checking of list arguments to bind_rows()

- .travis.yml
- DESCRIPTION
- NEWS.md
- README.Rmd
- README.md
- cran-comments.md
- inst/include/dplyr/Result/Rank.h
- inst/include/dplyr/Result/VectorSliceVisitor.h
- revdep/README.md
- revdep/checks/libraries.csv
- revdep/cran.md
- revdep/problems.md
- src/hybrid_nth.cpp
- src/join_exports.cpp
because the original fix didn't help.
Fedora: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/dplyr-00check.html
ASAN: https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-ASAN/dplyr/00check.log
UBSAN: https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/dplyr/00check.log
> Fix for recent Fedora and ASAN errors

- README.md
In the README, it says the best place to start is the "data import chapter" when it is actually pointing to the "data transformation chapter" and I believe the transformation chapter is the correct one to reference for dplyr.
> Correct link title in README

- R/join.r
To close #3097.  This tweaks a few parts of what users see in the `?inner_join` and related documentation:
1. Current documentation says "dplyr supports four join types" but then lists six joins.  This breaks them into two categories of 4 and 2, consistent with the examples where they are grouped into Mutating & Filtering.
2. Reorders them to match the examples
3. Current language says that mutating joins add variables to the LHS; rewrote this sentence to be true for `right_join` as well.
4. To close #3097, tells users to visit `join.tbl_df` to see additional arguments to the `_join` functions.
(I realize that to be a complete PR, this file needs to be turned into an .Rd file with `document()`, but I'm having problems doing so with this package & Windows so am hopeful someone else can run …
> add consistency to join documentation

- NEWS.md
- R/distinct.R
- tests/testthat/test-distinct.R
Fixes #3088. Went with a warning so as not to introduce a breaking change, should probably be an error in next version that allows breaking changes (0.9 I'm assuming).
I added a new NEWS section as well as I assume 0.7.3 is already released.
> Add warning if any of the selected columns for `distinct()` are of type `list`

- R/case_when.R
- man/case_when.Rd
closes #3202 
I added some examples in the documentation to show how consistent RHS works when using `NA` value. 
I think just adding example is enough but I can add precisions in documentation text also. 
Question : Can we add a sample of code that throws an error in a doc example ? 
something like
```r
x <- 1:50
case_when(
x %% 35 == 0 ~ 35,
x %% 5 == 0 ~ 5,
x %% 7 == 0 ~ 7,
TRUE ~ NA
)
```
I did not generate `Rd` file as you may prefer to do it on your side. Tell me if I had to.
> add example in case_when about consistent RHS

- NEWS.md
- R/grouped-df.r
Improves `df %>% group_by(...) %>% sample_*(...)` performance by 10-100x for dataset with large number of groups.
The motivation is that when performing stratified sampling using `group_by %>% sample_n` on 100k+ strata, it can take minutes or longer. A toy example shows every 1k groups increases runtime by ~2s. A quick profiling shows most of time is spent in `eval_tidy(weight, ...)` for each group. This PR performs the weight calculation using `mutate` instead to preserve the semantics but eliminates the repeated overscope lookup across groups.
``` r
library(dplyr)
#>
#>
#>
n_strata …
```
> More Efficient `group_by(...) %>% sample_*(...)`

- .Rbuildignore
- CONDUCT.md
- README.Rmd
- README.md
Adds contributor code of conduct from `usethis::use_code_of_conduct()`
> Add contributor code of conduct

- R/colwise-mutate.R
The units in the `iris` data are cm. Dividing by 2.54 converts cm to inch, so it's more appropriate to label the new columns with a _in suffix.
> Correct implicit units.

- src/utils.cpp
Just checked, `MARK_NOT_MUTABLE` has been around for at least four years now.
Fixes #3258.
> Use MARK_NOT_MUTABLE() instead of SET_NAMED()

- NEWS.md
- R/RcppExports.R
- R/tbl-df.r
- inst/include/dplyr/GroupedDataFrame.h
- inst/include/dplyr/bad.h
- inst/include/tools/utils.h
- src/RcppExports.cpp
- src/filter.cpp
- src/join_exports.cpp
- src/utils.cpp
- tests/testthat/test-joins.r
- tic.R
- semi- and anti-joins give a warning if RHS has dupes
Fixes #3243.
I have no idea why the build fails when `~/.R/Makevars` is created on Travis.
> Joins give better error message with duplicate column names

- vignettes/internals/hybrid-evaluation.Rmd
Receive this error if `depends()` doesn't include `plogr`
```C++
> Rcpp::sourceCpp('test1.cpp')
In file included from test1.cpp:1:
In file included from /Users/jakobelben/Library/R/3.4/library/dplyr/include/dplyr.h:4:
/Users/jakobelben/Library/R/3.4/library/dplyr/include/dplyr/main.h:11:10: fatal error: 'plogr.h' file not found
#include <plogr.h>
^~~~~~~~~
1 error generated.
make: *** [test1.o] Error 1
/usr/local/clang4/bin/clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I"/Users/jakobelben/Library/R/3.4/library/Rcpp/include" -I"/Users/jakobelben/Library/R/3.4/library/BH/include" -I"/Users/jakobelben/Library/R/3.4/library/dplyr/include" -I"/Users/jakobelben/Desktop/c++" -I/usr/local/include   -fPIC  -Wall -g -O2  -c test1.cpp -o test1.o
Error in …
```
> Add Rcpp dependencies

- R/manip.r
- src/slice.cpp
Related to discussion on Issue 3309. I have added some documentation on using negative indices, and also updated the slice() error message that is triggered if a mix of positive and negative indices are used.
https://github.com/tidyverse/dplyr/issues/3309
> Documentation and errors for slice() with negative indices

- NEWS.md
- inst/include/dplyr/Result/Mean.h
- inst/include/dplyr/Result/Sum.h
- inst/include/dplyr/Result/Var.h
- src/summarise.cpp
- tests/testthat/test-hybrid.R
- tests/testthat/test-summarise.r
> summarise() works for empty data frames

- vignettes/dplyr.Rmd
“Syntactic uniformity” is a singular noun, so the verb hide should be changed to hides.
> Grammar tweak

- NEWS.md
- R/zzz.r
When loading and attaching plyr after dplyr, certain functions in dplyr are masked by some in plyr, which can create problems (hence the "You have loaded plyr after dplyr..." message). But when you detach and unload both packages and then load and attach plyr by itself, the message is still printed even though dplyr is not attached nor loaded.
This PR adds an `.onDetach()` hook which replaces the plyr attach hook function with NULL so that the message isn't given when plyr is safely loaded and attached.
I tested this with @lgbarrett4 by rebuilding dplyr with the `.onDetach` function and made sure the loading and attaching of plyr by itself worked without a warning message.
> resets plyr attach hook when detaching dplyr

- R/colwise-select.R
- R/grouped-df.r
- tests/testthat/test-colwise-select.R
Closes #2947.
@hadley currently `rename_all()` does not rename the grouping variables. This is consistent with `mutate_all()` and `summarise_all()` but it seems that in the case of names it'd make sense to operate on the grouping vars as well. What do you think?
> Fix rename_all() on grouped data

- R/zzz.r
This is fairly trivial, and inline with `?.onDetach` expects. 
```
File ‘dplyr/R/zzz.r’:
.onDetach has wrong argument list ‘libname, pkgname’
Package detach functions should have one argument with name starting
with ‘lib’.
Package detach functions should not call ‘library.dynam.unload’.
See section ‘Good practice’ in '?.Last.lib'.
```
> Fix arguments of `.onDetach`.

- src/slice.cpp
- tests/testthat/test-slice.r
- slice handles 0 in positive and negative indices (#3313)
--- 
See #3313 for details, this fixes it but I wonder if instead of skipping the 0 we should make them illegal here, as `slice` should expect either strictly positive (to keep) or strictly negative (to drop). 
```
slice( d, c(0,1) )
```
But there seems to be some tolerance for it in R: 
```
> x <- 1:10
> x[0]
integer(0)
> x[c(0,1)]
[1] 1
```
> slice handles 0 in positive and negative indices. closes #3313

- inst/include/tools/utils.h
- src/bind.cpp
- src/utils.cpp
- tests/testthat/test-binds.R
- bind_cols handles unnamed list. (#3402)
--- 
I made it so that 
```
> bind_cols(list(1, 2))
V1    V2
<dbl> <dbl>
1    1.    2.
> bind_cols(list(1, x=2))
V1     x
<dbl> <dbl>
1    1.    2.
> bind_cols(list(x=1, 2))
x    V1
<dbl> <dbl>
1    1.    2.
```
but if it's better I can make it fail with a better error message.
> bind_cols handles unnamed list. closes #3402

- src/hybrid.cpp
- tests/testthat/test-hybrid.R
- hybrid evaluation simplifies calls prefixed with the dplyr namespace (#3309)
> hybrid evaluation simplifies dplyr::foo to foo. closes #3309

- R/funs.R
- tests/testthat/test-colwise-select.R
Fixes check failures in the keyholder package.
Reprex with 842b1fe4:
``` r
library(dplyr)
library(tidyselect)
interface <- function(.tbl, .funs = list()) {
impl(.tbl, .funs = .funs)
}
impl <- function(.tbl, ...) {
select_all(.tbl, ...)
}
interface(iris, .funs = toupper)
```
> Created on 2018-03-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> Fix lookup of .funs

- inst/include/dplyr/Result/GroupedHybridCall.h
- src/hybrid.cpp
- tests/testthat/helper-hybrid.R
- tests/testthat/test-hybrid.R
by only sharing proxy objects with a weak reference to the data source. Closes #3318.
@romainfrancois: This patch covers pretty much all of the current implementation to access variables in a grouped (and also ungrouped) operation. The patch only changes ownership: Previously we held ownership of objects used to handle the callbacks from R, now we create proxy objects that are owned by an `XPtr` and are aware if the underlying real object is still alive.
@romainfrancois @lionel-: I haven't found a way around using two proxy objects: one, because I need a `shared_ptr<>`, and the second which I actually share that contains the weak reference to the first proxy object. Is there a better way? Also, happy to take feedback on the naming and the comments, and of course the implementation.
> Avoid cleaning the data mask

- inst/include/dplyr/GroupedDataFrame.h
- inst/include/dplyr/registration.h
- inst/include/dplyr_RcppExports.h
- src/RcppExports.cpp
- src/group_by.cpp
- src/group_indices.cpp
- src/init.cpp
to retain existing classes. Closes #3310.
Does the comment make sense?
> Reindexing grouped data frames only update class if not grouped already

- inst/include/dplyr/HybridHandler.h
- inst/include/dplyr/HybridHandlerMap.h
- inst/include/dplyr/registration.h
- src/hybrid.cpp
- src/hybrid_count.cpp
- src/hybrid_debug.cpp
- src/hybrid_in.cpp
- src/hybrid_minmax.cpp
- src/hybrid_nth.cpp
- src/hybrid_offset.cpp
- src/hybrid_simple.cpp
- src/hybrid_window.cpp
- tests/testthat/test-hybrid.R
- hybrid functions can now be masked by regular R functions to turn hybrid evaluation off (#3255). 
--- 
closes #3255 
@lionel- @krlmlr this follows the discussion in #3255. Some of the tests in `test-hybrid.R` had to change because they were based on the previous behavior. 
```
test_that("nth handlers support quosured symbols", {
first <- last <- nth <- bad_hybrid_handler
expect_identical(
pull(summarise(mtcars, first(!!quo(cyl)))),
dplyr::first(mtcars$cyl)
)
expect_identical(
pull(summarise(mtcars, last(!!quo(cyl)))),
dplyr::last(mtcars$cyl)
)
expect_identical(
pull(summarise(mtcars, nth(!!quo(cyl), 2))),
dplyr::nth(mtcars$cyl, 2)
)
})
```
is now: 
```
test_that("nth handlers support quosured symbols", {
expect_identical(
pull(summarise(mtcars, first(!!quo(cyl)))), …
```
> turn off hybrid evaluation by masking the function. #3255

- src/hybrid_window.cpp
- tests/testthat/test-filter.r
- `row_number()` works on empty subsets (#3454)
> row_number is hybridifyed on empty indices set. closes #3454

- R/count-tally.R
- tests/testthat/test-count-tally.r
``` r
db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
dLocal <- data.frame(n = 1:3)
tally(dLocal)
#> Using `n` as weighting variable
#>   nn
#> 1  6
dRemote <- dplyr::copy_to(db, dLocal)
tally(dRemote)
#> Using `n` as weighting variable
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.22.0 [:memory:]
#>      nn
#>   <int>
#> 1     6
```
Created on 2018-04-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> tally works correctly on tbl_sql (#3075)

- NEWS.md
- inst/include/dplyr/Result/LazySubsets.h
- inst/include/tools/SymbolMap.h
This was going through the `SymbolVector::push_back` method. 
```
void push_back(const SymbolString& s) {
v.push_back(s.get_string());
}
```
and `v` is a `CharacterVector` 😱 
This is still expensive e.g. compared to `[`, I'll look for other bottlenecks.
``` r
library(dplyr)
#> 
#> 
#> 
library(purrr)
n_samples <- 500
n_features <- 100000
df <- bind_cols(
tibble(sample_id = paste0("sample_", 1:n_samples)),
1:n_features %>%
map(rnorm, n = n_samples) %>%
map(as_tibble) %>%
bind_cols()
)
system.time(fetched_sample <- filter(df, sample_id == "sample_1"))
#>    user  system elapsed 
#> …
```
> Performance fixes for wide data frames

- NEWS.md
- inst/include/dplyr/Result/Mean.h
- inst/include/dplyr/Result/Sum.h
- src/hybrid_simple.cpp
- tests/testthat/test-summarise.r
Now getting this with the `microbenchmark` from #3189 
```r
> microbenchmark(
+   # summarizing double variable
+   testTibble %>% summarise(s = sum(a)),
+   # summarizing logical variable <- ISSUE IS HERE
+   testTibble %>% summarise(s = sum(b)),
+   # summarizing integer variable
+   testTibble %>% summarise(s = sum(c)),
+   # compare with simple sums without grouping
+   testTibble %>% pull(a) %>% sum(),
+   testTibble %>% pull(b) %>% sum(),
+   testTibble %>% pull(c) %>% sum()
+ )
Unit: microseconds
expr     min        lq      mean   median        uq      max neval
testTibble %>% summarise(s = sum(a)) 887.793  963.7880 1113.9784 1009.477 1113.3875 3213.814   100
testTibble %>% summarise(s = sum(b)) 914.653 1026.2770 1246.6117 1105.180 1254.5270 3613.427   100
testTibble %>% …
```
> faster hybrid sum, mean, var and sd for logical vectors. closes #3189

- src/group_indices.cpp
- tests/testthat/test-empty-groups.R
When reviewing the code I was puzzled why there were calls to `slicer()` in `FactorSlicer::train()` but not in `VectorSlicer::train()`.
> train child slicers in VectorSlicer::train()

- NEWS.md
- R/colwise-filter.R
- R/dataframe.R
- R/manip.r
- R/tbl-df.r
- man/filter.Rd
- man/filter_all.Rd
- man/se-deprecated.Rd
> .preserve argument in `filter` to control group preservation

- src/set.cpp
- tests/testthat/test-sets.R
``` r
library(dplyr)
#> 
#> 
#> 
x <- data_frame(name = c("a", "b"), type = c("integer", "string"))
x %>% group_by(name) %>%
select(name) %>%
setdiff(select(x, name)) %>%
left_join(x, by = "name")
#> # Groups:   name [1]
#> # ... with 2 variables: name <chr>, type <chr>
```
Created on 2018-05-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> reconstruct groups metadata for set operations. closes #3587

- inst/include/dplyr/Result/Rank.h
- src/hybrid_window.cpp
- tests/testthat/test-mutate-windowed.R
```
> df <- tibble(x=1:42)
> mutate( df, nt = ntile(9))
x    nt
<int> <int>
1     1     1
2     2     1
3     3     1
4     4     1
5     5     1
6     6     2
7     7     2
8     8     2
9     9     2
10    10     2
```
on the example from #3418 :
```r
> library(tidyr)
>  mtcars %>%
+   as_tibble() %>% 
+   mutate(ntile = ntile(7)) %>%
+   nest(-ntile)
ntile data             
<int> <list>           
1     1 <tibble [5 × 11]>
2     2 <tibble [5 × 11]>
3     3 <tibble [4 × 11]>
4     4 <tibble [5 × 11]>
5     5 <tibble [4 × 11]>
6     6 <tibble [5 × 11]>
7     7 <tibble [4 × 11]>
```
I have not touched the non hybrid version, so at the moment these are confusing
```
> ntile(4)
Error in ntile(4) : argument "n" is missing, with no default
> ntile(n=4)
Error in ntile(n = 4) : argument "x" is …
```
> ntile with only one argument in dplyr expressions

- R/group_data.R
- R/grouped-df.r
- inst/include/tools/SlicingIndex.h
- man/group_data.Rd
- src/filter.cpp
- src/group_indices.cpp
- tests/testthat/test-arrange.r
- tests/testthat/test-group_data.R
- tests/testthat/test-sets.R
- tests/testthat/test-slice.r
```
> tibble( x = 1:4, g = rep(1:2, each = 2)) %>% group_by(g) %>% group_rows()
[[1]]
[1] 1 2
[[2]]
[1] 3 4
```
> Using 1-based indices in grouping metadata

- src/group_indices.cpp
- tests/testthat/test-group_data.R
```r
> df <- tibble(x = 1:4, g = rep(1:2, each = 2))
>   attr(df, "vars") <- "g"
>   attr(df, "class") <- c("grouped_df", "tbl_df", "tbl", "data.frame")
> group_rows(df)
[[1]]
[1] 1 2
[[2]]
[1] 3 4
```
> GroupedDataFrame are compatible with older style grouped_df. 

- NEWS.md
- inst/include/dplyr/Gatherer.h
- src/mutate.cpp
- tests/testthat/test-mutate.r
```r
> data_frame(a = 1:3, b=4:6) %>% group_by(a) %>%  mutate( b = identity(NULL))
a
<int>
1     1
2     2
3     3
```
When it's not always NULL, it's treated as NA when NA is supported, otherwise as NULL: 
```r
> data_frame(a = 1:3, b=4:6) %>% group_by(a) %>%  mutate( b = if(a==1) NULL else b )
a     b
<int> <int>
1     1    NA
2     2     5
3     3     6
> data_frame(a = 1:3, b=4:6) %>% group_by(a) %>%  mutate( b = if(a==1) NULL else list(b) )
a b        
<int> <list>   
1     1 <NULL>   
2     2 <int [1]>
3     3 <int [1]>
```
> mutate( x = some_expression() -> NULL ) removes column x

- NEWS.md
- R/colwise-mutate.R
- tests/testthat/test-colwise-mutate.R
```r
> iris %>%
+   group_by(Species) %>%
+   summarise_at(-1, mean)
Species    Sepal.Width Petal.Length Petal.Width
<fct>            <dbl>        <dbl>       <dbl>
1 setosa            3.43         1.46       0.246
2 versicolor        2.77         4.26       1.33 
3 virginica         2.97         5.55       2.03 
> 
```
just a bit unfortunate that because of this, the error message is less useful: 
```
> tbl <- data_frame(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>% group_by(gr1)
> summarise_at(tbl, vars(gr1), mean)
Error in .f(.x[[i]], ...) : object 'gr1' not found 
```
Maybe `summarise_at` could tryCatch this `funs <- manip_at(.tbl, .vars, .funs, enquo(.funs), caller_env(), ...)` and act on it.
> `summarise_at()` excludes grouping variables. closes #3613

- NEWS.md
- inst/include/dplyr/Collecter.h
- inst/include/dplyr/GroupedDataFrame.h
- inst/include/dplyr/JoinVisitorImpl.h
- inst/include/dplyr/Result/Lag.h
- inst/include/dplyr/Result/Lead.h
- inst/include/dplyr/Result/Mutater.h
- inst/include/dplyr/Result/Rank.h
- inst/include/dplyr/SubsetVectorVisitorImpl.h
- inst/include/tools/wrap_subset.h
- src/api.cpp
- src/between.cpp
- src/bind.cpp
- src/group_indices.cpp
- src/test.cpp
- src/utils.cpp
- src/window.cpp
https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/dplyr.out
> Fix rchk errors

- R/manip.r
- man/arrange.Rd
- man/filter.Rd
- man/mutate.Rd
- man/select.Rd
- man/slice.Rd
- man/summarise.Rd
In general, if a Description section jumped right into exceptions or special cases without first saying what the function does, I added something briefly describing what the function does.  
The rest of what's here is mostly small clarifications or corrections.
> Make a few doc sections more explicit

- .github/lock.yml
* Stop lockbot from marking issues as resolved. 
* Add message explaining what lockbot does.
* See https://github.com/dessant/lock-threads/issues/7 re. new `setLockReason` param.
> Set lockbot reason 🔒🤖

- vignettes/window-functions.Rmd
I fix a few minor typos.
I also updated the lead()/lag() example. The text talks about using the order_by argument, while the example uses the order_by() helper function with cumsum() (which also appears later in the vignette).
> Update window functions vignette

- R/count-tally.R
Not a typo or grammatical errors, but a suggestion to add to the documentation for add_count/tally.
The current documentation suggests to summarise yourself if you want another variable name than n, but there is an even easier option which is to call dplyr::rename() afterwards.
> count-tally doc - adding rename option

- R/context.R
The variable names are called differently in C++, yet it still works. I guess we don't need to initialize at all.
> Avoid initializing context in R

- inst/include/tools/hash.h
Fixes #3825 
Rcpp doesn't seem to provide a hash function of `Rcomplex`, so we need to define by ourselves for now.
c.f. https://github.com/RcppCore/Rcpp/blob/f3c5a34e06e774532227470b01c63a8f08ce4313/inst/include/Rcpp/sugar/sets.h#L25-L59
> Provide a hash function of Rcomplex for Windows

- R/utils-expr.R
- tests/testthat/test-colwise-mutate.R
Skip using quo_text with bare symbols so that we can borrow `rlang::as_string` magic with encoding.
```r
tidy_text <- function(quo, width = 60L) {
expr <- quo_get_expr(quo)
if (is_data_pronoun(expr)) {
as_string(node_cadr(node_cdr(expr)))
} else if (is_symbol(expr)) {
as_string(expr)
} else {
quo_text(quo, width = width)
}
}
```
The alternative would be that `rlang::expr_text` handle bare symbols:
```r
expr_text <- function(expr, width = 60L, nlines = Inf) {
if (is_symbol(expr)) {
return(as_string(expr))
}
str <- deparse(expr, width.cutoff = width)
if (length(str) > nlines) {
str <- c(str[seq_len(nlines - 1)], "...")
}
paste0(str, collapse = "\n")
}
```
> tidier tidy_text

- NEWS.md
- tests/testthat/test-colwise-mutate.R
This just adds this test which now passes: 
```r
test_that("mutate_all handles utf-8 names (#2967)", {
withr::with_locale( c(LC_CTYPE = "C"), {
res <- tibble(a = 1) %>%
setNames("\u4e2d") %>%
mutate_all(funs(as.character)) %>%
names()
expect_equal(res, "\u4e2d")
})
})
```
> regression test for handling of utf8 characters in mutate_all

- inst/include/dplyr/Collecter.h
- inst/include/dplyr/data/DataMask.h
- inst/include/dplyr/hybrid/Expression.h
- inst/include/dplyr/hybrid/hybrid.h
- inst/include/dplyr/hybrid/scalar_result/n_distinct.h
- inst/include/dplyr/symbols.h
- inst/include/tools/is_lubridate_unsupported.h
- src/arrange.cpp
- src/group_indices.cpp
- src/init.cpp
- src/join.cpp
- src/utils.cpp
So that symbols that are statically used, e.g. `Rf_install("n")` are initialized only once, and we get top them by `symbols().n`
I tried to rather have the syntax `symbols::n` but could not get it to work.
> Centralize static Rf_install calls.

- R/RcppExports.R
- src/RcppExports.cpp
- src/address.cpp
- tests/testthat/test-summarise.r
This was needed when we used the Shinkrable vectors thing. We no longer do, and this is causing issues on #3853. closes #3853.
> - old debugging function `gp`

- inst/include/tools/SlicingIndex.h
Although part of the work on the hybrid refactor got rid of the need of the base class `SlicingIndex` because the index class is directly used as a template parameter. But there are still some places taking a `const SlicingIndex&` (Collecter and bind).
> + virtual destructor to SlicingIndex

- DESCRIPTION
- inst/include/dplyr/visitors/subset/column_subset.h
- src/summarise.cpp
This does not work: 
```cpp
Rcpp::Matrix<RTYPE> res(no_init(n, nc));
```
and gives: 
```cpp
In file included from arrange.cpp:1:
In file included from ./pch.h:1:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp.h:40:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp/Vector.h:58:
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp/vector/Matrix.h:93:18: error: call to non-static member function without an object argument
Storage::set__( Rf_allocMatrix( RTYPE, obj.nrow(), obj.ncol() ) );
~~~~~~~~~^~~~~
../inst/include/dplyr/visitors/subset/column_subset.h:71:23: note: in instantiation of member function 'Rcpp::Matrix<13, PreserveStorage>::Matrix' requested …
```
> use of no_init

- R/funs.R
So that we get this: 
```r
> funs(function(si) { mp[si] })
Error: `function(si) {
mp[si]
}` must be a function name (quoted or unquoted) or an unquoted call, not `function`
Call `rlang::last_error()` to see a backtrace 
```
instead of: 
```r
> funs(function(si) { mp[si] })
Error: `function(si) {
mp[si]
}` must be a function name (quoted or unquoted) or an unquoted call, not ``function``
Call `rlang::last_error()` to see a backtrace 
```
> Fix as_fun with `function` and `~` case.

- inst/include/dplyr/data/GroupedDataFrame.h
- inst/include/dplyr/data/RowwiseDataFrame.h
- inst/include/tools/SlicingIndex.h
- inst/include/tools/VectorView.h
- src/filter.cpp
`GroupedSlicingIndex` does not need to protect its `data`, it is already protected. 
`GroupedFilterIndices` does not need to hold a `std::vector<slicing_index>`
> Revise filter internals to use less Rcpp protection

- R/group-by.r
- tests/testthat/test-group-by.r
closes #3780 
```r
> group_by(mtcars, cyl, !!quo())
mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
* <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
10 …
```
> ignore empty quosures in group_by

- R/manip.r
- man/filter.Rd
- man/mutate.Rd
- man/summarise.Rd
Closes #3904 
`?mutate` and `?summarise` mentioned `!!` but the examples were not very useful. Now mentions how to use strings with `.data` and how to bypass the mask with `!!`.
> Document `.data` and `!!` in manip verbs

- src/filter.cpp
- tests/testthat/test-slice.r
```r
> mtcars %>%
+     group_by(cyl) %>%
+     filter(cyl==6) %>%
+     slice(1:2)
mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
<dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1    21     6   160   110   3.9  2.62  16.5     0     1     4     4
2    21     6   160   110   3.9  2.88  17.0     0     1     4     4
> mtcars %>%
+     group_by(cyl) %>%
+     filter(cyl==6) %>%
+     sample_n(size = 3)
mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
<dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
2  19.7     6  145    175  3.62  2.77  15.5     0     1     5     6
3  21       6  160    110  3.9   2.62  16.5     0     1     4     4
```
> slice does nothing on empty groups. 

- src/bind.cpp
- tests/testthat/test-binds.R
``` r
library(dplyr)
df <- data.frame(x = 1, y = 2)
lst <- structure(list(df, df, df), class = "special_lst")
bind_rows(lst)
#>   x y
#> 1 1 2
#> 2 1 2
#> 3 1 2
```
Created on 2018-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)
> flatten_bindable() allows typed lists

- R/RcppExports.R
- R/dataframe.R
- R/grouped-df.r
- R/manip.r
- R/tbl-df.r
- inst/include/dplyr/data/DataMask.h
- inst/include/dplyr/symbols.h
- inst/include/dplyr/visitors/subset/DataFrameSubsetVisitors.h
- inst/include/dplyr/visitors/subset/column_subset.h
- src/RcppExports.cpp
- src/arrange.cpp
- src/distinct.cpp
- src/filter.cpp
- src/hybrid.cpp
- src/init.cpp
- src/join_exports.cpp
- tests/testthat/test-summarise.r
so that we get the same results as if `[` was called locally in the function, e.g. 
```r
test_that("column_subset respects S3 local [. method (#3923)", {
testS3Class <- function(x, X){
structure(x, class = "testS3Class", X = X)
}
`[.testS3Class` <- function(x, i, ...) {
testS3Class(unclass(x)[i, ...], X = attr(x, "X"))
}
df <- tibble(x = rep(1:2, each = 5), y = testS3Class(1:10, X = 100))
res <- df %>%
group_by(x) %>%
summarise(chunk = list(y))
expect_equal(res$chunk[[1]], df$y[df$x == 1])
expect_equal(res$chunk[[1]], df$y[df$x == 1])
df$y <- testS3Class(matrix(1:20, ncol = 2), X = 200)
res <- df %>%
group_by(x) %>%
summarise(chunk = list(y))
expect_equal(res$chunk[[1]], df$y[df$x == 1, , drop = FALSE])
expect_equal(res$chunk[[1]], df$y[df$x == 1, , drop = FALSE])
})
```
> column_subset evaluating [ in the frame

- R/nest_by.R
- inst/include/dplyr/standard/GroupedCallReducer.h
- inst/include/tools/SlicingIndex.h
- src/group_indices.cpp
- tests/testthat/test-group-by.r
- tests/testthat/test-group_data.R
closes #3935. 
```
> tibble(x = integer()) %>% group_by(x) %>% group_data()
```
> Fix group_by with 0 groups

- .travis.yml
- inst/include/tools/SymbolVector.h
- inst/include/tools/debug.h
- src/group_indices.cpp
- tests/testthat/test-group_data.R
``` r
library(dplyr)
#> 
#> 
#> 
library(ggplot2)
df <- structure(
data.frame(x=1),
class = c("grouped_df", "tbl_df", "tbl", "data.frame"),
vars = list(sym("x"))
)
df
#> Warning in group_data_grouped_df(.data): Detecting old grouped_df format,
#> replacing `vars` attribute by `groups`
#> # Groups:   x [1]
#>       x
#> * <dbl>
#> 1     1
df
#> # Groups:   x [1]
#>       x
#> * <dbl>
#> 1     1
ggplot(economics_long, aes(date, value01)) +
geom_line(aes(linetype = variable))
#> Warning in grouped_indices_grouped_df_impl(.data): Detecting old …
```
> Better compat with old grouped_df format. closes #3719

- R/group_data.R
- R/grouped-df.r
- tests/testthat/test-group-by.r
- tests/testthat/test-group_data.R
- tests/testthat/test-new_grouped_df.R
> Get rid of globalVariables() call

- src/filter.cpp
- tests/testthat/test-slice.r
ping @earowang
the reason why we allowed logical was the `NA`, so I've changed it to only support all NA logical vectors: 
``` r
df <- tibble(x = 1:3)
slice(df, NA)
#> # A tibble: 0 x 1
#> # … with 1 variable: x <int>
slice(df, TRUE)
#> Error: slice condition does not evaluate to an integer or numeric vector.
slice(df, FALSE)
#> Error: slice condition does not evaluate to an integer or numeric vector.
```
<sup>Created on 2018-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> only allow all NA logical vectors. closes #3970

- R/case_when.R
- R/utils.r
- man/case_when.Rd
- tests/testthat/test-case-when.R
Includes #3980
Quosures are now allowed inside pattern expressions. Unfortunately pattern expressions themselves still can't be quosured without issues, because of the way the parent of the mask is rechained.
However I realised you're likely better off using non-tidyeval idioms to program with `case_when()`. You can simply wrap `case_when()` in regular functions, and you can now create conditional patterns easily because `NULL` inputs are ignored. This is now documented in the examples.
Closes #2929 and #3133.
> Allow quosures in case_when() patterns and document how to program with it

- R/bind.r
- R/case_when.R
- R/colwise-filter.R
- R/colwise.R
- R/compat-purrr.R
- R/error.R
- R/if_else.R
- R/join.r
- R/lead-lag.R
- R/order-by.R
- R/sample.R
- R/tbl-cube.r
- R/utils-replace-with.R
- tests/testthat/test-binds.R
- tests/testthat/test-case-when.R
- tests/testthat/test-colwise-filter.R
- tests/testthat/test-colwise.R
- tests/testthat/test-if-else.R
- tests/testthat/test-joins.r
- tests/testthat/test-lead-lag.R
- tests/testthat/test-sample.R
- tests/testthat/test-tbl-cube.R
Embed `friendly_type_of()` (currently unexported from rlang) and use it instead of `type_of()`. For example:
Before: `` `measures` must be a named list of arrays, not integer``
After:  `` `measures` must be a named list of arrays, not an integer vector``
Before: `` `false` must be factor, not ordered/factor``
After: `` `false` must have class `factor`, not class `ordered/factor` ``
> Use friendly_type_of()

- .travis.yml
This simply runs covr only on the release build.
Running it on all builds doesn't really hurt anything, the coverage reports are automatically merged by codecov. However it takes additional time because dplyr has to be fully re-compiled in order to track the coverage.
Running only on the release build will allow the rest of the builds to finish much faster.
> Run covr only on release builds

- src/filter.cpp
- tests/testthat/test-filter.r
- tests/testthat/test-sample.R
- tests/testthat/test-slice.r
I also made `slice()` preserve the original order
``` r
tb <- tibble(g = c(1, 2, 1, 2, 1), time = 5:1, x = 5:1)
tb %>%
group_by(g) %>%
arrange(time) %>%
filter(x <= 4)
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       g  time     x
#>   <dbl> <int> <int>
#> 1     1     1     1
#> 2     2     2     2
#> 3     1     3     3
#> 4     2     4     4
tb %>%
group_by(g) %>%
filter(x <= 4) %>%
arrange(time)
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       g  time     x
#>   <dbl> <int> <int>
#> 1     1     1     1
#> 2     2     2     2
#> 3     1     3     3
#> 4     2     4     4
tb %>%
group_by(g) %>%
arrange(time) %>%
slice(1,n())
#> # A tibble: 4 x 3
#> # Groups:   g [2]
#>       g  time     x
#>   <dbl> <int> <int>
#> 1     1     1     1
#> 2     2 …
```
> filter() and slice() preserve order across groups

- inst/include/tools/SymbolVector.h
- inst/include/tools/utils.h
- src/bind.cpp
- src/utils.cpp
``` r
library(dplyr)
library(purrr)
make_df = function(x){
nrows = sample(1:1000,1)
df = data.frame(id = seq(1,nrows), val = rep("character",nrows), stringsAsFactors = FALSE)
return(df)
}
make_list = function(n){
ll = lapply(1:n, function(x) make_df(x))
names(ll) = as.character(1:n)
return(ll)
}
bench_list <- function(n){
data <- make_list(n)
sizes <- map_int(data, nrow)
bench::mark(check = FALSE, 
bind_rows(data), 
bind_rows(data, .id = "id"), 
rep(names(data), sizes)
)
}
bench_list(1e3)
#> # A tibble: 3 x 10
#>   expression    min    mean  median     max `itr/sec` mem_alloc  n_gc n_itr
#>   <chr>      <bch:> <bch:t> <bch:t> <bch:t>     <dbl> <bch:byt> <dbl> <int>
#> 1 bind_rows… 7.04ms  8.03ms  7.87ms 10.23ms     125.     5.87MB    15    38
#> 2 "bind_row… 9.97ms 11.26ms  11.1ms 14.43ms …
```
> Performance of bind rows(.id =)

- inst/include/dplyr/data/DataMask.h
- tests/testthat/test-mutate.r
``` r
iris %>% 
as_tibble() %>% 
mutate_at(
vars(starts_with("Petal")),
~ ifelse(Species == "setosa" & . < 1.5, NA, .)
)
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5         NA            NA setosa 
#>  2          4.9         3           NA            NA setosa 
#>  3          4.7         3.2         NA            NA setosa 
#>  4          4.6         3.1          1.5          NA setosa 
#>  5          5           3.6         NA            NA setosa 
#>  6          5.4         3.9          1.7          NA setosa 
#>  7          4.6         3.4         NA            NA setosa 
#>  8          5           3.4 …
```
> make rlang lambdas inherit from the data mask.

- inst/include/dplyr/data/DataMask.h
- tests/testthat/test-mutate.r
> DataMask<> does nothing when .rm() a name it does not know.

- src/group_indices.cpp
- tests/testthat/test-group_split.R
> group_split(keep = FALSE) is careful about "virtual" grouping columns.

- vignettes/programming.Rmd
Although is this special case (`...`) it works, I think generally we should stick to `enquos()` inside a function.
> use `enquos(...)`, not `quos(...)` inside a function

- R/RcppExports.R
- R/group_nest.R
- R/group_split.R
- src/RcppExports.cpp
- src/group_indices.cpp
This is to help `tidyr`, i.e.  in this branch: https://github.com/tidyverse/tidyr/pull/511
specifically to uncomment this test: https://github.com/tidyverse/tidyr/blob/dce9a0939dffbfd72eff8cb7f68a147aaa969fe9/tests/testthat/test-nest.R#L48
```r
test_that("nesting works for empty data frames", {
df <- tibble(x = 1:3, y = c("B", "A", "A"))[0, ]
out <- nest(df, x)
expect_equal(names(out), c("y", "data"))
expect_equal(nrow(out), 0L)
expect_equal(length(out$data), 0L)
out <- nest(df, x, y)
expect_equal(length(out$data), 1L)
expect_equal(out$data[[1L]], df)
})
```
> keep a ptype attribute when `group_nest()`ing

- R/group-by.r
- tests/testthat/test-group-by.r
I'm one of the people responsible for maintaining [crplyr](https://github.com/Crunch-io/crplyr) and in that package we have extended some dplyr methods to work with other R objects.
Our tests are failing with the current release candidate, and I'm pretty sure I've tracked it down to the removal of passing the `add` from `group_by.default` to `group_by` which this PR fixes. We are in the process of updating crplyr to use the `group_by` method instead of `group_by_` which will also fix the problem for us, but thought we would submit this in case anyone else was running into this inconsistency.
> re-instate `add` passing for group_by.default

- .travis.yml
Because of the tight relationship between `rlang` and `dplyr` and the use of C level api, I've added a job that tests dplyr on the release version of R, but using the dev rlang. 
This would have helped with things like: https://github.com/tidyverse/dplyr/issues/4049 where even though this was a dplyr problem, it was only apparent with a dev rlang. 
I'm not sure it would make sense to do something similar for dev versions of `Rcpp` or `tidyselect`, but it's nice to find out about these things quickly enough
> travis job to check against dev rlang

- R/manip.r
- man/arrange.Rd
(This is not related to the release of 0.8.0)
`arrange()` sorts `NA` to the end, whether the column is wrapped with `desc()` or not.
``` r
dplyr::arrange(data.frame(x = c(NA, 0, 1)), x)
#>    x
#> 1  0
#> 2  1
#> 3 NA
dplyr::arrange(data.frame(x = c(NA, 0, 1)), desc(x))
#>    x
#> 1  1
#> 2  0
#> 3 NA
```
<sup>Created on 2019-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
I guess this is intentional as [the test case says so](https://github.com/tidyverse/dplyr/blob/1f440d51bb8acee2d562f9bdc00400cdc0f6ae84/tests/testthat/test-arrange.r#L18). I haven't seen someone complained about this behaviour, but I feel this is worth noting.
> Add description about arrang()ing `NA`

- R/RcppExports.R
- R/tbl-df.r
- src/RcppExports.cpp
- src/summarise.cpp
This was using a `std::vector<IntegerVector>` and growing it for some reason. 
Also, it now uses the better `column_subset()` to filter rows of the grouping structure instead of some custom visitor that only knew how to deal with trivial types.
> More stable reconstruction of grouping structure after a summarise().

- R/colwise-mutate.R
#4072 Enhance documentation for scoped mutate and transmute verbs - move descriptions out of examples and into description section of documentation
> Enhance documentation for scoped mutate and transmute verbs - move descriptions out of examples and into description section of documentation

- .travis.yml
I added this workaround in #4085, but this is fixed on upstream:
https://github.com/travis-ci/travis-build/pull/1632
> Remove r_build_args: --no-manual

- inst/include/dplyr/visitors/subset/column_subset.h
- tests/testthat/test-slice.r
This incidentally fix #4128 
``` r
dplyr::slice(tibble::enframe(formals(rnorm)), 2:3)
#> # A tibble: 2 x 2
#>   name  value    
#>   <chr> <list>   
#> 1 mean  <dbl [1]>
#> 2 sd    <dbl [1]>
```
<sup>Created on 2019-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> internal::column_subset() falls back on R indexing on esoteric

- R/colwise-mutate.R
- tests/testthat/test-colwise-mutate.R
``` r
mutate_all(tibble(`..1` = "1"), toupper)
#>   ..1  
#>   <chr>
#> 1 1
```
This uses `.data` as @krlmlr suggested, so that: 
``` r
trace(dplyr:::mutate_impl, tracer = quote({ print(dots) ; cat("--------\n\n")}))
#> Tracing function "mutate_impl" in package "dplyr
#> (not-exported)"
#> [1] "mutate_impl"
mutate_all(tibble(`..1` = "1"), toupper)
#> Tracing mutate_impl(.data, dots) on entry 
#> <list_of<quosure>>
#> 
#> $..1
#> <quosure>
#> expr: ^toupper(.data[["..1"]])
#> env:  global
#> 
#> --------
#>   ..1  
#>   <chr>
#> 1 1
```
I think this is good enough (for now), but at some point I'd like to think about moving some logic internally for the colwise verbs.
> Support for non-syntactic variable names in mutate_all()

- inst/include/dplyr/symbols.h
- inst/include/dplyr/visitors/subset/column_subset.h
- src/init.cpp
Bring back performance from @earowang example: 
``` r
id <- rep(seq.int(8143667, by = 1, length.out = 4e+3), each = 1e+4)
time <- as.POSIXct("2015-01-01 00:00", tz = "UTC") + seq(0, by = 1800, length.out = 1e+4)
index <- rep(time, 4e+3)
tbl <- tibble(id = id, index = index)
system.time(
tbl %>% 
group_by(id) %>% 
summarise(len = length(index))
)
#>    user  system elapsed 
#>   0.946   0.242   1.191
```
<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> improve performance for POSIXct.

- inst/include/dplyr/hybrid/Expression.h
- inst/include/dplyr/hybrid/scalar_result/min_max.h
- tests/testthat/test-summarise.r
```r
> tibble(
+     x = c(NA, NA,NA, 1), 
+     y = c("a","a","b","b")
+ ) %>% 
+     group_by(y) %>% 
+     summarise( z = min(x, na.rm=TRUE))
y         z
<chr> <dbl>
1 a       Inf
2 b         1
Warning message:
no non-missing arguments to min; returning Inf 
```
similar to: 
```r
> tibble(
+     x = c(NA, NA,NA, 1), 
+     y = c("a","a","b","b")
+ ) %>% 
+     group_by(y) %>% 
+     summarise( z = min(x, na.rm=T))
y         z
<chr> <dbl>
1 a       Inf
2 b         1
Warning message:
In min(x, na.rm = T) : no non-missing arguments to min; returning Inf
```
although without the call. Don't think that's a big deal, and would be more work to get to the call.
> warn on cases like min(c(NA, NA), na.rm = TRUE) in hybrid

- R/colwise-mutate.R
- R/compat-name-repair.R
- inst/include/dplyr/hybrid/scalar_result/min_max.h
- tests/testthat/test-colwise-mutate.R
``` r
library(dplyr)
#> 
#> 
#> 
storms %>% 
summarize_at(vars(wind, pressure), list(mean, median)) 
#> # A tibble: 1 x 4
#>   `wind_<fn>_1` `pressure_<fn>_1` `wind_<fn>_2` `pressure_<fn>_2`
#>           <dbl>             <dbl>         <dbl>             <dbl>
#> 1          53.5              992.            45               999
```
<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Scoped mutate/summarize with multiple columns AND functions

- inst/include/dplyr/hybrid/Expression.h
This is still the main problem that happens on the rev dev checks. This gives a warning rather than an error. 
``` r
dplyr::summarise(iris, n = n())
#> Warning: Calling n() without importing or prefixing it is deprecated
#>     n
#> 1 150
```
This would leave more time for dependent packages to adjust. 
Only doing it for `n()`, `row_number()` and `group_indices()` as this is I believe the only ones that are problematic on the rev dep checks, but perhaps this could be all dplyr functions that are possibly handled hybridly. That perhaps would be a little bit more code.
> warn when n(), row_number() or group_indices() are used without dplyr::

- inst/include/dplyr/hybrid/Expression.h
- inst/include/dplyr/lifecycle.h
- inst/include/dplyr/symbols.h
- inst/include/dplyr/visitors/subset/column_subset.h
- src/init.cpp
- src/utils.cpp
``` r
dplyr::summarise(iris, n())
#> Warning: Calling `n()` without importing or prefixing it is deprecated, use `dplyr::n()`.
#> This warning is displayed once per session.
#>   n()
#> 1 150
dplyr::summarise(iris, n())
#>   n()
#> 1 150
```
<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Call warn_deprecated() instead of simple warning for n() 

- R/RcppExports.R
- R/hybrid.R
- R/tbl-df.r
- inst/include/dplyr/hybrid/Expression.h
- inst/include/dplyr/hybrid/hybrid.h
- inst/include/dplyr/lifecycle.h
- inst/include/dplyr/symbols.h
- src/RcppExports.cpp
- src/init.cpp
- src/mutate.cpp
- src/summarise.cpp
- src/utils.cpp
- tests/testthat/helper-hybrid.R
But I'm probably doing it wrong because: 
``` r
dplyr::summarise(iris, n = n())
#>     n
#> 1 150
dplyr:::with_lifecycle_warnings({
dplyr::summarise(iris, n = n())
})
#> Error: Evaluation error: is_string(nm) is not TRUE.
```
> n() is now signal_soft_deprecated() in dplyr::summarise(n = n())

- inst/include/dplyr/hybrid/scalar_result/mean_sd_var.h
- inst/include/dplyr/hybrid/scalar_result/min_max.h
- inst/include/dplyr/hybrid/scalar_result/sum.h
- inst/include/tools/default_value.h
- tests/testthat/test-summarise.r
``` r
df <- data.frame(
month = rep(month.abb, 2), 
year = c(rep(2019, 12), rep(2020, 12)),
value = c(rep(1, 15), NaN, rep(1, 8))
)
df %>% 
group_by(year) %>% 
summarise(value = sum(value, na.rm = TRUE))
#> # A tibble: 2 x 2
#>    year value
#>   <dbl> <dbl>
#> 1  2019    12
#> 2  2020    11
```
So `na.rm = TRUE` also ignores `NaN`
> Fix hybrid min(), max(), mean(), sum() 

- R/colwise-mutate.R
- man/mutate_all.Rd
- man/summarise_all.Rd
- tests/testthat/test-colwise-mutate.R
``` r
storms %>%
summarise_at(vars(wind, pressure), list(n = length, mean, median))
#> # A tibble: 1 x 6
#>   wind_n pressure_n wind_fn1 pressure_fn1 wind_fn2 pressure_fn2
#>    <int>      <int>    <dbl>        <dbl>    <dbl>        <dbl>
#> 1  10010      10010     53.5         992.       45          999
```
unnamed functions are called `fn1`, `fn2` etc ... the numbering is based on unnamed functions only. 
And we use `unique_names()` instead of `universal_names()`
Needs to be documented somewhere (e.g. related to #4146)
> using unique_names() and more natural numbering

- R/group_trim.R
- man/group_trim.Rd
Since `filter()` reverts to the previous behaviour, specifying `.preserve = TRUE` in the `group_trim()` docs would probably serve the `group_trim()` purpose.
``` r
iris_fct <- iris %>%
group_by(Species) %>%
filter(Species == "setosa", .preserve = TRUE) %>% 
print()
#> # A tibble: 50 x 5
#> # Groups:   Species [3]
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 …
```
> tweak group_trim example by adding `.preserve = TRUE`

- inst/include/dplyr/data/GroupedDataFrame.h
- src/group_indices.cpp
- tests/testthat/test-group_data.R
The old grouping repair was not working correctly. Evidence of that appeared in the revdepchecks of 0.7.8 vs 0.8.0 on the `rzeit2` 📦
> better old grouping format repair

- R/colwise-filter.R
- tests/testthat/test-colwise-filter.R
``` r
iris %>% 
filter_if(is.numeric, any_vars(.data$. > 7))
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
#> 1           7.1         3.0          5.9         2.1 virginica
#> 2           7.6         3.0          6.6         2.1 virginica
#> 3           7.3         2.9          6.3         1.8 virginica
#> 4           7.2         3.6          6.1         2.5 virginica
#> 5           7.7         3.8          6.7         2.2 virginica
#> 6           7.7         2.6          6.9         2.3 virginica
#> 7           7.7         2.8          6.7         2.0 virginica
#> 8           7.2         3.2          6.0         1.8 virginica
#> 9           7.2         3.0          5.8         1.6 virginica
#> 10          7.4         2.8 …
```
> Support .data$. in colwise filter_*()

- R/funs.R
Just a minor thing I noticed in the warning
> Add missing paranthesis in deprecation warning

- NEWS.md
- R/group-indices.R
- tests/testthat/test-group-indices.R
Fix #4208
Change the default value of `.drop` of `group_indices.data.frame()` to `TRUE`, which makes `d %>% group_indices(...)` and `d %>% group_by(...) %>% group_indices()` return the same value.
``` r
d <- tibble(x = letters[1:10], y = rep(1:2, each = 5), z = factor(rep(LETTERS[1:2], each = 5)))
d %>% 
group_by(y, z) %>%
group_indices()
#>  [1] 1 1 1 1 1 2 2 2 2 2
d %>% 
group_indices(y, z)
#>  [1] 1 1 1 1 1 2 2 2 2 2
```
<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Make group_indices.data.frame() to drop empty groups by default

- README.Rmd
- README.md
Added missing "/" in the logo link so it works properly.
> fix logo link typo in README

- DESCRIPTION
- NEWS.md
- R/funs.R
- inst/include/dplyr/data/DataMask.h
- inst/include/tools/Quosure.h
- inst/include/tools/utils.h
- src/arrange.cpp
- src/filter.cpp
- src/mutate.cpp
- src/summarise.cpp
- tests/testthat/test-colwise-mutate.R
So that all those from #4183 are equivalent: 
``` r
iris <- head(iris, 3)
iris %>%
mutate_if(is.numeric, ~ . / iris$Petal.Width)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1         25.5        17.5          7.0           1  setosa
#> 2         24.5        15.0          7.0           1  setosa
#> 3         23.5        16.0          6.5           1  setosa
iris %>%
mutate_if(is.numeric, ~ . / Petal.Width)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1         25.5        17.5          7.0           1  setosa
#> 2         24.5        15.0          7.0           1  setosa
#> 3         23.5        16.0          6.5           1  setosa
iris %>%
mutate_if(is.numeric, ~ . / .data$Petal.Width)
#>   Sepal.Length …
```
> Uniform handling of bare formulas in colwise verbs

- NEWS.md
- src/mutate.cpp
- tests/testthat/test-mutate.r
``` r
pass_through = function(x) { x }
data.frame(a = character()) %>%
mutate(b = pass_through(a))
#> [1] a b
#> <0 rows> (or 0-length row.names)
tibble(a = character()) %>%
rowwise() %>%
mutate(b = pass_through(a))
#> Source: local data frame [0 x 2]
#> Groups: <by row>
#> 
#> # … with 2 variables: a <chr>, b <chr>
```
<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Fixed mutate() on rowwise data frames with 0 rows.

- DESCRIPTION
- NEWS.md
- src/group_indices.cpp
- tests/testthat/test-group-by.r
``` r
(x <- data.frame(y = 1))
#>   y
#> 1 1
(group_by(x))
#>       y
#>   <dbl>
#> 1     1
x
#>   y
#> 1 1
```
> group_by() makes a shallow copy even with no groups.

- R/group-by.r
- R/rowwise.r
- man/group_by.Rd
This only affects perceived default for the `.drop=` argument of `group_by()`. 
But now we'd have this: `group_by()` generic: 
```r
> group_by
function(.data, ..., add = FALSE, .drop = group_drops(.data)) {
UseMethod("group_by")
}
```
so perhaps we should be exporting `group_drops()`, maybe under a different name.
> use `group_drops(.data)` as the default for group_by(.drop=)

- DESCRIPTION
- NEWS.md
- inst/include/dplyr/hybrid/vector_result/ntile.h
- tests/testthat/test-rank.R
``` r
tibble(a = 1:1e5) %>%
mutate(b = ntile(n = 1e5)) %>%
count(b) %>%
pull() %>% 
unique()
#> [1] 1
```
<sup>Created on 2019-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> use R_xlen_t to protect from overflow in ntile()

- DESCRIPTION
- NEWS.md
- inst/include/dplyr/hybrid/vector_result/ntile.h
- tests/testthat/test-rank.R
``` r
mtcars %>%
group_by(cyl) %>% 
summarise_at(vars(DISP = disp), list(mean = mean, median = median))
#>     cyl DISP_mean DISP_median
#>   <dbl>     <dbl>       <dbl>
#> 1     4      105.        108 
#> 2     6      183.        168.
#> 3     8      353.        350.
```
<sup>Created on 2019-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> summarise_at() can rename when multiple funs

- NEWS.md
- R/colwise-mutate.R
- tests/testthat/test-colwise-mutate.R
``` r
mtcars %>%
group_by(cyl) %>% 
summarise_at(vars(DISP = disp), list(mean = mean, median = median))
#>     cyl DISP_mean DISP_median
#>   <dbl>     <dbl>       <dbl>
#> 1     4      105.        108 
#> 2     6      183.        168.
#> 3     8      353.        350.
```
<sup>Created on 2019-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
> Can rename in summarise_at() with multiple functions.

- NEWS.md
- R/colwise-select.R
- tests/testthat/test-colwise-select.R
``` r
ids <- "Sepal.Length"
as_tibble(iris) %>% 
select_if(!names(.) %in% ids)
#> # A tibble: 150 x 4
#>    Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>        <dbl>       <dbl> <fct>  
#>  1         3.5          1.4         0.2 setosa 
#>  2         3            1.4         0.2 setosa 
#>  3         3.2          1.3         0.2 setosa 
#>  4         3.1          1.5         0.2 setosa 
#>  5         3.6          1.4         0.2 setosa 
#>  6         3.9          1.7         0.4 setosa 
#>  7         3.4          1.4         0.3 setosa 
#>  8         3.4          1.5         0.2 setosa 
#>  9         2.9          1.4         0.2 setosa 
#> 10         3.1          1.5         0.1 setosa 
#> # … with 140 more rows
as_tibble(iris) %>% …
```
> select_if() and rename_if() handle lgl vectors.

- appveyor.yml
- inst/include/dplyr/hybrid/vector_result/ntile.h
- tests/testthat/helper-hybrid.R
Use floating point division again, because in some situation (incl the ones we use for testing) we'd get an overflow on 32 bit platforms (i.e. where `R_xlen_t` is `int`).
> Fix ntile()  in win32

- inst/include/dplyr/hybrid/scalar_result/min_max.h
- tests/testthat/test-summarise.r
That's only possible when there are no empty groups after NA removal.
> Attempt to coerce results of min() and max() to int

- R/manip.r
- man/summarise.Rd
Clarify that `summarise()` will overwrite a variable of the same name.
* Fixes #4285.
> Clarify `summarise()` behaviour.

- tests/testthat/test-mutate.r
I just `skip()` the tests for now. 
Not sure where the encoding is lost, it's issue #2967 again. I can investigate some more, but just skipping the tests for now. 
```
> test_check("dplyr")
-- 1. Failure: Non-ascii column names in version 0.3 are not duplicated (#636) (
`res` not equal to names(df).
Lengths differ: 3 is not 2
-- 2. Failure: Non-ascii column names in version 0.3 are not duplicated (#636) (
`res` not equal to names(df).
Lengths differ: 3 is not 2
```
This is different, it does not even parse on the cran machine, it does not even get to execute any dplyr. 
```
-- 3. Error: no utf8 invasion (#722) (@test-mutate.r#481) ---------------------
utf-8.txt:5:0: unexpected end of input
3: # we use a different file extension to avoid this.
4: df <- data.frame(
^
1: source("utf-8.txt", …
```
> check problems of 0.8.0.1

- R/colwise-mutate.R
- inst/include/dplyr/data/DataMask.h
- inst/include/dplyr/hybrid/Expression.h
- inst/include/dplyr/symbols.h
- src/init.cpp
`manip_all()` ... record position of each of the used symbols in the `position` attribute. This is then used internally to bypass some encoding problems in hybrid evaluation, e.g. #4258
> colwise expressions using position of variable instead of symbol.

- R/group-by.r
- revdep/README.md
- revdep/problems.md
- revdep/revdep_dplyr0.8.1.md
- tests/testthat/test-group-by.r
This gives a more forgiving `group_by_drop_default()` because sometimes `group_by()` is used on corrupt grouped_df for the purpose of making them right, e.g. in the `extdplyr` 📦 . 
``` r
library(dplyr)
df <- tibble(x = 1:2, y = 1:2) %>%
structure(class = c("grouped_df", "tbl_df", "tbl", "data.frame"))
group_by_drop_default(df)
#> [1] TRUE
```
<sup>Created on 2019-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> Fixing group_by_drop_default()

- vignettes/programming.Rmd
`quos` and `enquos` are both acceptable here. But I believe `enquos` would be more consistent and intuitive in the context of the vignette.
> Fix a typo in the vignette of programming with dplyr

- src/encoding.cpp
Often if you are going to be visiting all elements of an Altrep vector
materializing it early on is much more performant than doing
element-wise access. Both because the element wise access has more
overall overhead and because often you end up materializing the full
vector at other stages later on (which is the case in `group_by()`),
which can incur the costs of retrieving the data more than once.
This can be seen with the current devel version of vroom
(https://github.com/jimhester/vroom/commit/cc082485116bb326cd037b80718ca11bbe06faf0)
doing a naive `dplyr::group_by()` with an altrep vector (df2) is
significantly slower than explicitly materializing the vector (df1)
prior to the `group_by()` call.
input <- vroom::gen_tbl(1e6, 2, col_types = "fd")
readr::write_csv(input, "test.csv")
df1 …
> Materialize Altrep character vectors before re-encoding

- .travis.yml
- DESCRIPTION
- NEWS.md
https://www.tidyverse.org/articles/2019/04/r-version-support/
> Support R > 3.2.0 and use_tidy_versions(CRAN)

- NEWS.md
- R/colwise-select.R
- tests/testthat/test-colwise-select.R
``` r
dplyr::rename_at(head(mtcars), character(),~paste0("NewCol.",.))
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
```
<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> rename_at() handles empty selection.

- R/src-local.r
- tests/testthat/test-copy_to.R
``` r
dplyr::src_df(env = rlang::env(. = iris))
#> src:  <environment: 0x7feac82c5838>
#> tbls: .
```
<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> src_tbls() includes all tbls.

- NEWS.md
- inst/include/dplyr/visitors/order/OrderVisitorImpl.h
- inst/include/tools/comparisons.h
- src/arrange.cpp
- tests/testthat/test-arrange.r
This is temporary workaround until `vctrs::vec_order()` can handle integer64 objects (and we use `vec_order()`). related to https://github.com/r-lib/vctrs/issues/348
``` r
suppressPackageStartupMessages(library(bit64))
df <- tibble(x = bit64::as.integer64(c(1, 3, 2, 1)))
arrange(df, x)
#> # A tibble: 4 x 1
#>   x      
#>   <int64>
#> 1 1      
#> 2 1      
#> 3 2      
#> 4 3
arrange(df, -x)
#> # A tibble: 4 x 1
#>   x      
#>   <int64>
#> 1 3      
#> 2 2      
#> 3 1      
#> 4 1
arrange(df, desc(x))
#> # A tibble: 4 x 1
#>   x      
#>   <int64>
#> 1 3      
#> 2 2      
#> 3 1      
#> 4 1
```
<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> support for arrange() for integer64

- NEWS.md
- R/funs.R
- R/utils.r
- tests/testthat/test-colwise-mutate.R
``` r
suppressPackageStartupMessages(library(dplyr))
library(rlang)
df <- mtcars[1:5, ]
transmute_at(df, vars(mpg), ~ . > mean(.))
#>     mpg
#> 1  TRUE
#> 2  TRUE
#> 3  TRUE
#> 4  TRUE
#> 5 FALSE
transmute_at(df, vars(mpg), quo(. > mean(.)))
#> expecting a one sided formula, a function, or a function name.
transmute_at(df, vars(mpg), ~ mean(.))
#>     mpg
#> 1 20.98
#> 2 20.98
#> 3 20.98
#> 4 20.98
#> 5 20.98
transmute_at(df, vars(mpg), quo(mean(.)))
#> expecting a one sided formula, a function, or a function name.
```
<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> unsupport quosures in colwise functions

- NEWS.md
- inst/include/dplyr/hybrid/Column.h
- inst/include/dplyr/hybrid/Expression.h
- inst/include/dplyr/hybrid/scalar_result/first_last.h
- inst/include/dplyr/hybrid/scalar_result/mean_sd_var.h
- inst/include/dplyr/hybrid/scalar_result/min_max.h
- inst/include/dplyr/hybrid/scalar_result/n_distinct.h
- inst/include/dplyr/hybrid/scalar_result/sum.h
- inst/include/dplyr/hybrid/vector_result/in.h
- inst/include/dplyr/hybrid/vector_result/lead_lag.h
- inst/include/dplyr/hybrid/vector_result/ntile.h
- inst/include/dplyr/hybrid/vector_result/rank.h
- inst/include/dplyr/hybrid/vector_result/row_number.h
- inst/include/dplyr/symbols.h
- src/init.cpp
``` r
library(dplyr)
n = 1e5
dat = tibble(
id  = sample(x = seq(1, n),    size = n, replace = TRUE),
val = sample(x = letters[1:4], size = n, replace = TRUE) %>%
factor(., levels = letters[1:4]))
f1 <- function(dat) {
dat %>%
group_by(id) %>%
summarise(first_val = dplyr::first(val))
}
f2 <- function(dat) {
dat %>%
mutate(val = as.character(val)) %>%
group_by(id) %>%
summarise(first_val = dplyr::first(val)) %>%
mutate(first_val = factor(first_val, levels = letters[1:4]))
}
bench::mark(f1(dat), f2(dat))
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 x 6
#> 1 f1(dat)       235ms    251ms      3.98    1.76MB …
```
> hybrid version of first() and friends for factors

- NEWS.md
- inst/include/dplyr/visitors/vector/VectorVisitorImpl.h
- tests/testthat/test-group-by.r
``` r
tbl <- tibble(
x = c("apple", NA, "banana"), 
y = 1:3
)
tbl %>% 
group_by(x) %>% 
group_data()
#> # A tibble: 3 x 2
#>   x      .rows    
#>   <chr>  <list>   
#> 1 apple  <int [1]>
#> 2 banana <int [1]>
#> 3 <NA>   <int [1]>
```
<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> `group_by()` puts NA groups last in character vectors.

- R/funs.R
This does not mention `list2()` because it's not so easy to figure out a simple example that would benefit from splicing. 
``` r
library(purrr)
p <- c(0.2, 0.5, 0.8)
p_names <- map_chr(p, ~paste0(.x*100, "%"))
p_funs <- map(p, ~partial(quantile, probs = .x, na.rm = TRUE)) %>% 
set_names(nm = p_names) 
mtcars %>% 
group_by(cyl) %>% 
summarize_at(vars(mpg), funs(!!!p_funs))
#> Warning: funs() is soft deprecated as of dplyr 0.8.0
#> please use a list of either functions or lambdas, some examples: 
#> 
#>   # simple named list: 
#>   list(mean = mean, median = median)
#> 
#>   # auto named with tibble::lst(): 
#>   tibble::lst(mean, median)
#> 
#>   # using lambdas
#>   list(mean = ~mean(., trim = .2), median = ~median(., na.rm = TRUE))
#> This warning …
```
> extend funs() deprecation message.

- R/count-tally.R
- man/tally.Rd
As `wt` is an optional parameter, if not used, it seems as there is a missing parameter with no default
> wt parameter is (and should be) optional

- NEWS.md
- R/RcppExports.R
- R/group_map.R
- R/group_nest.R
- R/group_split.R
- src/RcppExports.cpp
- src/group_indices.cpp
- tests/testthat/test-group_map.R
- tests/testthat/test-group_split.R
``` r
mtcars %>%
group_by(cyl) %>%
filter(hp > 1000) %>%
group_map(~.x)
#> list()
#> attr(,"ptype")
#> # A tibble: 0 x 10
#> # … with 10 variables: mpg <dbl>, disp <dbl>, hp <dbl>, drat <dbl>,
#> #   wt <dbl>, qsec <dbl>, vs <dbl>, am <dbl>, gear <dbl>, carb <dbl>
mtcars %>%
group_by(cyl) %>%
filter(hp > 1000) %>%
group_modify(~.x)
#> # A tibble: 0 x 11
#> # Groups:   cyl [0]
#> # … with 11 variables: cyl <dbl>, mpg <dbl>, disp <dbl>, hp <dbl>,
#> #   drat <dbl>, wt <dbl>, qsec <dbl>, vs <dbl>, am <dbl>, gear <dbl>,
#> #   carb <dbl>
```
<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> group_map() and group_modify() work with 0 groups grouped_df

- .travis.yml
- R/utils-expr.R
- R/utils.r
- tests/testthat/test-colwise-filter.R
- tests/testthat/test-colwise-mutate.R
- tests/testthat/test-colwise-select.R
- tests/testthat/test-colwise.R
- tests/testthat/test-funs.R
- tests/testthat/test-group-by.r
- tests/testthat/test-group_data.R
- tests/testthat/test-hybrid-traverse.R
- tests/testthat/test-overscope.R
- tests/testthat/test-tbl-cube.R
mostly so that I don't see the lifecycle warnings when testing e.g. `funs()` 
But maybe I don't do this correctly, wasn't there something to disable soft deprecation warnings from dplyr when testing dplyr ? @lionel-
> update some tests

- NEWS.md
- inst/include/dplyr/data/DataMask.h
``` r
library(purrr)
library(rlang)
#> 
#> Attaching package: 'rlang'
#> The following objects are masked from 'package:purrr':
#> 
#>     %@%, as_function, flatten, flatten_chr, flatten_dbl,
#>     flatten_int, flatten_lgl, flatten_raw, invoke, list_along,
#>     modify, prepend, splice
df <- tibble(x = 1:50000)
system.time(df <- group_by(df, x))
#>    user  system elapsed 
#>   0.127   0.006   0.133
system.time(df %>% mutate(y = x + 1))
#>    user  system elapsed 
#>   0.287   0.025   0.311
df_x <- df$x
rows <- group_rows(df)
system.time(map(rows, ~.subset(df_x, .) + 1))
#>    user  system elapsed 
#>   0.060   0.003   0.063
mask_resolved <- child_env(empty_env())
mask_active <- child_env(mask_resolved)
data_mask <- new_data_mask(mask_active, …
```
> Fix performance regression in dplyr 0.8.2

- NEWS.md
- R/reexport-tidyselect.R
Fixes #4432
@romainfrancois does it look ok to you
> Deprecate select_vars, rename_vars, select_var, current_vars

- R/recode.R
- man/recode.Rd
Closes #3768 
I added an example and modified slightly the wording of another to make it clearer that NAs need to be of the same type as replacement values, similarly to what was done for `case_when` via https://github.com/tidyverse/dplyr/pull/3247
> Add example in recode about NA types

- R/do.r
- R/rowwise.r
- man/do.Rd
- man/rowwise.Rd
Both, `do.r` and `rowwise.r` are already marked as questioning and have proposed alternatives. 
Discussed with @romainfrancois. 
For consistency, I moved the `do()` alternative up to right after the badge + changed proposed alternative `group_map()` to `group_modify()`.
`rowwise.r` alternative got a dot added at the end of the sentence ;-). 
Closes #3494.
> Rowwise() + do() questioning: propose alternatives

- NEWS.md
- src/group_indices.cpp
- tests/testthat/test-group-by.r
when grouping by factors with `drop = TRUE`.
closes #4460
``` r
ig <- group_by(iris, Species)
group_data(ig[0,])
#> # … with 2 variables: Species <fct>, .rows <list>
```
<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> `group_by()` does not create an arbitrary NA group 

- R/colwise.R
- tests/testthat/test-colwise-select.R
``` r
tibble(mycol=c("","",NA)) %>% 
select_if(~!all(.==""))
#> # A tibble: 3 x 0
```
<sup>Created on 2019-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> select_if() discards column when predicate evaluates to NA.

- NEWS.md
- inst/include/dplyr/symbols.h
- inst/include/dplyr/visitors/subset/column_subset.h
- src/init.cpp
closes #4501
``` r
n <- 1e5
system.time(d <- tibble(
x=sample(2000, n, TRUE),
y=sample(800, n, TRUE),
int=sample(5, n, TRUE),
fac = factor(int), 
ord = ordered(int, levels=c("4", "1", "3", "2", "5")),
val=runif(n)
) 
)
#>    user  system elapsed 
#>   0.017   0.002   0.018
system.time(d <- d %>% group_by(x, y))
#>    user  system elapsed 
#>   0.259   0.010   0.270
system.time(d %>% summarize(w = val[which.max(ord)]))
#>    user  system elapsed 
#>   0.478   0.038   0.516
system.time(d %>% summarize(w = val[which.max(fac)]))
#>    user  system elapsed 
#>   0.467   0.036   0.503
system.time(d %>% summarize(w = val[which.max(int)]))
#>    user  system elapsed 
#>   0.429   0.038   0.467
system.time(d %>% summarize(w = {int; 1L}))
#>    user  system …
```
> Better performance for slicing factors and ordered factors.

- README.Rmd
- README.md
small typo in Backends. Url for dtplyr redirected to dbplyr
> Fix README dtplyr link

- R/tbl-df.r
- tests/testthat/test-group-by.r
- tests/testthat/test-joins.r
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise.r
First commit fixes tests that failed previously.
Closes #2326.
> Fix auto-splice for tibbles

- R/manip.r
- tests/testthat/test-transmute.R
closes #4609
``` r
df <- data.frame(x=1)
transmute(df, y =x+1, z=y*2)
#>   y z
#> 1 2 4
```
<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> transmute() no longer warns when = NULL

- DESCRIPTION
- R/bind.r
- tests/testthat/test-binds.R
closes #4599
``` r
tibble_1 <- tibble(col = "foo")
tibble_2 <- tibble(nested = tibble(bar = 33))
bind_cols(tibble_1, tibble_2)
#> # A tibble: 1 x 2
#>   col   nested$bar
#>   <chr>      <dbl>
#> 1 foo           33
```
<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> bind_cols() handles packs

- R/group_split.R
- tests/testthat/test-group_nest.R
- tests/testthat/test-group_split.R
closes #4611
``` r
iris %>% 
group_by(Species) %>% 
tidyr::nest()
#> # A tibble: 3 x 2
#> # Groups:   Species [3]
#>   Species              data
#>   <fct>      <list<df[,4]>>
#> 1 setosa           [50 × 4]
#> 2 versicolor       [50 × 4]
#> 3 virginica        [50 × 4]
iris %>% 
group_nest(Species)
#> # A tibble: 3 x 2
#>   Species              data
#>   <fct>      <list<df[,4]>>
#> 1 setosa           [50 × 4]
#> 2 versicolor       [50 × 4]
#> 3 virginica        [50 × 4]
```
<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> group_split() returns a vctrs_list_of

- R/lead-lag.R
- R/order-by.R
- tests/testthat/test-colwise-mutate.R
- tests/testthat/test-lead-lag.R
closes #4558
``` r
suppressPackageStartupMessages({
library(bit64)
library(dplyr)
})
lag(bit64::as.integer64(c(1,2,3)), 1)
#> integer64
#> [1] <NA> 1    2
```
<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> vctrs:: based implementation for lead() and lag()

- R/colwise-mutate.R
- man/summarise_all.Rd
In the examples for summarise_at, a selection of variables called nms is created but not used.
This also demonstrates that you can pass a character vector directly to .vars without the need of the vars(one_of(...)) pattern.
> Tiny clarification for example for summarise_at

- R/grouped-df.r
- man/new_grouped_df.Rd
- src/dplyr.cpp
- src/dplyr/symbols.h
- tests/testthat/test-group_data.R
- tests/testthat/test-new_grouped_df.R
The R implementation was fairly slow, and this is not something we need vctrs for
```
[validate_grouped_df*] 282.4 MiB ❯ callr::r(function() {
+   library(dplyr, warn.conflicts = FALSE)
+   df <- tibble(x = rnorm(1e4), g = sample(rep(1:1e2, 100))) %>% group_by(g)
+   bench::mark(summarise(df, n = 0 + 0))
+ }, lib = "bench-libs/master")
expression                    min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result             memory               time     gc               
<bch:expr>               <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>             <list>               <list>   <list>           
1 summarise(df, n = 0 + 0)     22ms   26.7ms      36.3    1.54MB     61.2    19    32      523ms <tibble [100 × 2]> <df[,3] [1,720 × 3]> …
```
> internal implementation for validate_grouped_df

- R/group_keys.R
- inst/bench/bench.R
- src/dplyr.cpp
- src/dplyr/symbols.h
``` r
library(bench)
library(dplyr)
callr::r(function(){
library(dplyr)
df <- tibble(x = rnorm(1e6), g = sample(rep(1:1e4, 100))) %>% group_by(g)
bench::mark(a = group_keys(df))
}, lib = "/Users/romainfrancois/git/tidyverse/dplyr/bench-libs/0.8.3")
#> # A tibble: 1 x 6
#> 1 a             721µs    774µs     1217.     515KB     51.2
callr::r(function(){
library(dplyr)
df <- tibble(x = rnorm(1e6), g = sample(rep(1:1e4, 100))) %>% group_by(g)
bench::mark(a = group_keys(df))
}, lib = "/Users/romainfrancois/git/tidyverse/dplyr/bench-libs/master")
#> # A tibble: 1 x 6
#>   <bch:expr> <bch:tm> <bch:tm> …
```
> faster internal group_keys()

- R/count-tally.R
- man/tally.Rd
- tests/testthat/test-count-tally.r
Fixes a bug introduced by 4408 - tally needs to differentiate between a missing `wt` and `wt = NULL`.
- `wt` is missing indicates that it should use a variable named `n` as `wt` by default (used by `tally()`)
- `wt = NULL` indicates that it should not use `n` (used by `count()`)
> use n as default wt in tally

- R/top-n.R
- man/top_n.Rd
Made it clear in the documentation that top_n doesn't return an ordered data frame, because I found that surprising. Also changed the example code to show a case where the returned results are not ordered.
Modified the top-n.R and generated top_n.Rd with roxygen2.
> Document top_n() returns unsorted data frame

- R/tbl-df.r
Closes #4571.
With this PR:
``` r
library(dplyr)
library(nycflights13)
flights_var <- quo(flights)
rlang::eval_tidy(rlang::quo(nest_join(airlines[1:3, ], !!flights_var)))
#> Joining, by = "carrier"
#>   carrier name                   flights               
#>   <chr>   <chr>                  <list>                
#> 1 9E      Endeavor Air Inc.      <tibble [18,460 × 18]>
#> 2 AA      American Airlines Inc. <tibble [32,729 × 18]>
#> 3 AS      Alaska Airlines Inc.   <tibble [714 × 18]>
```
<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> WIP: Use as_label() for determining name of RHS table after nest_join()

- R/tbl-df.r
- src/dplyr.cpp
- tests/testthat/test-filter.r
- tests/testthat/test-mutate.r
Similar to #4646 but for mutate()
With profile code: 
```r
df <- tibble(x = rnorm(1e6), g = sample(rep(1:1e4, 100))) %>% group_by(g)
profvis::profvis(for (i in 1:100) out <- mutate(df, a = rep(+1L, n())))
```
We start at: 
after internalizing the loop that makes the chunks:
> internalize calculation of chunks in mutate()

- NEWS.md
Pull request #4102 has already been merged, but it did not contain a corresponding update to `NEWS.md`. This PR does.
The reason is that when I submitted the PR, `NEWS.md` was still at 0.8.0 for the then upcoming release: 
> I didn't yet make any changes to `NEWS` (or `DESCRIPTION`) as in branch master they are still at 0.8.0 for the upcoming release. I'm happy to add to this PR later to add an item to `NEWS`, but thought I'd leave it out for now to not cause any extra work for maintainers, in case a number of PRs go about bumping the version number and adding a new header to `NEWS`.
> Update NEWS.md for already merged PR #4102

- R/tbl-df.r
- tests/testthat/test-joins.r
``` r
left_join(tibble(a = c(1:3, 3:1)), tibble(a = 3:1, b = 1:3))
#> Joining, by = "a"
#> # A tibble: 6 x 2
#>       a     b
#>   <int> <int>
#> 1     1     3
#> 2     2     2
#> 3     3     1
#> 4     3     1
#> 5     2     2
#> 6     1     3
```
<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> row order for left_join() and right_join()

- R/distinct.R
- R/group-by.r
- R/tbl-df.r
- tests/testthat/test-distinct.R
- tests/testthat/test-group-by.r
~This needs some testing I guess, but~ `group_by()` gets somewhat smarter about its implicit `mutate()` step, in particular this means we can use `across()` in `group_by()` : 
``` r
iris %>% 
group_by(data.frame(Species = Species))
#> # A tibble: 150 x 5
#> # Groups:   Species [3]
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9 …
```
> group_by() and distinct() understands auto splicing

- R/across.R
- tests/testthat/test-summarise.r
``` r
iris %>% group_by(Species) %>% summarise(across(is.numeric, mean))
#> # A tibble: 3 x 5
#>   Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
#>   <fct>             <dbl>       <dbl>        <dbl>       <dbl>
#> 1 setosa             5.01        3.43         1.46       0.246
#> 2 versicolor         5.94        2.77         4.26       1.33 
#> 3 virginica          6.59        2.97         5.55       2.03
iris %>% group_by(Species) %>% summarise(across(everything(), mean))
#> # A tibble: 3 x 5
#>   Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
#>   <fct>             <dbl>       <dbl>        <dbl>       <dbl>
#> 1 setosa             5.01        3.43         1.46       0.246
#> 2 versicolor         5.94        2.77 …
```
> across() selection does not include grouping variables

- R/join.r
- tests/testthat/test-join.r
before: 
``` r
e <- data.frame(x = c(1, 1, 2, 3), z = 1:4)
f <- data.frame(x = c(1, 2, 2, 4), z = 1:4)
full_join(e, f, by = c("x" = "z"))
#> Warning in out[by_x] <- vec_rbind(vec_slice(x[, by_x, drop = FALSE],
#> x_indices_one), : number of items to replace is not a multiple of
#> replacement length
#>    x  z x.y
#> 1  1  1   1
#> 2  1  2   1
#> 3  2  3   2
#> 4  3  4   2
#> 5 NA NA   4
```
after: 
``` r
e <- data.frame(x = c(1, 1, 2, 3), z = 1:4)
f <- data.frame(x = c(1, 2, 2, 4), z = 1:4)
full_join(e, f, by = c("x" = "z"))
#>   x  z x.y
#> 1 1  1   1
#> 2 1  2   1
#> 3 2  3   2
#> 4 3  4   2
#> 5 4 NA   4
```
<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> rename before vec_rbind() for the by_x part of the full join

- tests/testthat/test-grouped-df.r
In `$<-()`, the `value` argument needs to come after the ellipsis, otherwise `R CMD check` complains. The test was malformed and only worked due to a bug in tibble.
> Fix broken test

- R/summarise.R
- src/summarise.cpp
- tests/testthat/test-summarise.r
``` r
tibble(a = 1:2) %>% group_by(a) %>% summarise(x = 1, y = 1:3, z = 1)
#> # A tibble: 6 x 4
#>       a     x     y     z
#>   <int> <dbl> <int> <dbl>
#> 1     1     1     1     1
#> 2     1     1     2     1
#> 3     1     1     3     1
#> 4     2     1     1     1
#> 5     2     1     2     1
#> 6     2     1     3     1
```
<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> summarise() tidy recycling

- R/tbl-df.r
- tests/testthat/test-context.R
I'll probably also tackle here that there are for no apparent good reasons two ways to get to the current group: https://github.com/tidyverse/dplyr/blob/master/src/dplyr.h#L78
```c
#define DPLYR_MASK_SET_GROUP(INDEX)                                                  \
SEXP rows_i = VECTOR_ELT(rows, i);                                                   \
R_xlen_t n_i = XLENGTH(rows_i);                                                      \
SEXP current_group = PROTECT(Rf_ScalarInteger(i + 1));                               \
Rf_defineVar(dplyr::symbols::current_group, current_group, env_private);             \
Rf_defineVar(dplyr::symbols::dot_dot_group_size, Rf_ScalarInteger(n_i), env_context);\
Rf_defineVar(dplyr::symbols::dot_dot_group_number, current_group, env_context) ;     \ …
```
> Fix cur_group()

- NEWS.md
- R/join-cols.R
- R/join.r
- man/mutate-joins.Rd
- man/nest_join.Rd
- tests/testthat/test-join-cols.R
- tests/testthat/test-join.r
@hadley as discussed in #4589, this is a quick first attempt to implement `keep = TRUE` for `left_join()` and `right_join()` in the same way as `full_join()` in 1e76e8a. It also keeps the suffix on the join column from the left table when `keep = TRUE`. No new examples or tests added yet.
I'll use these examples to add tests in a later commit:
```
band_members %>% left_join(band_instruments, by = c("name"), keep = TRUE)
band_members %>% right_join(band_instruments, by = c("name"), keep = TRUE)
band_members %>% full_join(band_instruments, by = c("name"), keep = TRUE)
band_members %>% left_join(band_instruments2, by = c("name" = "artist"), keep = TRUE)
band_members %>% right_join(band_instruments2, by = c("name" = "artist"), keep = TRUE)
band_members %>% full_join(band_instruments2, by = …
```
> Implement keep = T in left_join(), right_join()

- R/conditions.R
- tests/testthat/test-colwise-mutate-errors.txt
- tests/testthat/test-filter-errors.txt
- tests/testthat/test-filter.r
- tests/testthat/test-group-by-errors.txt
- tests/testthat/test-mutate-errors.txt
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise-errors.txt
- tests/testthat/test-summarise.r
``` r
tibble(x = 1, y = c(1, 2, 2), z = runif(3)) %>%
rowwise() %>%
summarise(a = lm(y ~ x))
#> Error: `summarise()` argument `a` must be a vector.
#> ℹ `a` is `lm(y ~ x)`.
#> ℹ The error occured in row 1.
#> x `a` must be a vector, not a list.
#> ℹ Did you mean: `a = list(lm(y ~ x))` ?
data.frame(x = c(2, 2, 3, 3)) %>%
rowwise() %>%
mutate(int = 1:5)
#> Error: `mutate()` argument `int` must be recyclable.
#> ℹ `int` is `1:5`.
#> ℹ The error occured in row 1.
#> x `int` can't be recycled to size 1.
#> ℹ `int` must be size 1, not 5.
#> ℹ Did you mean: `int = list(1:5)` ?
```
<sup>Created on 2020-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> row wise specific error bullets

- tests/testthat/test-arrange.r
> test arrange() supprt for across()

- R/data-mask.R
The `resolve_chunks()` function can be made simpler for ungrouped data frames because there is always only one group. 
However, this perhaps steps on #4722 
The win here is to avoid a `vec_slice()` that would just return the full column.
> Skip vec_slice() for ungrouped data frames

- R/filter.R
- man/filter.Rd
- man/slice.Rd
Various updates to the filter() documentation. 
- Adds brief introduction to make the "details" section less jarring
- Minor tidying to text to improve readability
- Attempts to describe the arguments more clearly
- Removes "see alsos" that will be redundant in an `across()` workflow
Closes #4791. I hope :slightly_smiling_face:
> Updates documentation to filter()

- R/mutate.R
- man/mutate.Rd
Fixes #4788 - Update examples to use starwars data to avoid use of as_tibble(), example datasets slimmed down for clarity
> update examples to use starwars data, re-factor examples for clarity

- R/data-mask.R
- src/dplyr.h
Instead of calling `Rf_defineVar()` over and over again, we define the `private$current_group` once and then update the value, the R side of the code that access it makes a copy. 
This is a minor performance fix.
> Only one defineVar for current_group

- DESCRIPTION
- R/data-mask.R
- R/mutate.R
- src/dplyr.h
- src/init.cpp
Based on looking at some profvis results, we were still paying unnecessary price for active bindings, even though the slices were materialized only once, i.e. this was still somewhat expensive `.subset2(chunks, private$current_group)` when we actually go through groups one by one predictably. 
We still need some laziness, because the first time a variable from the data is used causes lots of slicing, but once we know we need it, we can just install it instead of relying on another form of lazyness. 
So for each column from the data, we either need to materialize slices 0 or 1 times. Therefore switching to promises instead of active bindings. This needs this though. https://github.com/r-lib/rlang/pull/910
> Using promises instead of active bindings

- R/data-mask.R
- tests/testthat/test-mutate.r
closes #4845
``` r
test <- tibble(x = 1:2)
test %>%
rowwise() %>%
mutate(a = list(1)) %>%
mutate(b = list(a + 1))
#> # A tibble: 2 x 3
#> # Rowwise: 
#>       x a         b        
#>   <int> <list>    <list>   
#> 1     1 <dbl [1]> <dbl [1]>
#> 2     2 <dbl [1]> <dbl [1]>
test %>%
rowwise() %>%
mutate(a = list(1),
b = list(a + 1))
#> # A tibble: 2 x 3
#> # Rowwise: 
#>       x a         b        
#>   <int> <list>    <list>   
#> 1     1 <dbl [1]> <dbl [1]>
#> 2     2 <dbl [1]> <dbl [1]>
```
<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> Additional rowwise() magic within the same mutate() call.

- R/all-equal.r
i think this block might have an oversight?  `x=` in both cases is a factor, so `convert = FALSE` gives the same result as `convert = TRUE`
df1 <- data.frame(x = "a")
df2 <- data.frame(x = factor("a"))
all_equal(df1, df2)
all_equal(df1, df2, convert = TRUE)
if you don't want to add stringsAsFactors = FALSE here, another easy edit would be
df1 <- data.frame(x = 1L)
df2 <- data.frame(x = 1.0)
all_equal(df1, df2)
all_equal(df1, df2, convert = TRUE)
> oversight in example text

- R/group_data.R
- R/grouped-df.r
- src/dplyr.h
- src/group_by.cpp
- src/group_data.cpp
- src/init.cpp
- tests/testthat/test-group_data-errors.txt
- tests/testthat/test-group_data.R
This appeared to be taking unnecessary time, presumably because of the infamous `row.names` handling in R, so I worked out it. 
``` r
library(dplyr)
df <- tibble(x = rnorm(1e6), g = sample(rep(1:1e4, 100))) %>% group_by(g)
bench::mark(
group_keys(df), 
group_data(df)[-2], 
check = FALSE # not exactly the same because `group_keys()` also removes the .drop attribute
)
#> # A tibble: 2 x 6
#>   expression              min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>         <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 group_keys(df)       4.37µs   4.97µs   171603.    27.6KB     17.2
#> 2 group_data(df)[-2] 345.28µs  413.9µs     2482.    41.3KB     14.6
```
> Faster internal group_keys implementation

- R/join.r
- tests/testthat/test-join.r
This is just avoiding the problem, which I think is related to https://github.com/r-lib/vctrs/issues/807
``` r
library(vctrs)
library(tibble)
df <- tibble(x = NA)
vec_ptype(df)$x
#> logical(0)
vec_ptype2(df, df)$x
#> <unspecified> [0]
```
<sup>Created on 2020-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> join_mutate() using vec_ptype_common() instead of vec_ptype2()

- R/across.R
- tests/testthat/test-across.R
Fixes #4867: across() did not work on one column data.frame because a call to `[` was made without setting `drop = FALSE`.
> Prevent collapse of data.frame to vector in across (#4867)

- R/slice.R
- tests/testthat/test-slice.r
Removes `NA`'s from the columns.
Closes https://github.com/tidyverse/dplyr/issues/4826
> Prevent slice_min/max from crashing when there are NA's

- R/join-rows.R
Part of #4873 
This uses `vec_assign()` and `vec_equal_na()` to detect and replace `NULL` values with `NA_integer`, rather than `map()`
This only affects `left_join()` and `full_join()`, but I've included benchmarks for `right_join()` and `inner_join()` to note the previous performance difference between those and `left/full_join()` because of this `map()` call.
``` r
library(bench)
set.seed(342)
df1 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE))
df2 <- tibble(y = rnorm(1e3), a = sample(1:10, 1e3, replace = TRUE))
df3 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE), b = sample(1:5, 1e5, replace = TRUE))
df4 <- tibble(y = rnorm(1e3), a = sample(1:10, 1e3, replace = TRUE), b = sample(1:5, 1e3, replace = TRUE))
```
```r …
```
> More efficient replacement of `NULL` with `NA_integer` in `join_rows()`

- R/join.r
Part of #4873 
This only affects left and inner joins
In `join_mutate()`, `y_extra` only contains data on a right or full join. We are paying for extra copies of `rows$x` and `rows$y` in a few cases for left and inner joins, and we can avoid the updating of `new_rows` when `keep = TRUE` altogether, because we know there aren't any new rows
https://github.com/tidyverse/dplyr/blob/c6522a15bd7e37d4d760415af3e93c889d1a9b5f/R/join.r#L337-L341
Note the memory difference as well as the times in the benchmarks below
```r
library(bench)
set.seed(342)
df1 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE))
df2 <- tibble(y = rnorm(1e3), a = sample(1:10, 1e3, replace = TRUE))
df3 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE), b = …
```
> Avoid `c()` calls when only `x` rows are required

- R/colwise.R
This addresses the request in #4803.
> Inside `dplyr:::tbl_if_vars()`, use `pull()` instead of base column indexing

- R/generics.R
Part of #4873 
This benefits all joins, plus any function that calls `dplyr_reconstruct()` with a data frame.
As shown in https://github.com/tidyverse/dplyr/issues/4873#issuecomment-590067757, `attributes()<-` materializes compact row names (which is rather unfortunate).
`new_data_frame()` does not, which makes it much cheaper. It doesn't allow `!!!` in the `...` right now, but maybe we should consider that.
Note both the time and memory in the benchmarks below.
``` r
library(bench)
set.seed(342)
df1 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE))
df2 <- tibble(y = rnorm(1e3), a = sample(1:10, 1e3, replace = TRUE))
df3 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE), b = sample(1:5, 1e5, replace = TRUE))
df4 <- …
```
> Use `new_data_frame()` in `dplyr_reconstruct()` to avoid materializing row names

- R/arrange.R
- R/conditions.R
- tests/testthat/test-arrange-errors.txt
- tests/testthat/test-arrange.r
``` r
tibble(x = 1, x = 2, .name_repair = "minimal") %>% arrange(x) 
#> Error: arrange() failed at implicit mutate() step. 
#> x Can't bind data because some arguments have the same name
tibble(x = 1) %>% arrange(y)
#> Error: arrange() failed at implicit mutate() step. 
#> ℹ Could not create a temporary column with `..1`.
#> ℹ `..1` is `y`.
tibble(x = 1) %>% arrange(c(x, x))
#> Error: arrange() failed at implicit mutate() step. 
#> ℹ Could not create a temporary column with `..1`.
#> ℹ `..1` is `c(x, x)`.
```
<sup>Created on 2020-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
> tweaks to arrange() errors

- R/join-rows.R
- R/join.r
Part of #4873 
I realized that right and full joins could also take advantage of avoiding `c()` calls in the cases where they don't have any extra `y` rows. I'm not sure how common this is in practice, but it was the case in the two examples.
I mainly like that it again encapsulates the use of `type` to be purely in `join_rows()`.
``` r
library(bench)
set.seed(342)
df1 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE))
df2 <- tibble(y = rnorm(1e3), a = sample(1:10, 1e3, replace = TRUE))
df3 <- tibble(x = rnorm(1e5), a = sample(1:10, 1e5, replace = TRUE), b = sample(1:5, 1e5, replace = TRUE))
df4 <- tibble(y = rnorm(1e3), a = sample(1:10, 1e3, replace = TRUE), b = sample(1:5, 1e3, replace = TRUE))
```
```r
bench::mark(
right_join(df1, …
```
> Generalize avoidance of `c()` calls to right and full joins

- R/data-mask.R
- tests/testthat/test-mutate.r
Broke {d3r} and likely {ushr}
Previously:
```r
library(vctrs)
df <- new_data_frame(n = 5L)
colnames(df) <- NULL
mutate(df, x = 4)
#> Error in chr_unserialise_unicode(names(data)): is_character(chr) is not TRUE
```
Now:
``` r
library(vctrs)
df <- new_data_frame(n = 5L)
colnames(df) <- NULL
mutate(df, x = 4)
#>   x
#> 1 4
#> 2 4
#> 3 4
#> 4 4
#> 5 4
```
<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Use `names2()` to guard against `NULL` column names

- R/data-mask.R
- tests/testthat/test-mutate.r
Closes #4893 
When the column to be updated exists in the data already, but is not actually used in the expression that does the updating, then it does not currently get marked as `used`. This means that further usage of that column refers to the old version before it was updated. This PR fixes that.
> Fix sequential updating

- R/rowwise.r
`nrow` is a required argument to `new_tibble()`. This is only working in the dev version of tibble because it warns (once) if you don't provide it and them computes it anyways
> Pass on the number of rows to `new_tibble()`

- R/data-mask.R
``` r
library(dplyr)
r_iris <- rowwise(iris)
bench::mark(
mutate(r_iris, x = across(Sepal.Width)),
iterations = 50
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                                min median `itr/sec` mem_alloc
#>   <bch:expr>                              <bch> <bch:>     <dbl> <bch:byt>
#> 1 mutate(r_iris, x = across(Sepal.Width)) 276ms  318ms      3.09     3.4MB
#> # … with 1 more variable: `gc/sec` <dbl>
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                                min median `itr/sec` mem_alloc
#>   <bch:expr>                              <bch> <bch:>     <dbl> <bch:byt>
#> 1 mutate(r_iris, x = …
```
> Use `new_tibble()` in `$pick()` for faster construction

- R/data-mask.R
This simplifies `$pick()` further by using `env_get_list()`. This is also slightly faster, but I'm mainly interested in how it simplifies the code
I don't think there is any reason we need to use the mask vs what I do here with the bindings
``` r
library(rlang)
env <- environment()
env$x <- 1
env$y <- 2
mask <- new_data_mask(env)
mask$.data <- as_data_pronoun(mask)
vars <- c("x", "y")
bench::mark(
eval_tidy = {
cols <- eval_tidy(expr(list(!!!syms(vars))), mask)
names(cols) <- vars
cols
},
get_list = env_get_list(env, vars),
iterations = 100000
)
#> # A tibble: 2 x 6
#> 1 eval_tidy   10.74µs  12.73µs    74228.    38.7KB     84.7
#> 2 get_list     7.51µs   8.46µs …
```
> Swap `eval_tidy()` for `env_get_list()`

- R/across.R
- R/context.R
- R/data-mask.R
- tests/testthat/test-across.R
- tests/testthat/test-context.R
Closes #4907 
This PR fixes both `across()` and `cur_data()` when used in sequential expressions.
This was actually incredibly hard to get right. This is complicated by the fact that we don't want to resolve "unused" columns, which would mark them as "used", but we still have to check their types in `eval_select()` if something like `across(is.numeric)` is called.
The idea here is to separate the non-group columns that are currently present in the data into two groups. The first group are unused columns, which we pull from the original data. The second are used columns, which we pull from the current bindings.
The good news is that, even though this is more expensive, it is part of the "set up" work that gets cached in #4909. I'll rework that PR on top of this
> Fix `across()` and `cur_data()` to work sequentially

- R/across.R
- R/condense.r
- R/data-mask.R
- R/mutate.R
- R/summarise.R
- tests/testthat/test-across.R
This PR implements a caching system for the results of `eval_select()` when called from `across()`. The same cache could be used for `c_across()`.
The cache is a named list. The names are the deparsed expressions that a user provides when calling `across()`. The values are the results of `eval_select()`.
For any verbs that evaluate multiple expressions in a loop, the cache is reset between expressions (`mutate()`, `summarise()`, `condense()`). This should allow a `across(is.numeric)` call in one expression to be different from an `across(is.numeric)` call in another expression, but right now #4907 keeps that from working. This "reset" could move to the C code if it seems out of place.
``` r
iris2 <- bind_rows(!!!rep_len(list(iris), 10))
rowwise_iris2 …
```
> Cache `eval_select()` results in `across()` on a per expression basis

- NEWS.md
to NEWS.
I'm aware of the "Lifecycle changes" section. The new text highlights behavior changes that break tests that worked in dplyr 0.8.4.
> Add section on breaking changes

- DESCRIPTION
- src/imports.cpp
Surprisingly tests pass fine even without this change, but this is more correct.
This is a minimal change, eventually we can use the fact that the 3 vctrs functions used here are actually in a public header file provided by vctrs, rather than calling `R_GetCCallable()`
> Remove `struct vctrs_arg*` argument from `short_vec_recycle()`

- R/deprec-dbi.R
Just happened to find these. Followup of #4941
> Fix deprecated function names in src_mysql() and src_postgres()

- R/join-rows.R
Closes #4964 
Also related to #4873, particularly https://github.com/tidyverse/dplyr/issues/4873#issuecomment-590232679
Unfortunately `vec_c()` is currently much slower than `unlist()`. It is much safer though, so I'm not sure we will ever be able to fully match the speed of `unlist()`. I'm sure we can make improvements in some way though.
Until then, I think we might have to fall back to `unlist()` in `join_rows()`. It should be safe, as `y_loc` is always a list of integers.
``` r
library(bench)
data_size <- 1000000
left_df <- tibble(
a = sample(1:7, data_size, TRUE),
b = sample(c("a","a","b","c","d"), data_size, TRUE)
)
right_df1 <- tibble(
b = c("a","b","c","d"),
c = 1:4
)
right_df2 <- tibble(
b = c("a","b","c"),
c = 1:3
)
```
```r
bench::mark( …
```
> Use `unlist()` in `join_rows()` until `vec_c()` performance improves

- R/join-rows.R
For left and full joins, we can often avoid a `vec_assign()` call if all rows in `x` have a match in `y`. This helps performance in these cases.
These benchmarks are on top of #4975 
``` r
library(bench)
data_size <- 1000000
left_df <- tibble(
a = sample(1:7, data_size, TRUE),
b = sample(c("a","a","b","c","d"), data_size, TRUE)
)
right_df <- tibble(
b = c("a","b","c", "d"),
c = 1:4
)
bench::mark(
left_join = left_join(left_df, right_df, by = "b"),
check = FALSE,
iterations = 100
)
#> # A tibble: 1 x 6
#> 1 left_join    46.2ms   50.5ms      19.2    58.5MB     158.
#> Warning: Some expressions had a GC in every iteration; so …
```
> Avoid `vec_assign()` call when all rows match

- R/across.R
- tests/testthat/test-across.R
Closes #4967 
Part of #4953 
A chunk of the time in `across()` comes from compat-`pmap()` applying checks that we don't need here (like arg recycling).
Also, using `expand.grid()` is probably more work than we need to do vs using a double loop. I think that the use of `expand.grid()` was also the cause of #4967, because it varies the first input fastest (the columns).
```r
n_cols <- 5
n_rows <- 400
split <- 4
df <- tibble(
g1 = rep(seq_len(n_rows / split), each = split),
g2 = rep(seq_len(split), times = n_rows / split),
x1 = rnorm(n_rows),
x2 = rnorm(n_rows),
x3 = rnorm(n_rows),
x4 = rnorm(n_rows),
x5 = rnorm(n_rows)
)
gdf <- group_by(df, g1, g2)
bench::mark(
summarize(gdf, across(is.numeric, diff)),
summarize_if(gdf, is.numeric, diff),
iterations = …
```
> Use a double loop to apply functions in `across()`

- R/mutate.R
- tests/testthat/test-mutate.r
This was breaking `ggperiodic` on revdep checks. 
``` r
df <- tibble(x = structure(1, class = "foo"))
arrange(df, x)
#> Error: arrange() failed at implicit mutate() step. 
#> ℹ Could not create a temporary column for `..1`.
#> ℹ `..1` is `x`.
```
<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
with this pr: 
``` r
df <- tibble(x = structure(1, class = "foo"))
arrange(df, x)
#>       x
#>   <dbl>
#> 1     1
```
<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
We can later revisit as part of hybrid 2.0 but for now this just avoids the chop/unchop 💃
> mutate() skips chop/unchop with symbol expressions

- R/across.R
- R/select.R
- man/across.Rd
- man/select.Rd
- tests/testthat/test-across-errors.txt
- tests/testthat/test-across.R
- tests/testthat/test-arrange.r
- vignettes/colwise.Rmd
- vignettes/programming.Rmd
Closes #4965.
- Prefixed argument names with dots to avoid argument name collisions with `...` args.
- Moved `.names` after `...` so that ellipsis gets passed directly after `.fns` for consistency with other functionals.
I think I managed to get all of the arguments sorted in the callers, too. I grepped for `across\(.*(?<!\.)(cols|fns|names) *=` without anything more coming up.
> Prefix across() args with dots and pass ellipsis after .fns

- R/data-mask.R
- src/dplyr.h
- src/mutate.cpp
- tests/testthat/test-mutate.r
closes #4974
`which_used` is maintained so that the internal loop in this macro is performant: 
```c
#define DPLYR_MASK_SET_GROUP(INDEX)                                                  \
*p_current_group = INDEX + 1;                                                        \
SEXP resolved = Rf_findVarInFrame(env_private, dplyr::symbols::resolved);            \
SEXP which_used = Rf_findVarInFrame(env_private, dplyr::symbols::which_used);        \
int* p_which_used = INTEGER(which_used);                                             \
SEXP names_resolved = Rf_getAttrib(resolved, R_NamesSymbol);                         \
R_xlen_t n_resolved = XLENGTH(which_used);                                           \
for (R_xlen_t i_resolved = 0; i_resolved < n_resolved; i_resolved++) {               \ …
```
> recalculate which_used on removes.

- DESCRIPTION
- tests/testthat/test-bind.R
Closes #4931 
- Adds a test for `bind_rows()` with named factors
- We now have to rely on dev rlang again to get the fix to `!!!`
> Add regression test for `bind_rows()` and named S3 objects

- R/across.R
- R/context.R
- R/data-mask.R
- tests/testthat/test-across.R
part of #4953 
This follows up @DavisVaughan work on caching things `across()` uses, and now also caches: 
- the function list
- the names of the outputs (calling `glue::glue()` repeatedly was expensive)
before: 
with this: 
I believe more can be done without yet challenging evaluation: 
- `across_apply()` and particularly `local_column()` seem to be taking time: 
- `as_tibble()` too: 
I'd like to keep investigating in that direction because it benefits all uses of `across()` 
Then, perhaps we can preemptively recognize `across()` calls and handle it differently, e.g. we might not need to generate tibbles for chunks, ... but this starts to look more like hybrid evaluation, so I'd like to investigate how far we can go without doing this just yet.
> cache more in across_setup()

- R/bind.r
- tests/testthat/test-bind.R
Closes #4930
This looks to be different from #4931 
`vec_is_list()` is a new function in the CRAN version of vctrs for detecting a "list" in the vctrs sense. It returns TRUE if:
- x is a bare list with no class.
- x is a list explicitly inheriting from "list" or "vctrs_list_of".
- x is an S3 list that vec_is() returns TRUE for. For this to return TRUE, the class must implement a vec_proxy() method.
It requires a tweak to a test related to https://github.com/tidyverse/dplyr/issues/3924, but this was one of my own issues, so it is probably fine? It is technically a breaking change though.
> Use `vec_is_list()` in `bind_cols()` and `bind_rows()`

- DESCRIPTION
- R/bind.r
- tests/testthat/test-bind.R
``` r
bind_cols(data.frame(x = 1), y = 2)
#>   x y
#> 1 1 2
bind_cols(tibble(x = 1), y = 2)
#> # A tibble: 1 x 2
#>       x     y
#> * <dbl> <dbl>
#> 1     1     2
bind_cols(x = 1, y = 2)
#> # A tibble: 1 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
```
<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> bind_cols(<...>) -> tibble

- R/distinct.R
- tests/testthat/test-n_distinct.R
``` r
data.frame(x = 42) %>%
summarise(n = n_distinct(.data$x))
#>   n
#> 1 1
```
<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> protect against tibble() .data masking in older versions of tibble::

- R/grouped-df.r
- man/grouped_df.Rd
I've checked and this does not seem to harm https://github.com/tidyverse/tidyr/pull/914
> grouped_df(drop=) defaults to use group_by_drop_default(data)

- R/grouped-df.r
- tests/testthat/test-grouped-df.r
Closes #5040
This PR maintains the grouping order in the grouped_df methods we have overwritten. We just needed to flip the order in an `intersect()` call, which I have extracted out into `group_intersect()`
> Maintain grouping order in grouped_df methods

- R/join-rows.R
- tests/testthat/test-join-rows.R
- tests/testthat/test-join-rows.txt
``` r
dplyr:::join_rows(
data.frame(x = 1),
data.frame(x = factor("a"))
)
#> Error: Can't join on `x$x` x `y$x` because of incompatible types. 
#> ℹ `x$x` is of type <double>>.
#> ℹ `y$x` is of type <factor<127a2>>>.
full_join(
tibble(A=factor(1:3), B=LETTERS[1:3]),
tibble(A=1:3, C=letters[1:3])
)
#> Joining, by = "A"
#> Error: Can't join on `x$A` x `y$A` because of incompatible types. 
#> ℹ `x$A` is of type <factor<d3bfc>>>.
#> ℹ `y$A` is of type <integer>>.
```
<sup>Created on 2020-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Or, wondering if `vctrs::vec_match()` should expose arguments `x_arg` and `y_arg` like `vec_ptype2()` does
> join_rows() giving meaningful error message

- vignettes/colwise.Rmd
- vignettes/rowwise.Rmd
- Simplify first two examples in rowwise vignette
- Reorder two sections in rowwise vignette to increase complexity as you read down
- Minor grammatical edits / typos
I've also opened #4992, which needs to be addressed in the rowwise vignette.
And finally, I think the Gotchas section in the colwise vignette is still a bit confusing. I think it would be nice to add a "because ..." at the end of "Here `n` becomes `NA` because the standard deviation of 3 is `NA`", something along the lines of "because dplyr first does ... and then does ...", but I wasn't sure about the precise language for what's happening under the hood.
> Edits to rowwise and colwise vignettes

- R/lead-lag.R
- tests/testthat/test-lead-lag.R
close #5028
``` r
m       <- matrix(1:120, ncol = 12)
lag(m, 1L)
#>       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
#>  [1,]   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA    NA    NA
#>  [2,]    1   11   21   31   41   51   61   71   81    91   101   111
#>  [3,]    2   12   22   32   42   52   62   72   82    92   102   112
#>  [4,]    3   13   23   33   43   53   63   73   83    93   103   113
#>  [5,]    4   14   24   34   44   54   64   74   84    94   104   114
#>  [6,]    5   15   25   35   45   55   65   75   85    95   105   115
#>  [7,]    6   16   26   36   46   56   66   76   86    96   106   116
#>  [8,]    7   17   27   37   47   57   67   77   87    97   107   117
#>  [9,]    8   18   28   38   48   58   68 …
```
> use vec_sze() instead of length() in lead() and lag()

- R/colwise.R
- tests/testthat/test-colwise-select-errors.txt
- tests/testthat/test-colwise-select.R
When predicate function return type was wrong, error messages were somehow unclear about what went wrong:
`
select_if(iris, ~c(is.numeric(.x),is.numeric(.x)))
`
> more elements supplied than there are to replace
`select_if(iris, ~mean(.x))`
> Only strings can be converted to symbols
This short pull request adds the error message `abort("Provided predicate function did not return a single logical")` after checking that the result of the predicate function is a single logical value. 
Also fixed a typo in the first `abort` call of the function (swapped `(` and `}`).
> Check return type of predicate in tbl_if_vars

- R/group-by.r
- tests/testthat/test-group-by.r
close #4984
``` r
tibble(a = 1, b = 2) %>%
group_by(c = a * b, d = c + 1)
#> # A tibble: 1 x 4
#> # Groups:   c, d [1]
#>       a     b     c     d
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     2     2     3
```
<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Do we want to tailer the errors that occur during the `mutate()` step ? Perhaps in a different PR. 
``` r
tibble(a = 1, b = 2) %>%
group_by(c = a * b, d = e + 1)
#> Error: `mutate()` argument `d` errored.
#> ℹ `d` is `e + 1`.
#> x object 'e' not found
tibble(a = 1, b = 2) %>%
distinct(c = a * b, d = e + 1)
#> Error: `mutate()` argument `d` errored.
#> ℹ `d` is `e + 1`.
#> x object 'e' not found
```
<sup>Created on 2020-03-27 by the [reprex …
> group_by() with mutate() semantics

- tests/testthat/test-distinct.R
- tests/testthat/test-filter.r
- tests/testthat/test-join.r
- tests/testthat/test-mutate.r
Fixes tests once r-lib/vctrs#951 is merged.
> Don't count regroups in tests

- R/across.R
- man/across.Rd
Reverts a small piece of #4979 that prefixed the `cols` argument of `c_across()` with a `.`. I don't think we need that
> Don't `.` prefix `cols` in `c_across()`

- R/distinct.R
- tests/testthat/test-n_distinct.R
closes #5069
``` r
dplyr::n_distinct(iris$Sepal.Length, iris$Sepal.Width)
#> [1] 117
```
<sup>Created on 2020-03-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> N distinct eval tidy

- NEWS.md
- R/lead-lag.R
- tests/testthat/test-lead-lag-errors.txt
- tests/testthat/test-lead-lag.R
close #5073
``` r
lag(c("1", "2", "3"), default = FALSE)
#> Error: Incompatible type for `default`.
#> ℹ <logical> cannot be cast to type <character>.
```
<sup>Created on 2020-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> specific error for (lag|lead)(default=) when incompatible type.

- R/summarise.R
- src/dplyr.h
- src/init.cpp
- src/summarise.cpp
- tests/testthat/test-summarise.r
``` r
df <- tibble(g1 = factor(letters[1:10]), g2 = factor(letters[1:10]))
df %>%
group_by(g1, g2) %>% 
summarise(across(is.factor, nlevels))
#> # A tibble: 10 x 2
#> # Groups:   g1 [10]
#>    g1    g2   
#>    <fct> <fct>
#>  1 a     a    
#>  2 b     b    
#>  3 c     c    
#>  4 d     d    
#>  5 e     e    
#>  6 f     f    
#>  7 g     g    
#>  8 h     h    
#>  9 i     i    
#> 10 j     j
```
<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
initial example in #5084: 
``` r
df <- tibble(g1 = factor(letters[1:10]),
g2 = factor(LETTERS[1:10]),
a  = runif(10, 1, 10),
b  = runif(10, 10, 20),
c  = runif(10, 15, 30),
d  = runif(10, 1, 50))
df %>%
group_by(g1, g2) …
```
> ignore data frames with 0 columns as results in summarise()

- R/bind.r
- tests/testthat/test-bind.R
close #5087 I'll add a test if we decide to merge this
``` r
library(dplyr, warn.conflicts = FALSE, quietly = TRUE)
bind_rows(list(a = tibble(x = 1:2))) %>% row.names()
#> [1] "1" "2"
```
<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>Session info</summary>
``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz …
```
> bind_rows(.id = NULL) does not set names.

- vignettes/colwise.Rmd
- vignettes/rowwise.Rmd
- Rename colwise and rowwise vignettes as discussed in #5103 
- Update references to these actions in prose to read "column-wise" and "row-wise" to match titles
> Vignette rename: row-wise and col-wise

- vignettes/dplyr.Rmd
A few minor formatting edits on the dplyr vignette that shows up on the main pkgdown page
- Some inline function names were not formatted as code, those are now fixed
- A few places with two spaces after a period, now using only single space
- Inconsistency between code chunks re: single/multi-line pipe formatting is now made consistent -- no line break if `%>%` used only once
> Minor formatting edits on dplyr vignette

- DESCRIPTION
- R/summarise.R
```r
data.frame(x = 1:10, y = 1:10) %>%
summarise(z = mean(x))
```
The expression is `mean(x)`. 
This creates this function, with a special `hybrid_functions` as parent env: 
```r
fn <- function(x = mask$resolve("x"), y = mask$resolve("y")) mean(x)
```
which then eventually calls `hybrid_functions:::mean` : 
```r
mean = function(x, ...) {
call <- match.call()
mask <- peek_mask()
vars <- mask$current_vars()
stopifnot(is_symbol(call$x) && as_string(call$x) %in% vars)
if (identical(names(call), c("", "x"))) {
grouped_mean(x, na.rm = TRUE)
} else if(identical(names(call), c("", "x", "na.rm"))) {
na.rm <- call$na.rm
stopifnot(is_scalar_logical(na.rm))
grouped_mean(x, na.rm = na.rm)
}
}
```
that only ends up evaluating the `mask$resolve("x")` promise once actually calling `grouped_mean()`. 
`n` …
> lean more to evaluation

- R/generics.R
- tests/testthat/test-generics.R
Closes #5158 
This drastically simplifies `dplyr_reconstruct.data.frame()` by taking an approach similar to `dplyr_col_modify.data.frame()`, which just restores the attributes directly.
I've also pulled over the tests from #5158, but I think the attributes one might have been backwards. I think we care about keeping the attributes from `template`, not `data`.
The job of the data frame method of `dplyr_reconstruct()` is now very simple and well defined. It keeps all attributes of `template` except:
- `names` in case columns were modified
- `row.names` in case rows were modified
There was some code about the `.drop` attribute in the old `dplyr_reconstruct.data.frame()`, but I don't think it belonged there because we have a `grouped_df` method as well. It also wouldn't have worked right …
> Simplify `dplyr_reconstruct()`

- R/group_split.R
- tests/testthat/helper-s3.R
- tests/testthat/test-group_split.R
Closes #5165 
`group_split()` has been refactored to accomplish a few goals:
- It now uses `dplyr_row_slice()` to split with. Previously this was `vec_slice()`.
- There was a case where we used `[, i]` rather than 1D `[i]` when `keep = FALSE`. This has been fixed.
- group-splitting a rowwise data frame used to return a list-of rowwise data frames. I believe this is inconsistent, and it should just return a list of tibbles, like with grouped-dfs. The change has been made to make this more consistent.
- Methods for `data.frame`, `grouped_df`, and `rowwise_df` all now share the same implementation
@earowang, this makes `group_split(pedestrian, Sensor)` work since you have a `dplyr_row_slice()` method. You will still need a `group_split.grouped_ts()` method. It should just have to call …
> Refactor `group_split()` to use `dplyr_row_slice()`

- R/group_split.R
- tests/testthat/helper-s3.R
- tests/testthat/test-group_map.R
- tests/testthat/test-group_split.R
Follow up to #5167 
I have since realized that `group_split()` can be implemented in such a way that tsibble likely won't need to supply any methods for it.
The key was to switch a usage of `as_tibble()` for `ungroup()` in `group_split.grouped_df()`. Ungrouping is generic, so when a `grouped_ts` is ungrouped, it can correctly be dropped down to a `tbl_ts`. The previous usage of `as_tibble()` was incorrectly forcing this to be a bare tibble.
So now if tibble subclasses does both of these things, then `group_split()` works out of the box.
- Implement a `group_by.<tbl_subcls>()` method that returns a `<grouped_subcls>`
- Implement a `ungroup.<grouped_subcls>()` method that returns a `<tbl_subcls>`
tsibble does both of these.
---
This also unifies the code a bit more. We still can't make …
> Simplify `group_split()` using `ungroup()`, not `as_tibble()`

- R/lead-lag.R
- tests/testthat/test-lead-lag-errors.txt
closes https://github.com/bergsmat/wrangle/pull/1
this does fix `nonmemica`
I'm not sure this should also `vec_cast(x)` ?
> lead(), lag(): cast default to common type rather than to type of x.

- R/across.R
- R/context.R
- tests/testthat/test-across-errors.txt
- tests/testthat/test-across.R
closes #5180
``` r
across()
#> Error: across() must only be used inside dplyr verbs
c_across()
#> Error: c_across() must only be used inside dplyr verbs
```
<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> across() and c_across() when used out of dplyr context

- DESCRIPTION
- R/across.R
simplified `c_across()` thanks to https://github.com/r-lib/vctrs/pull/1091
> vec_c(.name_spec = zap())

- R/arrange.R
- tests/testthat/test-arrange.r
I think that for consistency, `arrange.data.frame()` should always call `dplyr_row_slice()` even if there are no `...`.
I have a `dplyr_row_slice()` method that unconditionally removes the tibble subclass. If `arrange()` doesn't always call `dplyr_row_slice()`, then `arrange(<subtbl>)` vs `arrange(<subtbl>, col)` give inconsistently classed results
It is a sufficiently rare edge case that I don't think the performance cost of doing a row slice matters much here.
> Ensure that `arrange()` always calls `dplyr_row_slice()`

- R/count-tally.R
- R/summarise.R
- tests/testthat/test-bind-errors.txt
- tests/testthat/test-count-tally.r
summarise() implementations might not know about `.groups=` yet. 
closes #5200
``` r
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, mtcars)
DBI::dbListTables(con)
#> [1] "mtcars"       "sqlite_stat1" "sqlite_stat4"
con %>% 
tbl("mtcars") %>% 
count()
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.30.1 [:memory:]
#>       n
#>   <int>
#> 1    32
```
<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> tally() not using .groups= 

- R/conditions.R
- R/filter.R
- R/mutate.R
- R/summarise.R
that can be used when rethrowing e.g. a vctrs error
> stop_dplyr() gains a parent=

- DESCRIPTION
- R/doc-params.R
- R/relocate.R
- R/select.R
- man/dplyr_data_masking.Rd
- man/dplyr_tidy_select.Rd
- man/relocate.Rd
- man/rmd/overview.Rmd
- man/rmd/setup.Rmd
- man/select.Rd
- tests/testthat/test-across-errors.txt
- tests/testthat/test-across.R
- tests/testthat/test-mutate.r
- tests/testthat/test-relocate.R
* Import upstream documentation.
* Switch to `where()`.
> Update tidyselect docs

- R/across.R
- tests/testthat/test-across.R
closes #5204
``` r
as_tibble(iris) %>% 
mutate(across(where(is.character), as.factor))
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9          1.7         0.4 setosa 
#>  7          4.6         3.4          1.4         0.3 setosa 
#>  8          5           3.4          1.5         0.2 setosa 
#>  9 …
```
> across(<empty>) -> data frame with 0 columns and 1 row.

- R/slice.R
- tests/testthat/test-slice.r
closes #5233
``` r
df <- data.frame(x = 1:10)
df %>% slice_head(prop = 0.11) 
#>   x
#> 1 1
df %>% slice_tail(prop = 0.10) 
#>    x
#> 1 10
df %>% slice_tail(prop = runif(1))
#>    x
#> 1  6
#> 2  7
#> 3  8
#> 4  9
#> 5 10
df %>% slice_tail(prop = 0.11)
#>    x
#> 1 10
```
<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> round down proportions on slice_tail()

- .github/workflows/R-CMD-check.yaml
- R/data-mask.R
- tests/testthat/helper-encoding.R
- tests/testthat/test-colwise-mutate.R
- tests/testthat/test-group-by.r
- tests/testthat/test-mutate.r
Alternative to #5231. withr does have support for locale change, so I used that + some probing for a non-UTF-8 locale.
> Refactor encoding test helpers and use withr::local_locale()

- NEWS.md
- vignettes/two-table.Rmd
Related to #4856
- add change in behaviour to NEWS.md
- small update to vignette "Two-table verbs"
I know some people who rely on `dplyr::right_join()` for sorting the LHS table according to the order of values in the RHS table, so maybe this could be helpful.
> Document changed behaviour of 'right_join()'

- R/across.R
- R/colwise-distinct.R
- R/colwise-filter.R
- R/colwise-group-by.R
- R/colwise-mutate.R
- R/colwise-select.R
- man/across.Rd
- man/distinct_all.Rd
- man/filter_all.Rd
- man/group_by_all.Rd
- man/mutate_all.Rd
- man/select_all.Rd
- man/summarise_all.Rd
- vignettes/base.Rmd
- vignettes/colwise.Rmd
- vignettes/programming.Rmd
- vignettes/rowwise.Rmd
Checked with a version of tidyselect where the warning is promoted to error.
Closes #5258.
> Use `where()` in remaining documentation

- R/data-starwars.R
- man/starwars.Rd
- vignettes/dplyr.Rmd
This does not yet adress #3983 so the links in `data-raw/starwars.R` are still `.co` links. 
But this adresses this during `devtools::check(remote = TRUE, manual = TRUE)`
```
Found the following (possibly) invalid URLs:
URL: http://swapi.co (moved to https://swapi.co/)
From: inst/doc/dplyr.html
Status: 404
Message: Not Found
URL: http://swapi.co/ (moved to https://swapi.co/)
From: man/starwars.Rd
Status: 404
Message: Not Found
```
> swapi.co -> swapi.dev

- R/generics.R
- R/grouped-df.r
- R/rowwise.r
- R/utils.r
- tests/testthat/helper-s3.R
- tests/testthat/test-generics.R
And ensure `dplyr_reconstruct()` methods are consistently passed a data frame.
I've checked all packages implementing `dplyr_reconstruct()` (fabletools, tsibble, rsample, and dials) and this doesn't cause any issue.
> Return data frame from `vec_data()`

- R/generics.R
- R/utils.r
- tests/testthat/test-generics.R
Makes it easier to implement methods and prevents unexpected leaking of irrelevant attributes.
> Strip attributes before reconstruction

- DESCRIPTION
- NEWS.md
- src/funs.cpp
- tests/testthat/test-window.R
Indexing off by one, causing first index to be repeated twice (and last index to be dropped). My intuition is we must keep *p_out and *p_x synced, so need to increment both on line 108. 
Example given:
x <- 1:5
Expected: 1.0 1.5 2.0 2.5 3.0
Actual:  1.000000 1.000000 1.333333 1.750000 2.200000
PR output: 1.0 1.5 2.0 2.5 3.0
Tested locally using Rcpp. Feedback welcome.
> Update indexing for dplyr_cummean (#5287)

- NEWS.md
- R/coalesce.R
- man/coalesce.Rd
- tests/testthat/test-coalesce.R
Closes #5326.
```r
df1 <- data.frame(x = c(NA, 1, NA), y = c(2, NA, NA), z = c(1:2, NA))
df2 <- tibble::tibble(x = 1:3, y = c(3, 4, NA), z = c(NA, NA, NA))
df3 <- data.frame(x = NA, y = c(30, 40, 50), z = 101:103)
df1
#>    x  y  z
#> 1 NA  2  1
#> 2  1 NA  2
#> 3 NA NA NA
df2
#>       x     y z
#>   <int> <dbl> <lgl>
#> 1     1     3 NA
#> 2     2     4 NA
#> 3     3    NA NA
df3
#>    x  y   z
#> 1 NA 30 101
#> 2 NA 40 102
#> 3 NA 50 103
coalesce(df1, df2, df3)
#>       x     y     z
#>   <dbl> <dbl> <int>
#> 1     1     2     1
#> 2     1     4     2
#> 3     3    50   103
```
> Support data frames in `coalesce()`

- R/slice.R
- man/slice.Rd
Sorry if this is very pernickety, but there was a space missing after a `#` in the `slice` examples and it would bug me if it were my package.
> add a space after # in comment

- R/mutate.R
- tests/testthat/test-group-by.r
closes #5316
``` r
df <- data.frame(x = c(1, 2))
df %>% summarise(across(NULL))
#> data frame with 0 columns and 1 row
df %>% mutate(across(NULL))
#>   x
#> 1 1
#> 2 2
df %>% group_by(across(NULL))
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2     2
names(list())
#> NULL
```
<sup>Created on 2020-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
> across(NULL) and across(character()) no-op

- R/conditions.R
- R/mutate.R
Handling warnings like errors, and adding some information about when the warning occurred gives: 
``` r
foo_warn <- function(x, sym){
if(any(x > 3)){
warning(paste(sym, "has an implausible value"))
}
x
}
iris %>% 
mutate(
across(contains("Sepal"), ~foo_warn(.x, cur_column()))
) %>% 
head()
#> Warning: Problem with `mutate()` input `..1`.
#> x Sepal.Length has an implausible value
#> ℹ Input `..1` is `across(contains("Sepal"), ~foo_warn(.x, cur_column()))`.
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> …
```
> add context to warning in mutate()

- R/bind.r
- tests/testthat/test-bind.R
part of #5370  but would probably need more help from `vctrs` (probably https://github.com/r-lib/vctrs/issues/1169).
> prefer vctrs::new_data_frame() over tibble(!!!)

- DESCRIPTION
- R/arrange.R
Follow up to https://github.com/r-lib/vctrs/pull/1155 which removes the experimental `relax` argument in favor of `vec_proxy_order()`
We get errors without this since `ellipsis::check_dots_empty()` is run on the vctrs side, and having the `relax` arg is an issue. Using `vec_proxy_order()` is also now the way to order list-columns.
Note that this bumps dplyr to use dev vctrs
> Use `vec_proxy_order()` in place of `vec_proxy_compare(relax = TRUE)`

- R/doc-params.R
- R/mutate.R
- man/dplyr_tidy_select.Rd
- man/mutate.Rd
- vignettes/dplyr.Rmd
Fix #5392 
Btw, it seems dplyr still uses roxygen 7.1.0. I think you should use 7.1.1 before the next CRAN submission to avoid crossref warnings on R-devel.
> Use ! instead of - to negate the selection in docs

- DESCRIPTION
- R/data-mask.R
- tests/testthat/test-arrange-errors.txt
- tests/testthat/test-summarise-errors.txt
- tests/testthat/test-summarise.r
Fixes the error message failure on CI. Binding functions in rlang no longer fail when there are duplicate bindings.
I took this opportunity to bump the rlang dep.
> Fix error message when data frame contains duplicated names

- R/arrange.R
- R/zzz.r
In the end the next version of vctrs will not include the order proxy. So we detect it from the formal signature of `vec_proxy_compare()` instead of the vctrs version. Edit: Now detecting presence of `vec_proxy_order()` in the vctrs namespace.
> Improve detection of modern order proxy

- R/context.R
- R/data-mask.R
- R/filter.R
- R/mutate.R
- R/slice.R
- R/summarise.R
- src/dplyr.h
- tests/testthat/test-mutate-errors.txt
- tests/testthat/test-mutate.r
Related to #5388
``` r
library(ggplot2)
plot_this <- function(.data, x, y, label) {
ggplot() +
geom_point(data = .data, aes(mpg, hp)) +
geom_point(aes(x = {{ x }}, y = {{ y }}), color = "red", size = 4) +
geom_text(aes(x = {{ x }}, y = {{ y }}, label = {{ label }}), color = "white", fontface = "bold")
}
df <- tibble(
data = list(mtcars),
x = c(16, 18, 19),
y = c(80, 90, 100)
) %>% 
tibble::rowid_to_column()
df
#> # A tibble: 3 x 4
#>   rowid data                    x     y
#>   <int> <list>              <dbl> <dbl>
#> 1     1 <df[,11] [32 × 11]>    16    80
#> 2     2 <df[,11] [32 × 11]>    18    90
#> 3     3 <df[,11] [32 × 11]>    19   100
plots <- df %>% 
rowwise() %>% 
mutate(
plot = plot_this(data, x, y, rowid) %>% list(), 
.keep = "unused"
) …
```
> attempt to protect against late use of DataMask objects.

- src/group_by.cpp
Dealing with: https://www.stats.ox.ac.uk/pub/bdr/memtests/valgrind/dplyr/tests/testthat.Rout
rhub::check_with_valgrind(): https://builder.r-hub.io/status/dplyr_1.0.1.tar.gz-0eeefce6aa944aeeb5cc6b6d5af15b32
> avoid look past std::vector, as identified by cran valgrind

- R/across.R
- man/across.Rd
- tests/testthat/test-across.R
- vignettes/colwise.Rmd
- vignettes/programming.Rmd
https://stackoverflow.com/questions/63151985/how-to-glue-a-function-argument-to-names-in-dplyrs-across-function
``` r
library(palmerpenguins)
mean_by <- function(data, by, var, prefix = "avg") {
data %>% 
group_by({{ by }}) %>% 
summarise(across({{ var }}, mean, .names = "{prefix}_{col}"))
}
penguins %>% 
mean_by(species, starts_with("bill"))
#> `summarise()` ungrouping output (override with `.groups` argument)
#>   species   avg_bill_length_mm avg_bill_depth_mm
#>   <fct>                  <dbl>             <dbl>
#> 1 Adelie                  NA                NA  
#> 2 Chinstrap               48.8              18.4
#> 3 Gentoo                  NA                NA
```
<sup>Created on 2020-07-31 by the [reprex …
> allow local variables in across(.names=)

- R/group-by.r
- man/group_by.Rd
Current example on `group_by()`'s help page doesn't actually show usage of the empty group. I guess `.drop = FALSE` is intended here.
``` r
tbl <- tibble(
x = 1:10,
y = factor(rep(c("a", "c"), each  = 5), levels = c("a", "b", "c"))
)
tbl %>%
group_by(y) %>%
group_rows()
#> <list_of<integer>[2]>
#> [[1]]
#> [1] 1 2 3 4 5
#> 
#> [[2]]
#> [1]  6  7  8  9 10
```
<sup>Created on 2020-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Improve group_by()'s example to show empty group

- R/rank.R
In the `ntile()` docs, the definition link gives a 404 error since Microsoft migrated the blog. Seem to have found it though&mdash;same author, title, and date posted.
> Update ntile documentation link

- R/arrange.R
- R/zzz.r
The `delayedAssign()` approach apparently does not work consistently with binary packages.
> Fix dynamic binding for `dplyr_proxy_order()`

- R/distinct.R
- tests/testthat/test-n_distinct.R
Closes #5428 
The `map()` and `as_tibble()` calls in `n_distinct()` are fairly slow when called repeatedly (added in https://github.com/tidyverse/dplyr/pull/5072).
This PR refactors `n_distinct()` to avoid tibble and `map()` and instead only use vctrs. I imagine this will be further improved with hybrid eval, but this should help significantly for now. I don't think it should change any behavior of `n_distinct()`.
Below is an adjusted example from #5428. It reduces the number of rows from 50,000,000 down to a more reasonable 500,000. The example there was a bit extreme to run on 50 million rows, but I imagine that it should at least work now.
``` r
set.seed(123)
table_size <- 500000
dates <- seq(as.Date('2020/07/01'), as.Date('2020/07/18'), by = "day")
table_tbl <- …
```
> Improve `n_distinct()` performance

- R/compat-purrr.R
- R/deprec-src-local.r
- R/deprec-tibble.R
- R/distinct.R
- R/funs-predicates.R
- R/nth-value.R
- R/utils.r
- tests/testthat/test-nth-value.R
- tests/testthat/test-nth-value.txt
``` r
dplyr::nth(1:10, "x")
#> Error: `nth()` argument `n=` should be a single integer
#> Backtrace:
#>     █
#>  1. └─dplyr::nth(1:10, "x")
```
<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
> improve nth() error message about n=

- .github/workflows/continuous-benchmarks.yaml
- .github/workflows/pkgdown.yaml
GitHub action requires us to set username and email explicitly (c.f. https://github.com/r-lib/actions/issues/135). Otherwise it fails with the errors like this:
```
Run Rscript -e 'bench::cb_run()'
Rscript -e 'bench::cb_run()'
shell: /bin/bash -e {0}
env:
R_LIBS_USER: /Users/runner/work/_temp/Library
TZ: UTC
NOT_CRAN: true
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'runner@Mac-1596551650870.(none)')
##[error]Error: git notes failed with exit code 128.
```
> Configure git username and email on GitHub Actions CI

- R/data-mask.R
- R/mutate.R
With the last version of rlang (on which we now depend), the locale warnings on Windows should be fixed.
Also `env_unbind()` doesn't warn when the binding doesn't exist, unlike `rm()`.
> Use rlang to manipulate environment bindings without warnings

- NEWS.md
- R/across.R
- tests/testthat/test-across.R
Follow-up to #5469
Closes #5460
> Fix data masking of tidyselect env-expressions in `across()` 

- R/data-mask.R
- src/dplyr.h
- src/init.cpp
- src/mask.cpp
related to #5017 
with the code: 
```r
m0 <- matrix(0, 50, 2000)
groups <- sample(1:10, 50, replace = TRUE)
m1 <- apply(m0, c(1,2), function(x) sample(c(0,1),1)) %>%
as.data.frame() %>%
mutate(groups = groups)
m2 <- m1 %>%
group_by(groups)
profvis::profvis({
summarise_all(m2, list(sum))
})
```
we're down from: 
to
> speedup <DataMask>$set(name, chunks)

- R/na_if.R
- man/dplyr-package.Rd
- man/na_if.Rd
Updated the example, considering that `mutate_if` has been superseded by mutate + across
> change mutate_if example in na_if documentation to mutate + across

- vignettes/programming.Rmd
According to the [update notice](https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-select-rename-relocate/#update-notice),
I guess it is a typo
> fix a typo in programming.rmd

- NEWS.md
- R/data-mask.R
- tests/testthat/test-across.R
closes #5523
``` r
library(dplyr)
tibble(hello = 1:5) %>% mutate(across(NULL, ~ .x + 1))
#> # A tibble: 5 x 1
#>   hello
#>   <int>
#> 1     1
#> 2     2
#> 3     3
#> 4     4
#> 5     5
tibble(.rows = 5) %>% mutate(across(NULL, ~ .x + 1))
#> # A tibble: 5 x 0
```
<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
> `across()` handles data frames with 0 columns

- R/context.R
- R/data-mask.R
- R/filter.R
- R/mutate.R
- R/slice.R
- R/summarise.R
- src/chop.cpp
- src/dplyr.h
- src/filter.cpp
- src/init.cpp
- src/mask.cpp
- tests/testthat/test-mutate-errors.txt
This builds on top of #5520 but instead of creating one rlang data mask per group with promises, this has only one data mask, but holding active bindings. 
The active binding still uses the lazy chops which still live in an environment full of promises. 
For example with `data.frame(x = 1:2, y = 3:4) %>% group_by(x)` we create: 
- the lazy chops: an environment with promises of chops for `x` and `y`. The parent of this env has the `.current_group` variable that needs to be changed as the evaluation moves from one group to the other. 
- the rlang data mask, with bindings like `function() .subset2(x, .current_group)`. The binding function's enclosure is the lazy chops env
``` r
library(dplyr)
set.seed(123)
group_size <- 5L
n_groups <- 1e5
size <- n_groups * group_size
g <- …
```
> promises for chops, active bindings for slices

- NEWS.md
- R/mutate.R
- man/mutate.Rd
- tests/testthat/test-deprec-combine-errors.txt
- tests/testthat/test-deprec-dbi-errors.txt
- tests/testthat/test-deprec-funs-errors.txt
- tests/testthat/test-deprec-src-local-errors.txt
- tests/testthat/test-do-errors.txt
- tests/testthat/test-mutate.r
This does not yet deals with #5582 but there still was a little problem that `attr(cols, "used")` aka `mask$get_used()` is relative to the accumulated variables, not just `names(.data)`. 
Then, is this correct: 
``` r
iris %>%
group_by(Species) %>%
mutate(meanPL = mean(Petal.Length), .keep = "all") %>% 
group_vars()
#> [1] "Species"
iris %>%
group_by(Species) %>%
mutate(meanPL = mean(Petal.Length), .keep = "none") %>% 
group_vars()
#> [1] "Species"
iris %>%
group_by(Species) %>%
mutate(meanPL = mean(Petal.Length), .keep = "used") %>% 
group_vars()
#> character(0)
iris %>%
group_by(Species) %>%
mutate(meanPL = mean(Petal.Length), .keep = "unused") %>% 
group_vars()
#> [1] "Species"
```
<sup>Created on 2020-11-02 by the [reprex …
> $get_used() is relative to $current_vars(), not names(.data)

- NEWS.md
- R/group-by.r
- tests/testthat/test-group-by.r
related to #5473
``` r
df <- tibble(x = c(1,2), y = c(3,4), z = c(5,6))
df %>% 
dplyr::group_by(y) %>%
dplyr::group_by(across(any_of(c('y','z')))) %>%
dplyr::group_vars() 
#> [1] "y" "z"
df %>% 
dplyr::group_by(y) %>%
dplyr::group_by(y, z) %>%
dplyr::group_vars() 
#> [1] "y" "z"
```
<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
On master, only the second one incorporates `y`. Is there any reason why the implicit `mutate()` step uses the grouped data instead of the ungrouped data, as suggested by this PR ? 
``` r
df <- tibble(x = c(1,2), y = c(3,4), z = c(5,6))
df %>% 
dplyr::group_by(y) %>%
dplyr::group_by(across(any_of(c('y','z')))) %>%
dplyr::group_vars() …
```
> compute groups on ungrouped data.

- _pkgdown.yml
or perhaps we can remove it altogether, there's nothing to see there
> fix link for 0.8.4 release

- R/slice.R
- tests/testthat/test-slice-errors.txt
- tests/testthat/test-slice.r
related to #5478
Trying to be more informative in the error message: 
``` r
df <- data.frame(col1 = c('a', 'b', 'b', 'c'), col2 = 1:4)
df %>% 
group_by(col1) %>% 
slice_sample(n = max(n() * 0.5, 1))
#> Error: `n` must be constant across groups in `slice_sample()`.
#> x `n()` must only be used inside dplyr verbs.
#> Backtrace:
#>      █
#>   1. └─df %>% group_by(col1) %>% slice_sample(n = max(n() * 0.5, 1))
#>   2.   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
#>   3.   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   4.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   5.       └─`_fseq`(`_lhs`)
#>   6.         └─magrittr::freduce(value, `_function_list`)
#>   7.           ├─base::withVisible(function_list[[k]](value))
#> …
```
> check that n= or prop= can be forced.

- R/context.R
- R/mutate.R
- tests/testthat/test-mutate.r
closes #5534
``` r
data.frame(x = numeric()) %>%
group_by(x) %>%
mutate(y = max(x))
#> Warning: Problem with `mutate()` input `y`.
#> ℹ no non-missing arguments to max; returning -Inf
#> ℹ Input `y` is `max(x)`.
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> # Groups:   x [0]
#> # … with 2 variables: x <dbl>, y <dbl>
```
<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
@lionel- is there a way to only keep one of these warnings: 
``` r
withCallingHandlers(warning("a"), warning = function(w) warning("b"))
#> Warning in (function (w) : b
#> Warning in withCallingHandlers(warning("a"), warning = function(w)
#> warning("b")): a
```
<sup>Created on 2020-11-09 …
> special case cur_group_label() when data has 0 rows.

- src/chop.cpp
- src/dplyr.h
- src/mask.cpp
This is copied from https://github.com/r-lib/rlang/blob/898449d00b51ac32839715be0bdd8c5330f56aca/src/lib/vec-chr.h#L92 
@lionel- is there a way to use something like `r_str_as_symbol` directly from rlang ?
> remove warning from installChar()

- DESCRIPTION
Closes #5568 
Since this issue is now fixed in the CRAN version of vctrs (0.3.5) https://github.com/r-lib/vctrs/issues/1291
> Bump required vctrs version

- R/grouped-df.r
closes #5622
workaround for dplyr until https://github.com/r-lib/vctrs/issues/1298
> down cast before vec_order()

- R/funs.R
This request fixes some minor documentation in the updated `between` function.
1. Added the word "be" to error message when right argument is not a scalar so it is now "`right` must be length 1" instead of "`right` must length 1"
2. Added a space after comma in documentation.
Related to #5501
> Grammar typos in between function error fixed

- src/chop.cpp
Since `Rf_findVarInFrame()` might return a promise, and it might not.
(At least in an R-devel build with `--enable-strict-barrier`, it seems like this may not necessarily be a `PROMSXP`.)
> only call PRVALUE if prom is indeed a PROMSXP

- NEWS.md
- R/grouped-df.r
- tests/testthat/test-group-by.r
Passing `.drop = FALSE` to `group_by()` causes ordered factors to become unordered. I added a simple check in `compute_groups()` to check if a factor is ordered, and if so, create an ordered factor in its place instead of an unordered one.
Includes tests which currently fail. Lmk if you have any questions/feedback 👌
Fixes #5455
> Preserve ordered factors with `group_by(.drop = FALSE)`

- R/mutate.R
- R/summarise.R
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise.r
closes #5646
on the original example: 
``` r
my_vals <- function(x) {
name_x <- rlang::expr_deparse(rlang::enexpr(x))
out <- lapply(unique(x), function (i) {
out_i <- tibble(i)
names(out_i) <- paste(name_x, i, sep = ": ")
out_i
})
vctrs::vec_cbind(!!!out)
}
mtcars %>%
group_by(cyl) %>%
summarise(
my_vals(am),
my_vals(vs)
)
#> `summarise()` has ungrouped output. You can override using the `.groups` argument.
#> # A tibble: 3 x 5
#>     cyl `am: 1` `am: 0` `vs: 1` `vs: 0`
#> * <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
#> 1     4       1       0       1       0
#> 2     6       1       0       1       0
#> 3     8       1       0      NA       0
```
<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
> cast to common type results of mutate() and summarise().

- R/across.R
- man/across.Rd
- vignettes/colwise.Rmd
alternatively, this could illustrate the problem and offer alternatives as discussed in #5433 but it might be confusing in the vignette ?
> Avoid where(is.numeric) in colwise vignette when using across twice

- NEWS.md
- R/summarise.R
- man/summarise.Rd
- tests/testthat/test-summarise-errors.txt
- tests/testthat/test-summarise.r
``` r
.... <- tibble(x = 1, y = 2) %>% group_by(x, y) %>% summarise()
#> `summarise()` has grouped output by 'x'. You can override using the `.groups` argument.
.... <- tibble(x = 1, y = 2) %>% group_by(x, y) %>% summarise(z = c(2,2))
#> `summarise()` has grouped output by 'x', 'y'. You can override using the `.groups` argument.
.... <- tibble(x = 1, y = 2) %>% group_by(x) %>% summarise(z = c(2, 2))
#> `summarise()` has grouped output by 'x'. You can override using the `.groups` argument.
.... <- tibble(x = 1, y = 2) %>% group_by(x) %>% summarise()
```
<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
Should the messages that we keep include more insight about why this is what is chosen ?
> remove the message about going from 1 to 0 groups

- R/across.R
- man/across.Rd
Addresses #5517 .
A few notes:
- I didn't change the examples which demonstrates how to use the `.fns` and `.names` arguments because I think these examples would be easier to understand if the selected columns (`starts_with("Sepal")`) remain the same.
- Some examples (especially the one with `across(c(1:Sepal.Width)`) may seem weird, but I think they can inspire users to try related selecting strategies.
This is my first attempt to make a pull request, so please let me know if it needs further refinements :).
> add examples to show more ways of selecting columns in across() documentation

- vignettes/base.Rmd
The base R entry for relocate(df, y) was missing a closing square bracket.
> Fixed typo - missing closing bracket

- NEWS.md
- R/aaa.R
- R/mutate.R
- R/utils.r
- R/zzz.r
- tests/testthat/helper-dplyr.R
- tests/testthat/test-mutate.r
Closes #5675
```r
foo <- function() {
warning("foo")
NA
}
df <-
tibble(x = rep(1:1000, 2)) %>%
group_by(x)
bench::workout({
mutate(df, foo())
suppressWarnings(mutate(df, foo()))
mutate(df, suppressWarnings(foo()))
})
#> # 1.0.0
#>   exprs                                process     real
#>   <bch:expr>                          <bch:tm> <bch:tm>
#> 1 mutate(df, foo())                      191ms    208ms
#> 2 suppressWarnings(mutate(df, foo()))    208ms    213ms
#> 3 mutate(df, suppressWarnings(foo()))    220ms    225ms
#> # dev version
#>   exprs                                process     real
#>   <bch:expr>                          <bch:tm> <bch:tm>
#> 1 mutate(df, foo())                      3.02s    3.13s
#> 2 suppressWarnings(mutate(df, foo()))    3.25s    3.39s
#> 3 mutate(df, …
```
> Don't instrument muffled warnings

- R/arrange.R
- man/arrange.Rd
- man/select.Rd
Unless I'm reading it wrong, the text in the arguments section:
> `<data-masking>` Variables, or functions or variables. Use desc() to sort a variable in descending order.
Should read:
> `<data-masking>` Variables, or functions of variables. Use desc() to sort a variable in descending order.
> Fix typo in arrange() documentation

- NEWS.md
- R/summarise.R
- src/summarise.cpp
- tests/testthat/test-summarise-errors.txt
- tests/testthat/test-summarise.r
closes #5708
silently ignoring when *all the results* are NULL, and otherwise shout: 
``` r
df <- data.frame(x = 1:2, g = 1:2) %>% group_by(g)
summarise(df, x = NULL)
#> # A tibble: 2 x 1
#>       g
#> * <int>
#> 1     1
#> 2     2
summarise(df, x = if(g == 1) 42)
#> Error: Problem with `summarise()` input `x`.
#> x `x` must return compatible vectors across groups.
#> ℹ Cannot combine NULL and non NULL results.
#> ℹ Input `x` is `if (g == 1) 42`.
```
<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> summarise() silently ignore NULL results.

- NEWS.md
- R/across.R
- man/across.Rd
- src/dplyr.h
- src/filter.cpp
- src/init.cpp
- tests/testthat/test-across.R
- tests/testthat/test-mutate.r
closes #5709
simplified version of @iago-pssjd example: 
``` r
d <- data.frame(x = c(0, 0, 10), y = c(0, 0, 10), z = c(10, 0, 10))
d %>% mutate(
test = case_when(
if_all(x:z, ~ . > 8) ~ "all big",
if_any(x:z, ~ . > 8) ~ "some big",
TRUE                 ~ "small"
))
#>    x  y  z     test
#> 1  0  0 10 some big
#> 2  0  0  0    small
#> 3 10 10 10  all big
```
<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> if_any() effectively reducing.

- R/across.R
- R/data-mask.R
closes #5717
initial reprex from #5717: 
``` r
data.frame(x = 1, y = 2, z = 3) %>% 
summarise(
across(c(x, y), ~ . / z)
)
#>           x         y
#> 1 0.3333333 0.6666667
data.frame(x = 1, y = 2, z = 3) %>% 
summarise(
across(c(x, y), ~ . / .data[["z"]])
)
#>           x         y
#> 1 0.3333333 0.6666667
```
<sup>Created on 2021-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
This also fix the issue with `mde`: 
``` r
library(mde)
#> Welcome to mde. This is mde version 0.2.2.9000.
#>  Please file issues and feedback at https://www.github.com/Nelson-Gon/mde/issues
#> Turn this message off using 'suppressPackageStartupMessages(library(mde))'
#>  Happy Exploration :)
some_data <- …
```
> tweak formula when in top_across()

- R/across.R
- tests/testthat/test-across.R
closes #5717
identified by testing `stacks` in the revdeps.
> not determine if in top_across() holistically

- R/grouped-df.r
- tests/testthat/test-group-by.r
closes #5745
initial example: 
``` r
library(tibble)
iris_med <- iris %>% 
group_by(Species) %>% 
summarize(across(where(is.double), median))
iris_med %>% column_to_rownames("Species")
#>            Sepal.Length Sepal.Width Petal.Length Petal.Width
#> setosa              5.0         3.4         1.50         0.2
#> versicolor          5.9         2.8         4.35         1.3
#> virginica           6.5         3.0         5.55         2.0
```
<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> use attr<-() instead of structure() as it somehow messes up row.names 

- R/across.R
- man/across.Rd
description for if_any() and if_all() was missing a word ("...are used with ____ to apply the same...") , I assumed the missing word was select() semantics...
I used select() semantics because that is the phrasing used in the description for across().
> Update typo in across.R

- NEWS.md
- R/slice.R
- tests/testthat/test-slice.r
closes #5729
The original code gives: 
``` r
tibble(dummy = character(), weight = numeric(0)) %>% 
slice_sample(prop=0.5, weight_by = weight)
#> # … with 2 variables: dummy <chr>, weight <dbl>
```
<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
There might be a better way to address this 🤷, this feels like a `sample.int()` shortcoming:
``` r
sample.int(0, 0, prob = numeric(0))
#> Error in sample.int(0, 0, prob = numeric(0)): too few positive probabilities
```
<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> work around sample.int()

- _pkgdown.yml
I found the pkgdown site is still at 1.0.2: https://dplyr.tidyverse.org/
This seems because there's some missing topics and a defunct topic.
```
-- Building function reference -------------------------------------------------
Error in check_missing_topics(rows, pkg) : 
Topics missing from index: c_acrosssetops
Calls: <Anonymous> ... stopifnot -> data_reference_index -> check_missing_topics
In addition: Warning message:
In '_pkgdown.yml', topic must be a known topic name or alias
✖ Not 'condense' 
```
https://github.com/tidyverse/dplyr/runs/1816406217#step:9:44
> Fix pkgdown build

- NEWS.md
- R/across.R
- R/data-mask.R
- tests/testthat/test-across.R
closes #5734
``` r
df <- data.frame(x = 1, y = 2)
df %>% 
mutate(across('x', function(.x) {
return(.x/y)
}))
#>     x y
#> 1 0.5 2
```
OTOH, this does not work: 
```r
f <- function(.x) .x / y
df %>% mutate(across('x', f))
#> Error: Problem with `mutate()` input `..1`.
#> x object 'y' not found
#> ℹ Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
```
<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> eval_tidy() the top_across() call with the right mask and caller env

- NEWS.md
- R/across.R
- R/data-mask.R
closes #5733
It's the kind of problem that is not easily reproducible in a test, but the original code from #5733 now gives: 
``` r
library(palmerpenguins)
penguins %>%
group_by(species, island) %>%
summarise(
prob = c(.25, .75),
across(
c(bill_length_mm, bill_depth_mm, flipper_length_mm),
~ quantile(., prob, na.rm = TRUE)
)
)
#> `summarise()` has grouped output by 'species', 'island'. You can override using the `.groups` argument.
#> # A tibble: 10 x 6
#> # Groups:   species, island [5]
#>    species   island     prob bill_length_mm bill_depth_mm flipper_length_mm
#>    <fct>     <fct>     <dbl>          <dbl>         <dbl>             <dbl>
#>  1 Adelie    Biscoe     0.25           37.7          17.6              185.
#>  2 Adelie    Biscoe     0.75           40.7 …
```
> internal error dealing with .current_group

- NEWS.md
- R/group-by.r
- tests/testthat/test-group-by.r
closes #5760
``` r
m <- mtcars
attr(m, "foo") <- "a"
m <- dplyr::group_by(m, vs)
attr(m, "foo")
#> [1] "a"
m <- dplyr::group_by(m, cyl, .add = TRUE)
attr(m, "foo")
#> [1] "a"
```
<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
`ungroup()` wipes all attributes, but `dplyr_reconstruct()` would restore `@groups` which we don't want. Not sure this can be abstracted away ?
> keep attributes when adding computed columns, ungroup() is too strong

- NEWS.md
- R/mutate.R
- R/summarise.R
- tests/testthat/test-across.R
I added some tests too, code from #5770: 
``` r
library(palmerpenguins); library(tidyverse)
(tbl1 <- penguins %>%
group_by(species, island, sex) %>%
summarize(n = n()) %>%
pivot_wider(names_from = sex, values_from = n))
#> `summarise()` has grouped output by 'species', 'island'. You can override using the `.groups` argument.
#> # A tibble: 5 x 5
#> # Groups:   species, island [5]
#>   species   island    female  male  `NA`
#>   <fct>     <fct>      <int> <int> <int>
#> 1 Adelie    Biscoe        22    22    NA
#> 2 Adelie    Dream         27    28     1
#> 3 Adelie    Torgersen     24    23     5
#> 4 Chinstrap Dream         34    34    NA
#> 5 Gentoo    Biscoe        58    61     5
(tbl2 <- tbl1 %>%
ungroup() %>%
rowwise(species, island) %>%
mutate(across(everything(), ~ . / …
```
> across() not operating sequentially

- R/group-by.r
- tests/testthat/test-group-by.r
related to https://github.com/tidyverse/dplyr/pull/5767/files/bbe2e5be39946ed4f7bea5149d84e2612133fc51#diff-1ec33e14b938e61e20e0bef01b54aa084a603bfcbf3449c84535293f0f6ca9a5 comment on #5767
No need for attribute surgery, added a test that actually requires a `mutate()`
> Move the ungroup() special handling down to add_coomputed_columsn()

- vignettes/programming.Rmd
I found a  minor typo in the dplyr-programming vignette, where `mean` is used instead of `sd`.
So I changed the two occurences and hereby open my first pull-request.
If I did anything wrong, please let me know.
Otherwise, I hope this is the right way to contribute to improving the tidyverse-documentation.
Thanks,
Sebastian
> typo: replace mean with sd

- NEWS.md
- R/compute-collect.r
- man/compute.Rd
The `name` argument of the `compute()` generic is a vestige from the old days before dbplyr was broken out as a separate package. It would be best to remove it if doing so will not break any reverse dependencies.
Some dplyr backend packages need a method to force evaluation of lazy operations _without_ assigning an external name to the materialized result where it's stored in the backend system. An example of this is the arrow R package.
It _seems_ like this change should not break anything, because dplyr SQL backend packages should all use `dbplyr::compute.tbl_sql()` (which redefines the `name` argument) or else define their own `compute()` methods.
> Remove name argument from compute() generic

- NEWS.md
- R/data-mask.R
- src/chop.cpp
- tests/testthat/test-mutate.r
> support for rowwise data frame with 0 rows and list columns.

- R/across.R
- man/across.Rd
- man/select.Rd
- tests/testthat/test-across.R
closes #5782
``` r
df <- data.frame(
x = 1:3
)
df %>% mutate(
y1 = case_when(
if_any(everything(), ~ . >= 3) ~ "big",
if_any(everything(), ~ . >= 2) ~ "medium",
TRUE ~ "small"
),
y2 =  case_when(
x >= 3 ~ "big",
x >= 2 ~ "medium",
TRUE ~ "small"
)
)
#>   x     y1     y2
#> 1 1  small  small
#> 2 2 medium medium
#> 3 3    big    big
```
<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> across() gains .call= so that we can control which call governs the caching

- R/mutate.R
- tests/testthat/_snaps/transmute.md
- tests/testthat/test-transmute.R
closes #5796
I'm not sure this is the right way, perhaps we should instead just (with a warning maybe) cancel `.keep`, `.after` and `.before`
> transmute() forbids .keep, .after, .before

- R/distinct.R
- R/group-by.r
- R/mutate.R
- R/summarise.R
- man/group_by_prepare.Rd
- tests/testthat/helper-dplyr.R
- tests/testthat/test-distinct.R
- tests/testthat/test-group-by.r
- tests/testthat/test-mutate.r
- tests/testthat/test-summarise.r
Usually does not matter but the caller env will be useful for fixing #5815.
Since they are exported, `group_by_prepare()` and `distinct_prepare()` use `caller_env(2)` as default. Best to supply the caller env explicitly though.
> Supply proper caller environments to dplyr masks

- R/across.R
- man/across.Rd
- Caching `.fns` is too perilous. The function might produce side effects or depend on state.
- Caching `.cols` is no longer as useful with the top-level `across()` expansion that Romain implemented.
We still cache for `c_across()` as it doesn't have any expansion yet. The caching takes into account the quosure env to improve correctness. Should be further improved by not caching any selection that includes env-expressions since these might have side effects and depend on state.
Future actions:
- Expand top-level `if_any()` and `if_all()` calls.
- Think about macro-expansion approach. Maybe features like `if_any()`, `across()`, etc should be thought of as macros.
Closes #5835.
> Remove caching of `across()` selections

- R/conditions.R
- R/mutate.R
- R/summarise.R
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/summarise.md
``` r
df <- data.frame(a = 1, b = 2, c = 3)
df %>% 
summarise(across(c(a, b), ~stop("oh no")))
#> Error: Problem with `summarise()` input `..1`.
#> ℹ `..1 = across(c(a, b), ~stop("oh no"))`.
#> x oh no
```
<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Follow up to #5843, using input instead of column for ..{i}

- NEWS.md
- R/across.R
- R/conditions.R
- R/filter.R
- tests/testthat/_snaps/across.md
- tests/testthat/test-across.R
closes #5732
on the original example, this gives: 
``` r
mtcars %>% 
filter(if_any(~.x == 39.1))
#> Error: Problem with `filter()` input `..1`.
#> x Misplaced formula shorthand.
#> ℹ You most likely meant to use `.fns = ~.x == 39.1`
#> ℹ ... or perhaps `where(~.x == 39.1)`
#> ℹ Input `..1` is `if_any(~.x == 39.1)`.
```
<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Forbid ~predicates in `across/if_any/if_all(.cols = )`

- R/across.R
- tests/testthat/test-across.R
closes #5862
``` r
f <- function(data, cols, fn_list) {
data %>% 
summarise(
across({{ cols }}, fn_list$funs)
)
}
f(mtcars, c(mpg, cyl), list(funs = mean))
#>        mpg    cyl
#> 1 20.09062 6.1875
```
<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
seems to fix `skimr::skim()` too: 
``` r
skimr::skim(iris)
```
|                                                  |      |
| :----------------------------------------------- | :--- |
| Name                                             | iris |
| Number of rows                                   | 150  |
| Number of columns                                | 5    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |      |
| Column type frequency: …
> expand_across() can access lexical scope.

- NEWS.md
- R/across.R
- tests/testthat/test-across.R
closes #5883
original example from #5883
``` r
FOOBAR.df <- data.frame(matrix(rnorm(50), nrow = 10))
colnames(FOOBAR.df) <- c("Prevotella", "Streptococcus", "Gemella", "Rothia", "Haemophilus")
FOOBAR.df %>% 
rowwise() %>% 
transmute(sum(c_across(all_of(c("Prevotella", "Streptococcus", "Gemella", "Rothia", "Haemophilus")))))
#> # A tibble: 10 x 1
#> # Rowwise: 
#>    `sum(...)`
#>         <dbl>
#>  1      0.673
#>  2      3.51 
#>  3     -0.463
#>  4     -3.28 
#>  5     -1.43 
#>  6     -2.56 
#>  7     -4.42 
#>  8     -2.06 
#>  9      0.473
#> 10      0.297
```
<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> making sure key_deparse() returns a single string

- NEWS.md
- R/across.R
- tests/testthat/test-across.R
closes #5881
``` r
library(AMR)
library(skimr)
skim(example_isolates)
```
|                                                  |                   |
| :----------------------------------------------- | :---------------- |
| Name                                             | example\_isolates |
| Number of rows                                   | 2000              |
| Number of columns                                | 49                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                   |
| Column type frequency:                           |                   |
| character                                        | 2                 |
| Date                                             | 1                 |
| factor                                           | 1 …
> use the formula environment as the newly created quosure environment.

- NEWS.md
- R/across.R
- tests/testthat/test-across.R
This is the `across()` related part of #5207: 
``` r
df <- data.frame(x = 1, y = 2)
df %>% 
summarise(across(c(z = x)))
#>   z
#> 1 1
df %>% 
summarise(across(all_of(c(z = "x"))))
#>   z
#> 1 1
df %>% 
summarise(across(c(z = x), mean))
#>   z
#> 1 1
df %>% 
summarise(across(all_of(c(z = "x")), mean))
#>   z
#> 1 1
df %>% 
summarise(across(c(z = x), list(mean = mean)))
#>   z_mean
#> 1      1
df %>% 
summarise(across(all_of(c(z = "x")), list(mean = mean)))
#>   z_mean
#> 1      1
```
<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> `across()` handles named selections, part of #5207

- R/across.R
- R/filter.R
- R/utils.r
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/test-across.R
identified as part of rev dep checks for release 1.0.7 #5894 
original problem: 
``` r
local({
limit <- 7
df <- data.frame(x = 1:10, y = 10:1)
filter(df, if_any(everything(), ~ .x > limit))
})
#> Error: Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `x > limit | y > limit`.
#> x object 'limit' not found
```
this breaks package `readabs`. 
```
> revdepcheck::cloud_details(, "readabs")
══ Reverse dependency check ═══════════════════════════════════════════════════════════════════════════════════ readabs 0.4.9 ══
Status: BROKEN
── Newly failing
x checking examples ... ERROR
x checking tests ... ERROR
── Before ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✓ | 0 …
```
> Fixes for `across()` substitution

- R/utils.r
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/test-across.R
``` r
tibble(x = 1:10) %>% 
mutate(across(x, ~ case_when(
. < 5 ~ 5L, 
TRUE  ~ .
)))  
#> # A tibble: 10 x 1
#>        x
#>    <int>
#>  1     5
#>  2     5
#>  3     5
#>  4     5
#>  5     5
#>  6     6
#>  7     7
#>  8     8
#>  9     9
#> 10    10
```
<sup>Created on 2021-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> expr_substitute() does substitute double sided formula

- R/arrange.R
- tests/testthat/_snaps/arrange.md
- tests/testthat/test-arrange.r
> desc() inside arrange() checks the number of arguments.

- R/across.R
- tests/testthat/test-across.R
closes #5924
``` r
data.frame(x = 1) %>% 
mutate(across(where(is.numeric), lst(f = ~ . + 1)))
#>   x x_f
#> 1 1   2
```
<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> `across()` expansion: also check the ancestry of the formula environment.

- NEWS.md
- R/coalesce.R
- tests/testthat/test-coalesce.R
This implements @FrancoisGuillem's proposed fix for 1-dimensional arrays.
> coalesce() support 1-D arrays (#5557)

- R/group_data.R
this does not address the issue from #5969 because the warning is legit, but at least it should warn about the right function: 
``` r
dplyr::group_indices(mtcars, cyl)
#> Warning: The `...` argument of `group_indices()` is deprecated as of dplyr 1.0.0.
#> Please `group_by()` first
#>  [1] 2 2 1 2 3 2 3 1 1 2 2 3 3 3 3 3 3 1 1 1 1 3 3 3 3 1 1 1 3 2 3 1
```
<sup>Created on 2021-08-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> fix warning message. related to #5969

- NEWS.md
- src/filter.cpp
- tests/testthat/_snaps/filter.md
- tests/testthat/test-filter.r
closes #5973
original code from #5972 gives: 
``` r
tibble(
y = tibble(
b = c(1, 2),
a = c(NA, 1),
)
) %>% 
filter(is.na(y))
#> Error: Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `is.na(y)`.
#> x Input `..1` must be a logical vector, not a logical[,2].
```
<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> `filter()` forbid matrices

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
- DESCRIPTION
Hopefully switching to pak fixes our failing builds 
https://github.com/tidyverse/dplyr/runs/3398502012
Update:
Turns out switching from xenial to bionic in #5959 required a cache bump to redownload stringi, and that is what was causing the failures. I think that updating the workflows here has also triggered the cache bump, which is why we get green checks now.
Hopefully the pkgdown build works (I've added required packages to Config/Needs/website), we won't know until we merge.
> Update GitHub Actions workflows

- DESCRIPTION
- R/arrange.R
- R/group-by.r
- tests/testthat/_snaps/across.md
- tests/testthat/_snaps/arrange.md
- tests/testthat/_snaps/colwise-filter.md
- tests/testthat/_snaps/deprec-funs.md
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/group-by.md
- tests/testthat/_snaps/group_map.md
Closes r-lib/rlang#1254
This was coming with https://github.com/tidyverse/dplyr/pull/5942, which is close to being ready to merge, but doing this in its own PR is much cleaner since there are a few changes:
- A few snapshot tests are changed since now there is a space in anonymous functions between `~` and the body
- The `check_dots_empty()` error comes from rlang now and is a little different
- In two places, we relied on `abort()` auto-naming the non-header bullets. It no longer does this, so I've added explicit `x` names on these bullets. See also https://github.com/r-lib/rlang/issues/1254
@lionel- I imagine that rlang will probably be sent to CRAN before dplyr, so there will be a short period where the two places we weren't explicitly naming the bullets will now emit unbulleted …
> Require dev rlang

- R/slice.R
Similar to how it's done in `filter_rows()`
> slice_rows() takes a caller_env argument, instead of calling caller_env() inside 

- NEWS.md
- R/slice.R
- tests/testthat/_snaps/sample.md
- tests/testthat/_snaps/slice.md
closes #5931
``` r
data.frame(x = 1:10, g = rep(1:5, each = 2)) %>% 
group_by(g) %>% 
slice(stop("boom"))
#> Error: boom
#> ℹ The error occurred in group 1: g = 1.
```
<sup>Created on 2021-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
Maybe this should follow the lead of other verbs and use the conditionMessage as a `x`, e.g. something like: 
```r
#> Error: Problem with `slice()` <...>
#> x boom
#> ℹ The error occurred in group 1: g = 1.
```
but because all `...` are collapsed with `quo <- quo(c(!!!dots))` we can't be specific about which of them generates the error, we cannot do e.g. `Problem with `slice()` input ..1`
This change will probably be interesting together with https://github.com/tidyverse/dplyr/pull/5932
> Adding context to slice() errors, i.e. the group information.

- DESCRIPTION
related to:
- https://github.com/r-lib/pillar/pull/368
- https://github.com/tidyverse/tibble/pull/955
> avoid warning about last_warnings()

- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
closes #5922
``` r
df <- data.frame(x = 1:10)
slice_min(df, 1:6)
#> Error: `slice_min(order_by=)` must have size 10, not size 6.
slice_max(df, 1:6)
#> Error: `slice_max(order_by=)` must have size 10, not size 6.
slice_sample(df, n = 2, weight_by = 1:6)
#> Error: `slice_sample(weight_by=)` must have size 10, not size 6.
```
<sup>Created on 2021-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> check slice_min/max(order_by) and slice_sample(weight_by=)

- R/mutate.R
- man/mutate.Rd
- tests/testthat/test-mutate.r
Closes #6007 
Closes #5967 
I'm hoping that this is a much simpler variant of #6007 that is overall easier to understand and test.
Essentially there are 4 _rules_ that always hold:
- _Group_ variables are always retained and never move
- _Modified_ variables are always retained and never move
- _New_ variables are always retained and move at the whim of `.before` and `.after`. Default is to add them to the end.
- _NULL_ expressions remove columns entirely
This takes care of everything except `.keep`, and we now have a language to refer to the different types of columns. There are two extra column types:
- _Used_ variables are variables from the original data used to generate other columns. The set of used variables excludes group variables and modified variables.
- _Unused_ variables are …
> Rework `mutate.data.frame()` to better implement `.keep`

- DESCRIPTION
- R/sets.r
- man/setops.Rd
- tests/testthat/test-sets.R
closes #5891
``` r
a <- tibble(var = 1:3)
b <- tibble(var = 2:4)
c <- tibble(var = c(1, 3, 4, 5))
intersect(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
setdiff(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
setequal(a, b, c)
#> Error: `...` is not empty.
#> ℹ These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> • `..1`
#> ℹ Did you misspecify an argument?
union(a, b, …
```
> check empty dots in set operations on data frames

- DESCRIPTION
- R/group-by.r
- R/pull.R
- R/rows.R
- R/select-helpers.R
- R/slice.R
Perhaps this should drop the `rlang::` prefix too since `rlang` is `@import`'ed
> Use rlang dots helper instead of ellipsis

- R/across.R
- man/across.Rd
- tests/testthat/test-across.R
closes #6068 
This goes against what was discussed with @lionel- in #5813 so I'm not really sure. The point raised in #6068 needs to be addressed though. 
This should either fail, maybe with a message saying that `cur_column()` cannot be used in `across(...)` or succeed (the way of this pull request). 
``` r
tibble(a = 1:5, b = 2:6) %>% 
mutate(across(everything(), paste, cur_column()))
#> # A tibble: 5 × 2
#>   a     b    
#>   <chr> <chr>
#> 1 1 a   2 b  
#> 2 2 a   3 b  
#> 3 3 a   4 b  
#> 4 4 a   5 b  
#> 5 5 a   6 b
```
<sup>Created on 2021-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
This invalidates a test that was added in #5813 (skipped now):
``` r
test_that("across() evaluates ... with promise semantics …
```
> `across(...)` evaluated more lazily

- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
When neither `n` nor `prop` is given but a single unnamed `...` is given, `..1` is likely meant as `n =`. 
``` r
library(dplyr, warn.conflicts = F)
show_error <- function(expr) tryCatch(expr, error = function(cnd) print(cnd, backtrace = FALSE))
show_error(
mtcars %>% 
slice_head(2)  
)
#> <error/rlang_error>
#> Error in `slice_head()`: `n` must be explicitely named.
#> ℹ Did you mean `slice_head(n = 2)` ?
```
<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
> special case for slice_*() 

- R/sample.R
This was causing some failed test in `saeSim`: 
````
══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-sim_sample.R:26:3): Attributes are preserved ────────────────────
Error in `sample_frac(., size = size, replace = replace, weight = !!weight)`: `size` of sampled fraction must be less or equal to one.
ℹ set `replace = TRUE` to use sampling with replacement.
ℹ The error occurred in group 3: idD = 3.
Backtrace:
▆
1. ├─... %>% expect_equal(2) at test-sim_sample.R:26:2
2. ├─testthat::expect_equal(., 2)
3. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
4. │   └─rlang::eval_bare(expr, quo_get_env(quo))
5. ├─base::as.data.frame(.)
6. ├─saeSim:::as.data.frame.sim_setup(.)
7. │ ├─sim_run_once(x) %>% ...
8. │ └─saeSim:::sim_run_once(x) …
```
> protect size quosure in `sample_frac()`

- src/filter.cpp
- tests/testthat/_snaps/filter.md
- tests/testthat/test-filter.r
closes #6082
This would fix `ggcharts` against 1.0.8
> allow matrics with 1 column in filter(), with a warning.

- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
- matrices with one column ok
- more columns : error from vec_cast()
This is similar to what is done for `filter()`, but should be reworked as part of #6091. 
This deals with https://github.com/natydasilva/PPforest/pull/2 from this end.
> handle matrices in slice()

- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
``` r
df <- data.frame(x = 1:2)
gdf <- group_by(df, x)
slice(gdf, matrix(c(1, 2), ncol = 2))
#> Error in `slice()`:
#>   Problem while checking indices.
#>   ℹ The error occurred in group 1: x = 1.
#> Caused by error in `vec_cast()`:
#>   Can't convert <integer[,2]> to <integer>.
#>   Cannot decrease dimensions.
slice(gdf, "a")
#> Error in `slice()`:
#>   Problem while checking indices.
#>   ℹ The error occurred in group 1: x = 1.
#> Caused by error:
#>   Invalid result of type <character>.
#>   ℹ Indices must be positive or negative integers.
slice(gdf, c(1, -1))
#> Error in `slice()`:
#>   Problem while checking indices.
#>   ℹ The error occurred in group 1: x = 1.
#> Caused by error:
#>   Indices must be all positive or all negative.
#>   ℹ Got 1 …
```
> wrap slice_combine() errors

- R/sample.R
- R/slice.R
- tests/testthat/_snaps/rowwise.md
- tests/testthat/_snaps/sample.md
- tests/testthat/_snaps/slice.md
- tests/testthat/test-rowwise.r
- tests/testthat/test-slice.r
reboot of #6111 
`slice.sf()` is indeed called when calling `slice_sample(<sf>)`: 
``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
nc <- st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source 
#>   `/Users/romainfrancois/.R/library/4.0/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> Geodetic CRS:  NAD27
nc$area_cl = cut(nc$AREA, c(0, .1, .12, .15, .25))
nc <- nc %>% group_by(area_cl) 
nc %>% slice(1:2)
#> Simple feature collection with 8 features and 15 fields
#> Geometry type: MULTIPOLYGON
#> Dimension: …
```
> have `slice_helpers()` call `slice()`

- R/deprec-do.r
- man/do.Rd
Hello,
This PR aims to fix a minor grammar issue in the documentation of the now deprecated `do` function.
Thank you,
NelsonGon 
(Failed to redocument due to `rlang` not being uptodate on my side).
> Fix grammar in deprecated do

- R/generics.R
- R/reexport-tibble.r
``` r
library(data.table)
d1 <- data.table(x = 1)
attr(d1, "foo") <- "bar"
d2 <- dplyr:::dplyr_col_select(d1, "x")
attr(d2, "foo")
#> [1] "bar"
```
<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
as opposed to losing the attribute: 
``` r
library(data.table)
d1 <- data.table(x = 1)
attr(d1, "foo") <- "bar"
d2 <- dplyr:::dplyr_col_select(d1, "x")
attr(d2, "foo")
#> NULL
```
<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
however, this only works with the dev version of `data.table` thanks to: https://github.com/Rdatatable/data.table/pull/4909
This is related to: https://github.com/fndemarqui/covid19br/pull/1
> `dplyr_col_select()` reconstructs bare data.table objects

- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
related to https://github.com/Nowosad/motif/issues/66
> Fix `slice_sample()` handling of `n=` and `prop=`

- vignettes/programming.Rmd
Although the hyphen is optional, one can easily argue that 'How-tos' is preferable to 'How tos'. A non-native speaker may not understand that the expression refers to an object (a guide), so it may look up the definition of 'tos'. Using 'How-tos' helps in this sense, as it indicates that it is a single expression.
> Adding an hyphen in How tos

- NEWS.md
- R/conditions.R
- R/rows.R
- man/rows.Rd
- tests/testthat/_snaps/conditions.md
- tests/testthat/_snaps/rows.md
- tests/testthat/test-conditions.R
- tests/testthat/test-rows.R
Closes #5588 (supersedes it)
Closes #5553 
Related to an error when `y` has zero columns that I fixed:
Closes #6179 
Closes #6061
This PR updates the rows functions using part of the plan outlined at the bottom of this comment https://github.com/tidyverse/dplyr/pull/5588#issuecomment-1048373544. Specifically, it mainly does two things:
- Allows duplicate keys in `x` unconditionally
- Allows duplicate keys in `y` for `rows_insert()` and `rows_delete()`
I also refreshed the error messages to be more descriptive.
This is motivated by practical usefulness of these functions on local data frames (i.e. #5553).
The important thing to think about here is that if these checks are required, then they can be done ahead of time outside the `rows_*()` function using something like:
- `enforce()` for …
> Allow duplicate `x` keys in `rows_*()` (and sometimes allow duplicate `y` keys)

- src/group_by.cpp
Closes #6192 
On my Mac, `<vector>` includes `<algorithm>` (I can see it in the vector header file itself), but it isn't good practice to rely on this hidden dependency
> Include `<algorithm>` header since we use `std::fill()`

- DESCRIPTION
- R/slice.R
- tests/testthat/_snaps/bind.md
- tests/testthat/_snaps/conditions.md
- tests/testthat/_snaps/select.md
- tests/testthat/_snaps/slice.md
- Updated two snapshots related to internal errors now mentioning the package name
- Require rlang >= 1.0.2 as this isn't much to ask of the user, and ensures that we are all developing with a version of rlang that gives consistent snapshots
> Update to rlang 1.0.2 snapshots

- NEWS.md
- R/rows.R
- man/rows.Rd
- tests/testthat/_snaps/rows.md
- tests/testthat/test-rows.R
Follow-up to #6199 and continuation of the plan from here https://github.com/tidyverse/dplyr/pull/5588#issuecomment-1048373544
Closes #5984 
Closes #5699 
This PR adds a new `conflict` argument to `rows_insert()`, `rows_update()`, `rows_patch()`, and `rows_delete()`, inspired by the `ON CONFLICT *` command from SQL's `INSERT`.
- For `rows_insert()`, a conflict arises if there is a key in `y` that _already_ exists in `x`. By default, it `"error"`s, but you can now also `"ignore"` the rows in `y` where this occurs, which is like `ON CONFLICT DO NOTHING`.
- For `rows_update()`, `rows_patch()`, and `rows_delete()`, a conflict arises if there is a key in `y` that _doesn't_ exist in `x` (because the behavior is then ambiguous). Again, by default it `"error"`s, but you can also `"ignore"` those …
> Implement `conflict` and `unmatched` arguments for the `rows_*()` family

- NEWS.md
- R/rows.R
- R/utils.r
- tests/testthat/_snaps/rows.md
- tests/testthat/test-rows.R
This also ensures that we only use data frame operations that we have documented that we use internally. Specifically, this avoids `df[i, j]` (and its assignment variant) which suffers from `drop = FALSE` issues with bare data frames. It is replaced with usage of `df[i]`, `dplyr_row_slice()`, and `dplyr_col_modify()`. Tests have been added to ensure that we never regress here.
Preserving the column types in `x` was something that we already document, but this wasn't actually occurring correctly. Instead, we often ended up taking the common type (especially with bare data frames).
> Ensure that `rows_*()` preserves the type of `x`

- NEWS.md
- R/funs.R
- man/between.Rd
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- src/dplyr.h
- src/funs.cpp
- src/init.cpp
- tests/testthat/_snaps/funs.md
- tests/testthat/test-funs.R
Closes #6183
- Supports more input types
- No longer requires scalar left/right
- Bounds are cast to type of `x`
- Bounds are recycled to size of `x`
See also my funs PR where I discuss the enhancements I made there and talk a little about performance https://github.com/tidyverse/funs/pull/78. This is basically a port of that.
---
Revdep run shows 6 failures that seem to be related to `between()` getting a little stricter (related to the fact that `left` and `right` are cast to the type of `x`, so you can't do `between(1L, -Inf, Inf)`, for example). It says 9 failures but 3 are related to a failing internet resource. This seems reasonable.
Might need to adjust the NEWS bullet to talk more about the strictness.
> Rewrite `between()` with vctrs

- tests/testthat/test-count-tally.r
- tests/testthat/test-nth-value.R
- tests/testthat/test-summarise.r
Surfaced by the new `lintr::expect_null_linter()`.
Filing wondering:
- Interest in applying the upcoming `testthat` consistency linters slated to be added to `lintr` to `dplyr`, see `Expect*` linters in https://github.com/r-lib/lintr/issues/884
- Interest more generally in these changes for tidyverse repos
And also looking for feedback on how appropriate the lint is for usages in CRAN packages. Thanks.
> use expect_null where appropriate

- tests/testthat/test-bind.R
- tests/testthat/test-deprec-funs.R
Similar to #6211 -- caught with `lintr::expect_type_linter()`.
> Use expect_type where appropriate

- NEWS.md
- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
Closes #6271 
I think that rather than updating the documentation, we could just give a better error in the case where the user isn't sampling with replacement and the number of requested rows exceeds the number of rows in the data.
I feel like the error below is a nice improvement. I'm willing to accept the fact that the case you see below is the edge case of `1 rows are present` rather than `1 row is present` since we haven't gone all in on cli in dplyr yet (with its pluralization features).
``` r
library(dplyr)
df <- tibble(
group = rep(c("a", "b", "c"), c(1, 2, 4)),
x = runif(7)
)
df %>% 
group_by(group) %>% 
slice_sample(n = 2)
#> Error in `slice_sample()`:
#> ! Problem while computing indices.
#> ℹ The error occurred in group 1: group = "a".
#> Caused by error:
#> ! Can't sample …
```
> Catch the `slice_sample()` case of `replace = FALSE` and `n < size`

- vignettes/colwise.Rmd
- vignettes/rowwise.Rmd
Related to https://github.com/rstudio/rstudio/issues/11273#issuecomment-1150341589
So that `vignette()` gets more interesting data than: 
```r
> v <- vignette("colwise", "dplyr")
> str(v)
List of 7
$ Package: chr "dplyr"
$ Dir    : chr "/Users/romainfrancois/.R/library/4.2/dplyr"
$ Topic  : chr "colwise"
$ File   : chr "colwise.Rmd"
$ Title  : chr "colwise"
$ R      : chr "colwise.R"
$ PDF    : chr "colwise.html"
- attr(*, "class")= chr "vignette"
```
In https://github.com/rstudio/rstudio/issues/11273 the vignette title is picked up and displayed in the popup:
> Update VignetteIndexEntry for colwise vignette

- tests/testthat/test-arrange.r
Closes #6268 
Actually fixed in #6263 with the switch to `vec_order_radix()` which simplified `arrange_rows()`
> Test that `arrange()` works correctly with data frame proxies

- DESCRIPTION
- tests/testthat/_snaps/arrange.md
- tests/testthat/_snaps/distinct.md
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/group-by.md
- tests/testthat/_snaps/join.md
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/summarise.md
Should be followed up with a fix for https://github.com/tidyverse/dplyr/issues/6308, but for now this allows CI to pass
Two main changes:
- Exposes the #6308 issues
- Shows a better error call for `arg_match0()` in some of the join tests
> Update to rlang 1.0.3

- R/join-by.R
- man/join_by.Rd
This eliminates the very long description in favour of a new "join types" section.
> Tweak join_by() docs

- NEWS.md
- R/case_when.R
- R/utils-format.r
- R/vec-case-when.R
- data-raw/starwars.R
- man/case_when.Rd
- tests/testthat/_snaps/case-when.md
- tests/testthat/_snaps/vec-case-when.md
- tests/testthat/test-across.R
- tests/testthat/test-case-when.R
- tests/testthat/test-colwise-select.R
- tests/testthat/test-vec-case-when.R
Closes #6261 
Closes #6206 
Closes #5106
Closes #6145 
Closes #6225 
Supersedes #6286 
This is a more conservative update of `case_when()` vs what was done in #6286. There shouldn't be any breaking changes here (but ill run revdeps), and it should make everyone pretty happy.
The intention is to move `vec_case_when()` to vctrs and rewrite in C, but getting the semantics right in R is more important for now.
`vec_case_when()` will also be used to back `if_else()` and `coalesce()` for sure. I think it could also back `na_if()`.
---
Important notes:
- I have decided to keep the formula interface. I think my main complaint about `case_when()` is less about the formula interface, and more about `TRUE ~`. It also doesn't seem like we are going to add a multi-condition `mutate_when()` that would …
> Rewrite `case_when()` using `vec_case_when()`

- DESCRIPTION
- NEWS.md
- R/if_else.R
- man/if_else.Rd
- tests/testthat/_snaps/if-else.md
- tests/testthat/test-if-else.R
Closes #6243 
- Now takes the common type of `true`, `false`, and `missing`
- No longer need strongly typed `NA` values (due to the above point)
- New `size` and `ptype` args
- Now works with more value types, like data frames and rcrds
This PR adds a remote on dev vctrs, to be able to reference `vector_recycling_rules` (yay!)
> Implement `if_else()` on top of `vec_case_when()`

- NEWS.md
- R/all-equal.r
- R/group-by.r
- R/grouped-df.r
- R/locale.R
- man/group_by.Rd
- tests/testthat/_snaps/grouped-df.md
- tests/testthat/_snaps/locale.md
- tests/testthat/helper-encoding.R
- tests/testthat/test-grouped-df.r
- tests/testthat/test-locale.R
Supersedes #6018, too out of date
Closes #4406 
Linked tidyup, https://github.com/tidyverse/tidyups/blob/main/006-dplyr-group-by-ordering.md
Main changes:
- `group_by()` now internally computes and orders groups with `vec_locate_sorted_groups()`, which is often much faster than the previous approach
- `group_by()` now internally sorts character vector group columns in the C locale rather than the system locale. This affects the ordering of the result of functions that use the group data, like `summarise()` and `group_split()`. Note that this is consistent with the new default of `arrange()`, which also uses the C locale.
- A temporary boolean global option, ~`dplyr.legacy_group_by_locale`~ `dplyr.legacy_locale`, has been added that allows users to revert back to respecting the system …
> Update `group_by()` algorithm to utilize `vec_locate_sorted_groups()`

- vignettes/base.Rmd
When comparing to `select(df, starts_with("x"))`, the grepl function had inverted arguments.
> [vignettes/base.Rmd] Fix function arguments order

- NEWS.md
- R/na_if.R
- man/na_if.Rd
- tests/testthat/_snaps/na-if.md
- tests/testthat/test-na-if.R
We talked about making `na_if()` work in a match-like way, like `na_if(x, c("bad", "NA"))`, but I no longer think we should do that. While that might be more useful, I think:
- It would break existing code where people are currently supplying vector `y` values and expect `==` to be used, which does seem to come up on a quick GitHub scan
- It would no longer match `NULLIF()` from SQL, which it is advertised as mimicking. The Microsoft SQL docs state that `NULLIF(e1, e2)` should be treated as a "searched CASE expression", meaning that the following should be exactly equivalent
```
NULLIF(e1, e2)
CASE  
WHEN e1 = e2 THEN NULL  
ELSE e1  
END 
```
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/nullif-transact-sql?view=sql-server-ver16#remarks
If people want a match-like …
> Rewrite `na_if()` using vctrs

- NEWS.md
- R/relocate.R
- man/relocate.Rd
- tests/testthat/test-relocate.R
Closes #6301 
Closes #6209 
Alternative approach vs #6301. I actually don't think we should error here. I think we should take the _last_ name change when a column is renamed multiple times while it is being moved.
CRAN behavior takes the _first_ change, which I feel is wrong:
``` r
library(dplyr)
df <- tibble(a = 1)
relocate(df, x = a, y = a)
#> # A tibble: 1 × 1
#>       x
#>   <dbl>
#> 1     1
```
This PR takes the _last_ name change, which is more consistent with `rename()`:
``` r
library(dplyr)
df <- tibble(a = 1)
relocate(df, x = a, y = a)
#> # A tibble: 1 × 1
#>       y
#>   <dbl>
#> 1     1
rename(df, x = a, y = a)
#> # A tibble: 1 × 1
#>       y
#>   <dbl>
#> 1     1
```
I think this generally makes a little more sense too. We could error here, but I feel like this is a little …
> Retain only the last duplicate when a column is renamed multiple times in `relocate()`

- NEWS.md
- R/count-tally.R
- R/zzz.r
- tests/testthat/test-count-tally.r
Closes #6338 
Closes https://github.com/tidyverse/dbplyr/issues/940
See https://github.com/tidyverse/dplyr/issues/6338#issuecomment-1189423451 for the full diagnosis
@mgirlich could you please confirm that this is working as you expect? I think I've gotten it right, but you know more about dbplyr. You might want to add a test that is similar to the one here on the dbplyr side as well.
`"c5253d35-98ae-4a66-a3b7-78e93d321fd3"`
> Remove `tbl_sql` methods for `count()` and `tally()`

- NEWS.md
- R/distinct.R
- tests/testthat/test-distinct.R
> Prefer `dplyr_col_select()` over `[` to retain attributes in `distinct()`

- NEWS.md
- R/data-mask.R
- tests/testthat/_snaps/arrange.md
- tests/testthat/_snaps/distinct.md
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/group-by.md
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/summarise.md
Closes #6308.
This was a bit tricky because the `call` for these top-level errors is created by R itself, before calling `.handleSimpleError()`. To fix these, I wrapped the evaluation routine in a function called `eval()` which rlang ignores by default.
> Prevent mask methods from being mentioned in error calls

- NEWS.md
- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.r
closes #6185 
This PR silently caps slice size at `n()` for `slice_sample(..., replace = FALSE)` e.g. 
``` r
data.frame(a = 1) %>% 
slice_sample(n = 2)
#>   a
#> 1 1
```
The timeline on this, as I understand it:
- In #5962, when adding support for negative `n` and `prop` in slice functions, I moved calculation of "slice size" to one function for all slice helpers. This function (silently) bounded all sizes between `0` and `n()`. I didn't realize, though, that  `slice_sample(..., replace = TRUE)`, allowed users to produce groups with more than `n()` rows, and so in doing this I changed that behavior.
- In revdeps before releasing 1.0.8 it [was found](https://github.com/Nowosad/motif/issues/66) that this change broke a package, and so #6172 reverted to the old behavior for …
> Silently cap `slice_sample()` slice size at `n()` when `replace = FALSE`

- NEWS.md
- R/mutate.R
- R/rows.R
- man/mutate.Rd
- man/rows.Rd
I think these are unquestionably useful. Other experimental functions that I left as is are the `dplyr_*` generics, `group_map()`/`group_walk()`/`group_nest()`/`group_split()`/`group_trim()`, `with_groups()`, and `nest_by()`. I don't see any reason that these would go away, but it feels like we still want to reserve the right to play around with them still.
Fixes #6110
> Mark mutate() args + row_* as no longer experimental

- NEWS.md
- R/across.R
- tests/testthat/test-across.R
- tests/testthat/test-mutate.r
Closes #6380 (alternative)
Closes #6264
@hadley I think I like this approach more?
- It seems a lot simpler to me
- It avoids a new argument to `current_cols()` (which I think shouldn't ever alter the cols if possible)
- It matches the spirit of what an official `pick()` function would do. It would be semantically the same as `across(.fns = NULL)`, so it is nice to see that we internally use `$pick()` for the `across(.fns = NULL)` code path.
I think this further supports the need for `pick()`. It would allow us to "purify" `across()` a bit more with rowwise data frames. Once we deprecate `.fns = NULL`, `across()` would _always_ work directly on list column elements VS `pick()` which would _always_ preserve the full list-column as-is
> Use `$pick()` when `across(.fns = NULL)` is specified

- NEWS.md
- R/relocate.R
- tests/testthat/_snaps/relocate.md
- tests/testthat/test-mutate.r
- tests/testthat/test-relocate.R
Closes #5829 (but we'd still need to move this to tidyselect)
Closes #6167 
Closes #6341 
This PR pulls `eval_relocate()` out of `relocate.data.frame()`. The eventual goal would be to move this to tidyselect for other backends to use it (#5829) but this is a good first step.
The `before` and `after` arguments of `eval_relocate()` take defused input, or `NULL`, which feels right given that `expr` works basically the same way.
`eval_relocate()` returns a named integer vector the same size as `ncol(data)` (important invariant) that describes how to rearrange the columns of `data`. The names are normally the same as the original data, but renaming can happen in `expr` so it is possible for them to be different.
I fixed a few edge case bugs in the implementation of `eval_relocate()`. Mainly …
> Factor out `eval_relocate()` and use `dplyr_col_select()` in `relocate()`

- R/generics.R
- R/relocate.R
- R/select.R
It has bugged me that "col select" also handles renaming, since most of the time it isn't used that way. It isn't hard to separate this renaming bit out, so I did that here
> Make `dplyr_col_select()` purely about selection

- R/across.R
- R/context.R
- tests/testthat/_snaps/across.md
- tests/testthat/_snaps/context.md
* Capture call rather than function name in `peek_mask()` and `context_peek()`
* Require `location` in `context_peek()`
* Make `peek_mask()` location more specific
* Require mask in `across_setup()` and `c_across_setup()`
Fixes #6403
> Improve peek_mask() errors

- R/slice.R
- man/slice.Rd
- tests/testthat/test-slice.r
I think this does a better job of conveying how negative values work. The previous explanation made me think that `bind_rows(slice_head(df, n = 5), slice_head(df, n = -5))` would yield `df`.
> Clarify tests/docs for negative n/prop

- R/conditions.R
- R/context.R
- R/data-mask.R
- R/rowwise.r
Working on `mutate(.when =)` (#6313) showed that having `$full_data()` was a bit dangerous because the original data might now always reflect the real state of the data mask, i.e. with `.when` the real data was the original data sliced to where `.when` was `TRUE`.
Removing `$full_data()` actually makes it very easy to remove `private$data` too, which seems like a nice simplification
> Eliminate `mask$full_data()` and `private$data`

- R/data-mask.R
It should always be a `list_of<integer>`. This doesn't have any practical effect here, but I think it is better practice
This is another thing noticed in #6313
> Ensure that `rows` is type stable

- NEWS.md
- R/conditions.R
- R/count-tally.R
- R/group-by.r
- tests/testthat/_snaps/count-tally.md
- tests/testthat/_snaps/distinct.md
- tests/testthat/_snaps/group-by.md
- tests/testthat/test-count-tally.r
Closes #6139.
Also makes `dplyr_error_call()` recursive so that, for example, `mutate()` errors transferred to `add_tally()` can be transferred to `add_count()`.
> Fix ownership of errors thrown by internal dplyr steps

- NEWS.md
- R/data-mask.R
- tests/testthat/test-context.R
> Patch `current_key()` to work with zero row grouped data frames

- R/join-by.R
- tests/testthat/_snaps/join-by.md
- tests/testthat/_snaps/join.md
- tests/testthat/test-join-by.R
We already have `tick_if_needed()` .
Closes #6448.
> Mention `join_by()` when `by` argument is omitted in joins

- NEWS.md
- R/nth-value.R
- R/order-by.R
- `nth(order_by =)`
- `with_order()`
This means that `vec_order_base()` is now only used in the `dplyr.legacy_locale` code path of `group_by()`. And I might be able to remove that in another PR by using `dplyr_order_legacy()`, which is used in the `arrange()` legacy path. I'll take a look.
I did not feel like this needs a news bullet, because it is highly unlikely to affect much code, and we don't provide a way to opt out of this.
> Switch to radix ordering in more places

- R/arrange.R
- R/grouped-df.r
- R/zzz.r
We already have `dplyr_order_legacy()` for `arrange()`, which is slightly different from `vec_order_base()` because it allows you to use a vectorized `direction` argument.
Since `arrange()` already needed a custom version of `vec_order_base()`, we might as well adapt it to be usable by the legacy path of `group_by()` as well.
That means:
- Both `arrange()` and `group_by()` use the exact same legacy ordering helper
- We don't need to import `vctrs:::vec_order_base()`, which simplifies things a bit and means we definitely don't need it in vctrs anymore
So now we just have to worry about managing `vec_order_radix()`
> Use `dplyr_order_legacy()` and remove `vec_order_base()`

- NEWS.md
- R/join-by.R
- man/join_by.Rd
- tests/testthat/_snaps/join-by.md
- tests/testthat/test-join-by.R
Closes #6439 
I think this is much nicer. It was easier to talk about in the docs, and the progression from
```r
join_by(id, sale_date >= promo_date)
```
to
```r
join_by(id, closest(sale_date >= promo_date))
```
in the examples is now much easier to understand
> Remove `preceding()` and `following()` in favor of `closest()`

- NEWS.md
- R/filter.R
- src/filter.cpp
- tests/testthat/_snaps/filter.md
- tests/testthat/test-filter.R
Closes #6091 
Went with `deprecate_warn()` rather than `deprecate_soft()` because filtering by a 1 column matrix should be sufficiently rare enough that we can skip a step in the deprecation process.
> Deprecate usage of 1 column matrices in `filter()`

- R/conditions.R
- tests/testthat/_snaps/across.md
- tests/testthat/_snaps/arrange.md
- tests/testthat/_snaps/colwise-mutate.md
- tests/testthat/_snaps/conditions.md
- tests/testthat/_snaps/count-tally.md
- tests/testthat/_snaps/distinct.md
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/group-by.md
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/slice.md
- tests/testthat/_snaps/summarise.md
I realised that:
- The "compute" and "process" verbs don't bring any information.
- Having `!` bullets in contextual errors that only display contextual information without reformulating the causal error in a higher level way is distracting.
This PR simplifies contextual errors by using "i" bullets starting with "In argument", as in #6477.
I kept `!` bullets for recycling errors though because "Can't recycle" is informative.
> Simplify contextual errors with "i" bullets

- NEWS.md
- R/join-cols.R
- R/join-rows.R
- R/join.R
- tests/testthat/_snaps/join-cols.md
- tests/testthat/_snaps/join-rows.md
- tests/testthat/_snaps/join.md
- tests/testthat/test-join-cols.R
- tests/testthat/test-join-rows.R
- tests/testthat/test-join.R
Closes https://github.com/tidyverse/dplyr/issues/6465
This was slightly more work than expected. I ended up making the common cast operation more explicit, as currently it is implicit in the `vec_locate_matches()` call.
Pulling it out into `join_cast_common()` felt better than trying to pass `vars` through to `join_rows()`, which otherwise wouldn't need to know anything about `vars`. Casting early also allowed me to remove some code that was recomputing the common type again.
> Use original `y` name in join common type error message

- DESCRIPTION
- R/bind-cols.R
- R/bind-rows.R
- R/coalesce.R
- R/nth-value.R
- R/rank.R
- `.error_call` not `.call`
- `vec_detect_missing()` not `vec_equal_na()`
> Update to latest vctrs features

- DESCRIPTION
- R/across.R
- R/colwise-funs.R
- R/colwise-mutate.R
- R/defunct.R
- tests/testthat/_snaps/colwise-mutate.md
- tests/testthat/_snaps/defunct.md
- tests/testthat/test-colwise-mutate.R
- Pass bullets instead of formatted strings. This is compatible with both CRAN and dev lifecycle.
- Pass `user_env` to `deprecate_warn()` to differentiate between direct and indirect calls. This requires dev lifecycle.
> Update to latest lifecycle

- tests/testthat/test-arrange.R
Closes #6490 
This was actually the same problem as https://github.com/tidyverse/dplyr/issues/6268 and has already been fixed in the dev version, but I'm adding another regression test since this involved `across()`
> Test that `arrange()` breaks ties correctly when used with `across()`

- R/join-by.R
- tests/testthat/_snaps/join-by.md
- tests/testthat/test-join-by.R
Closes #6469 
To allow `{{ }}`, since `enexprs()` doesn't allow that.
I spent quite a bit of time yesterday re-convincing myself that this is the best way to handle this, and I think it is.
> Use `enquos()` + `quo_squash()` in `join_by()`

- R/join-by.R
- man/join_by.Rd
- tests/testthat/_snaps/join-by.md
- tests/testthat/test-join-by.R
- tests/testthat/test-join.R
Closes #6488 
Highlights of my analysis in #6488:
- Kept `[]` default in `between()` and `overlaps()` for compatibility with `dplyr::between()` and how I think these are most likely to be used
- `between()` gains `bounds = "[]"` because `[]`, `[)`, and `()` all have their uses (and `(]` is then for completeness)
- `overlaps()` gains `closed = TRUE` because `xl <= yu, xu >= yl` covers `[]` and `xl < yu, xu > yl` covers the other 3 partially/fully open range cases.
- The binary conditions for `within()` are the same regardless of the inclusiveness of the range boundaries, so it doesn't gain any new arguments.
This would allow me to talk about `between(bounds = "[)")` and `overlaps(closed = FALSE)` in ivs, which would align with `iv_locate_between()` and `iv_locate_overlaps()`.
And R4DS …
> Add `between(bounds =)` and `overlaps(bounds =)`

- R/join-cols.R
- R/join.R
- man/mutate-joins.Rd
- tests/testthat/_snaps/join-cols.md
- tests/testthat/_snaps/join.md
- tests/testthat/test-join-cols.R
- tests/testthat/test-join.R
Closes #6499 
See https://github.com/tidyverse/dplyr/issues/6499#issuecomment-1276346314 for rationale and good examples of why we shouldn't allow `keep = FALSE` with non-equi joins. Those examples have been turned into snapshot tests that now error informatively.
> Disallow `keep = FALSE` with non-equi conditions

- NEWS.md
- R/arrange.R
- tests/testthat/test-arrange.R
Closes #6495 
I've ended up with an approach that just evaluates each expression provided to `arrange()` in its own `mutate()` call. I don't expect the performance here to matter because it is always on ungrouped data frames and the `mutate()` call itself has a fairly small amount of overhead.
This means that each `across()` call will be evaluated on the original data, preventing `everything()` from accessing dummy columns added after evaluating earlier expressions.
I'm actually still using `..1`, `..2`, etc as the column names here, because they need to be called _something_ and that something ends up as part of the error message, so this seemed like the best option.
> Evaluate each expression in `arrange()` separately

- R/consecutive-id.R
- R/n-distinct.R
- tests/testthat/_snaps/consecutive-id.md
- tests/testthat/_snaps/n-distinct.md
- tests/testthat/test-consecutive-id.R
Follow up to https://github.com/tidyverse/dplyr/pull/6381
- Better error calls with `.error_call`
- Setting `.unpack = FALSE` which at this point is for theoretical reasons, because we solved the only practical issue that could arise in `n_distinct(na.rm = TRUE)` in https://github.com/tidyverse/dplyr/pull/6381#discussion_r941352917
> Use `df_list()` in `n_distinct()` and `consecutive_id()`

- NEWS.md
- R/across.R
- R/conditions.R
- R/context.R
- man/across.Rd
- man/c_across.Rd
- tests/testthat/_snaps/across.md
- tests/testthat/test-across.R
Follow up to #6492 
`.cols` and `.fns` are now required for `across()`, `c_across()`, `if_all()`, and `if_any()`.
We recommend in the NEWS that you use `pick()` instead of `across(.fns = NULL)`, which was the most common case of how people relied on these defaults
~This deprecation is currently hidden, all calls to these functions that rely on the previous defaults still work with no messages or warnings. I think that is definitely the right thing to do for `.fns = NULL`, because people would often do `across(c(x, y))` to mimic what `pick()` now does, and previously there was no other option. But I wonder if we could go ahead and soft deprecate the `.cols` case?~ The deprecation is hidden for `.fns = NULL`, but we now use `deprecate_warn()` for missing `.cols`
> Quietly deprecate optional `.cols` and `.fns` cases

- NEWS.md
- R/summarise.R
- src/dplyr.h
- src/init.cpp
- src/summarise.cpp
- tests/testthat/test-pick.R
- tests/testthat/test-summarise.R
Closes https://github.com/tidyverse/dplyr/issues/6509
``` r
df <- tibble(x = 1:3)
summarise(df, sum = sum(x), empty = tibble())
#> # A tibble: 0 × 2
#> # … with 2 variables: sum <int>, empty <tibble[,0]>
summarise(df, sum = sum(x), empty = new_tibble(list(), nrow = 3))
#> # A tibble: 3 × 2
#>     sum empty       
#>   <int> <tibble[,0]>
#> 1     6             
#> 2     6             
#> 3     6
```
This reverts most of https://github.com/tidyverse/dplyr/pull/5088, but the tests that were added there still pass. This is because _unnamed_ data frames are actually already handled on the R side these days. They get auto-spliced ahead of time into their individual columns, which effectively makes 0-column data frames disappear.
https://github.com/tidyverse/dplyr/blob/02ef1d7c2de2bd70252a124004b …
> Recycle 0-column data frames in `summarise()` when they are named

- NEWS.md
- R/across.R
- tests/testthat/_snaps/across.md
- tests/testthat/test-across.R
Closes #6522 
I knew something was fishy here. We needed to use `quo_set_env_to_data_mask_top()` in `c_across()` like we already do for `pick()` and `across()`. Without it, `all_of()` didn't work correctly and we were accidentally allowing grouping variables to be selected.
While I was there, I also:
- Passed the `error_call` through to `eval_select()` for better error calls
- Set `allow_rename = FALSE` to get a better error message. It already threw an error, but it was an obscure one.
> Fix `c_across()` quosure environment and disallow renaming

- DESCRIPTION
- R/join-rows.R
- R/join.R
- tests/testthat/_snaps/join.md
- tests/testthat/test-join.R
This uses the same code as `lifecycle::deprecate_soft()`, which means that the following two cases _do_ still get the warning:
- dplyr users that directly call the join functions will see the warning
- Package authors that directly call join functions in their package code will see the warning in their tests
But users or package authors who _indirectly_ call a join function through some other package will not see the join warning, because they likely won't have access to `multiple` to silence it (there are probably some exceptions to this, like packages that write S3 methods for the join functions and would expose `multiple` in their method, but I'm willing to live with accidental silence there).
For example, pretty much any package author or user who called `tidyr::complete()` was …
> Only throw the `multiple` warning on "direct" calls to join functions

- R/across.R
- tests/testthat/_snaps/across.md
Closes #6567 
- Modified dots deprecation warning in `across()`
- Updated snapshot test accordingly
> Modified across dots deprecation warning

- R/select.R
- man/rmd/select.Rmd
- man/select.Rd
roxygen2 now sets `crayon.enabled`, `cli.unicode`, and `width` for us in inline code chunks. It also sets the knitr options `comment = "#>", collapse = TRUE` so we don't need that either.
Also added the `pillar.min_title_chars = 20` option to the `select.Rmd` rendering, as this is going to be the new pillar default in the next release. Since I already set this in my `.Rprofile`, it was changing `select.Rd` every time I ran document interactively, which was annoying
> Use latest roxygen2 local reproducible defaults

- R/slice.R
Minor bug I discovered while poking around `slice_rows()`
In main:
```r
impl <- function(...) {
dplyr:::...length2()
}
impl()
#> [1] 1
impl(1)
#> [1] 1
impl(1, 2)
#> [1] 2
```
This PR
``` r
impl <- function(...) {
dplyr:::...length2()
}
impl()
#> [1] 0
impl(1)
#> [1] 1
impl(1, 2)
#> [1] 2
```
The problem is that when you don't supply any dots, `env_get(nm = "...")` ends up returning a missing-arg rather than a DOTSXP, which has a `length()` of 1.
`...length()` does work correctly in this case, but it does so by defining this special `length_DOTS()` macro that avoids this issue https://github.com/wch/r-source/blob/431d589d479358a11ace2a0b7443fb519bf0ce05/src/main/envir.c#L1410
CC @lionel- you might be interested in this corner case
> Fix `...length2()` with missing dots

- R/group-split.R
- man/group_split.Rd
Closes https://github.com/tidyverse/dplyr/issues/6510
I think we mainly just need to tweak the documentation here
> Mention the `<list_of>` class in the return value of `group_split()`

- NEWS.md
- R/rename.R
- tests/testthat/_snaps/rename.md
- tests/testthat/test-rename.R
> Add more error checking to `rename_with()`

- NEWS.md
- R/slice.R
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/test-slice.R
This revisits a point brought up in https://github.com/tidyverse/dplyr/issues/2252
I went to remove the early exit in `slice_rows()` and discovered it was actually being used to ensure that `slice()` with no `...` returns all rows. I think this is theoretically inconsistent.
I think that if we have:
```r
df <- data.frame(x = 1:2)
```
then:
```r
filter(df)
c(TRUE, TRUE)
```
and:
```r
slice(df)
integer()
```
This is inline with the logic mentioned here:
https://github.com/tidyverse/dplyr/issues/2252#issuecomment-260128765
And with these two examples:
``` r
df <- data.frame(x = 1:2)
slice(df, c())
#> [1] x
#> <0 rows> (or 0-length row.names)
slice(df, 1, 1)
#>   x
#> 1 1
#> 2 1
```
And it allows us to remove the early exit, which to me has always been an indication that the theoretical logic …
> Drop all rows with empty `slice()` calls

- R/join-rows.R
- R/join.R
- man/mutate-joins.Rd
- man/nest_join.Rd
- tests/testthat/_snaps/join-rows.md
- tests/testthat/_snaps/join.md
- tests/testthat/test-join-rows.R
- tests/testthat/test-join.R
Closes #6566
`unmatched` allows you to error if the input that has the _potential_ to drop rows would actually drop them. So:
- For left joins, it checks `y`
- For right joins, it checks `x`
- For inner joins, it checks `x` and `y`
- For full joins, it doesn't check either input, so `unmatched` isn't an argument to `full_join()`
We previously required that `unmatched` was a size 1 character vector, but this means that you can't control the behavior of `x` and `y` independently for inner joins. I think this is reasonable to want to be able to do. It comes up when you want each row in the `x` table to have exactly 1 match in `y`, but you don't care about what happens to unmatched rows in `y`.
This is exactly the case of the `employees` / `parties` example. You want each `employee` to be …
> Allow `unmatched` to be a size 2 character vector for inner joins

- R/slice.R
Tweaks https://github.com/tidyverse/dplyr/pull/6558
Turns out that putting `check_dots_unnamed()` in the generic means that extension authors aren't able to add their own extra arguments (this came up with the dm revdep)
```r
slice <- function(.data, ..., .by = NULL) {
rlang::check_dots_unnamed()
UseMethod("slice")
} 
slice.my_class <- function(.data, ..., .my_arg = NULL) {
list(.data, .my_arg)
}
df <- vctrs::new_data_frame(class = "my_class")
slice(df)
#> [[1]]
#> data frame with 0 columns and 0 rows
#> 
#> [[2]]
#> NULL
slice(df, .my_arg = 1)
#> Error in `slice()`:
#> ! Arguments in `...` must be passed by position, not name.
#> ✖ Problematic argument:
#> • .my_arg = 1
```
Moving the check to the method fixes that problem.
We are still left with the issue where extensions authors can't …
> Move `check_dots_unnamed()` into the method

- R/bind-rows.R
- man/bind_rows.Rd
~18 packages in https://github.com/tidyverse/dplyr/issues/6262 "failed" because they link to `bind_rows()` or `bind_cols()`, which had a topic name of `bind`, and that no longer exists now that those functions are on two different pages.
I've added a `bind` alias that goes to `bind_rows()`, since that is by far the more common one.
There are maybe 2 or 3 packages that were linking to `bind_cols()`, so this alias will redirect to `bind_rows()` for them now, but all they need to do is redocument and that will fix it, so I'm not worried.
I think CRAN would probably ignore these failures anyways, but this is an easy enough fix to get rid of them altogether
> Add a `bind` alias to `bind_rows()`

- R/join.R
- man/filter-joins.Rd
- man/mutate-joins.Rd
- man/nest_join.Rd
After a reread, it seems like talking about both character `by` and `join_by()` together is more confusing than it is worth. I think focusing on `join_by()` and mentioning character `by` at the end is much clearer and more forward thinking
> Focus more on `join_by()` in `by` docs

- R/join-by.R
- tests/testthat/_snaps/join-by.md
- No need to mention `join_by()` in the error because it is part of the call
- Otherwise updating a few of the errors to the more modern style of starting with `Can't` where it seemed useful
> Minor improvements to `join_by()` errors

- NEWS.md
- R/across.R
Closes #6620 
Alters https://github.com/tidyverse/dplyr/pull/6365
This is a new deprecation and is likely to affect quite a few people, so we should start with soft-deprecation. Practically, it came up in revdeps where the warning was being propagated through a dependency package that the revdep package author didn't control.
> Move `across()` dots deprecation from `deprecate_warn()` to `deprecate_soft()`

- R/across.R
I realised that with the lambda detection set up in #6550, we can now easily inline lambdas supplied in lists. This PR changes the detection of inlinable lambdas to use the environment-sentinel approach instead of a metaprogramming approach. This simplifies things a bit and makes the expansion behaviour more consistent and predictable.
```r
gdf <- tibble(g = seq_len(1e5), x = g) %>% group_by(g)
bench::mark(
expr = gdf %>% mutate(x_1 = identity(x), x_2 = identity(x)),
formula = gdf %>% mutate(across(x, list(~ identity(.), ~ identity(.)))),
lambda = gdf %>% mutate(across(x, list(\(.) identity(.), \(.) identity(.)))),
iterations = 20
)[1:8]
#> # Before
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:by>   <dbl> <int> <dbl>
#> 1 expr          177ms    180ms      5.54     13MB    6.10    20 …
```
> Inline lambdas supplied in lists

- NEWS.md
- R/join-cols.R
Closes https://github.com/tidyverse/dplyr/pull/6636
Alternate approach that truly vectorizes the calculation. I'm about 95% sure this is correct. It passes all tests and we do have a decent number of tests that check corner cases of `suffix` so I'm fairly confident about it.
> Vectorize `add_suffixes()`

- NEWS.md
- R/across.R
- tests/testthat/_snaps/across.md
- tests/testthat/test-across.R
Closes #6638. cc @DavisVaughan
> error in `across()` when supplied `...` without a `.fns` argument

- NEWS.md
- R/by.R
- R/filter.R
- R/slice.R
- man/dplyr_by.Rd
- man/rmd/by.Rmd
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/slice.md
- tests/testthat/test-filter.R
- tests/testthat/test-slice.R
Closes #6647
- The `?dplyr_by` docs now do a better job of documenting that you may see either one of these depending on the dplyr verb. In particular the _Supported verbs_ section now tells you which verb uses which form of `by`.
- `filter()` now catches if you accidentally type `by =`
- `slice()` now catches if you accidentally type `by =`
- `slice_*()` now catches if you accidentally type `.by =`
As mentioned in #6647, we can't catch typos in `mutate()`, `summarise()` or `reframe()`, which all use `.by`. This is because `by` is a valid column name in those cases. But since we typically talk about per operation grouping using `.by`, this is what most people will reach for, so they are less likely to be confused in these three functions.
> Better document `.by` vs `by` and catch typos in `filter()` and `slice*()`

- R/distinct.R
- man/distinct.Rd
Related to https://github.com/tidyverse/dplyr/issues/6654
Clarifies that when `...` isn't provided, uniqueness is _always_ computed using all of the variables in the data frame.
Justification of this behavior and a link to where it was implemented is contained here https://github.com/tidyverse/dplyr/issues/6654#issuecomment-1402447808
> Tweak grouped data frame examples in `distinct()`

- NEWS.md
- R/rows.R
- tests/testthat/_snaps/rows.md
- tests/testthat/test-rows.R
Closes https://github.com/tidyverse/dplyr/issues/6652
The easiest way to fix this is to realize that `rows_select_key()` was doing too much. It was doing 3 things:
- Checking that the input contained the `by` cols
- Selection with `x[by]`
- Optional uniqueness checks
I have split this into the 3 individual responsibilities:
- `rows_check_contains_by()`
- `dplyr_col_select()`
- `rows_check_unique()`
This solves the problem with `rows_insert()` because the casting of `y` to the type of `x` was happening before the check that `y` contained the `by` columns. Since `x` contained the `by` columns, the cast made it look like `y` did too. The correct ordering of the operations in `rows_insert()` is:
- `rows_check_contains_by()`
- `rows_cast_y()`
- `dplyr_col_select()`
- `rows_check_unique()` …
> Ensure that `rows_insert()` checks that `y` contains `by` before casting

- tests/testthat/test-rename.R
This only adds a test for behavior that is tested implicitly in the tests for `relocate()` .
> Explicitly test reusing column with `rename()`

- R/funs.R
- R/join-by.R
- man/between.Rd
- man/join_by.Rd
Closes https://github.com/tidyverse/dplyr/issues/6595
This is like an 85% improvement I think.
- Alias `overlaps` to `join_by()` (no conflicts)
- Alias `closest` to `join_by()` (no conflicts)
- Alias `within` to `join_by()`. Conflicts with `base::within()` so `?within` brings up 2 help pages to choose from. 🤷 
- Can't alias `between` to `join_by()` because we already have `dplyr::between()`. So instead I gave the help docs of `between()` a `@seealso` tag for `join_by()`
So now only `between()` generates a link when you are on the `join_by()` help page
And all the helpers generate links when you are on other pages like NEWS. The `overlaps()` and `within()` ones link correctly. `between()` links to `dplyr::between()`, of course.
> Add join helper aliases and link to `join_by()` from `between()`

- R/colwise-mutate.R
- R/group-nest.R
- R/group-split.R
- R/nest-by.R
- _pkgdown.yml
- man/group_nest.Rd
- man/group_split.Rd
- man/mutate_all.Rd
- man/nest_by.Rd
- man/summarise_all.Rd
Closes https://github.com/tidyverse/dplyr/issues/6639
- No NEWS bullet (I'm not really sure what it would say)
- All still experimental
- The `Life cycle` section is something rlang does. i.e. `?rlang::int`
- Marked `group_split()` as internal and removed pkgdown reference index
> Note instability of `nest_by()` and `group_nest/split()`

- R/join.R
- tests/testthat/_snaps/join.md
- tests/testthat/test-join.R
The sift package was passing a named empty `character()` object through as `by` and we didn't catch that
> Use a slightly more relaxed check for the old variant of cross join

- _pkgdown.yml
* Adds link to the dplyr-1-1-0 tag as the "Version 1.1.0" link in the Releases section of the pkgdown header. 
_n.b._ We've not done this previously (e.g. with 1.0.0, which also had several posts), but it seems to make sense in this case, as there's no one post of reference.
If we do this, it'd probably be worth adding the tag to the 1.1.0 is coming soon post (https://www.tidyverse.org/blog/2022/11/dplyr-1-1-0-is-coming-soon/)
> Add link to 1.1.0 posts to pkgdown Releases dropdown

- NEWS.md
- R/rename.R
- man/rename.Rd
Closes #6688
I think that documentation is really the best we can do here? It seems worth calling this specific case out, at least.
> Add `rename_with()` example of using `paste0(recycle0 = TRUE)`

- NEWS.md
- R/filter.R
Closes https://github.com/tidyverse/dplyr/issues/6679
We weren't passing the `user_env` through to `deprecate_warn()` (probably because it didn't exist at the time).
The example from #6679 now reports the right package
```r
df2 <- df |> tabyl(procedure_name)
#> Warning: Using one column matrices in `filter()` was deprecated in dplyr 1.1.0.
#> ℹ Please use one dimensional logical vectors instead.
#> ℹ The deprecated feature was likely used in the janitor package.
#>   Please report the issue at <https://github.com/sfirke/janitor/issues>.
```
> Pass correct `user_env` through to all `filter()` warnings

- DESCRIPTION
- NEWS.md
- R/data-mask.R
- src/chop.cpp
- src/dplyr.h
- src/filter.cpp
- src/init.cpp
- src/mask.cpp
- src/mutate.cpp
- src/slice.cpp
- src/summarise.cpp
- tests/testthat/_snaps/across.md
- tests/testthat/_snaps/join-rows.md
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/rows.md
- tests/testthat/_snaps/summarise.md
- tests/testthat/test-across.R
- tests/testthat/test-mutate.R
- tests/testthat/test-summarise.R
Closes https://github.com/tidyverse/dplyr/issues/6666
This is a bit of a tricky one.
The issues in #6666 are caused by the fact that every evaluation within a single `mutate()` call (both across multiple expressions and across groups within the same expression) share the same data mask.
This means that assignments with `<-` in one expression can affect downstream expressions or group evaluations. This is most problematic when the assignment is like `x <- ` where `x` is a column in the original data frame. That assignment will _mask_ the active binding we set up for `x`, so it will no longer evaluate to the correct expression in the following expressions or groups.
My idea here is to create a _fresh_ data mask for each individual evaluation (again, both across expressions and across …
> Evaluate each group expression in a fresh data mask

- DESCRIPTION
- NEWS.md
- tests/testthat/test-arrange.R
Closes #6680
Needs https://github.com/r-lib/vctrs/pull/1782
> Add tests for `arrange()` with `numeric_version`

- NEWS.md
- R/nth-value.R
- tests/testthat/_snaps/nth-value.md
- tests/testthat/test-nth-value.R
Closes https://github.com/tidyverse/dplyr/issues/6682
I'm not too worried about `vec_as_location2()` actually being slow right now. We can improve that later when we finally add `vec_slice2()` for real.
``` r
library(dplyr)
x <- 1:5
bench::mark(first(x), iterations = 100000)
#> # A tibble: 1 × 6
#> 1 first(x)     49.5µs   65.2µs    15182.     152KB     16.7
#> # A tibble: 1 × 6
#> 1 first(x)     18.9µs   25.2µs    38844.     133KB     15.5
```
Further improvements will come from vctrs with https://github.com/r-lib/vctrs/issues/1785 and …
> Speed up `nth()` family

- NEWS.md
- R/conditions.R
- R/utils.R
Closes https://github.com/tidyverse/dplyr/issues/6681
Here is the crux of the issue
``` r
quo <- quo(1 + 1)
bench::mark(
as_label(quo),
with_no_rlang_infix_labeling(as_label(quo))
)
#> # A tibble: 2 × 6
#>   expression                                       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                                  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 as_label(quo)                                 1.41ms   1.99ms      496.      992B    11.3 
#> 2 with_no_rlang_infix_labeling(as_label(quo))  185.4µs 247.46µs     4041.      704B     8.60
quo <- quo(mean(x) + mean(x) + mean(x) + mean(x) + mean(x) + mean(x) + mean(x) + mean(x))
as_label(quo)
#> [1] "... + mean(x)"
with_no_rlang_infix_labeling(as_label(quo))
#> [1] "+..."
bench::mark(
as_label(quo), …
```
> Use rlang private option when creating error context labels

- NEWS.md
- R/case-match.R
- R/case-when.R
- tests/testthat/_snaps/case-match.md
- tests/testthat/_snaps/case-when.md
Closes https://github.com/tidyverse/dplyr/issues/6674
Three improvements to make these decently fast again:
- Minor: Calls to `current_env()` and `caller_env()` are now lazy (only evaluated when needed) (needs https://github.com/r-lib/rlang/issues/1558)
- Major: We no longer call `as_label()` to turn the expressions into labels which were being used as informative names that showed up in error messages. This stinks, but `as_label()` is just too slow to be used eagerly like this. We can revisit this again in the future if we add a lazy ALTREP character vector which could materialize the `as_label()` calls on demand (i.e. at error time). In the meantime, we now use positional names that also include LHS/RHS information, like `..2 (RHS)`, which ends up being decent.
- Major: I was previously …
> Improve performance of `case_when()` and `case_match()`

- NEWS.md
- R/slice.R
- tests/testthat/test-slice.R
> Inject maskable arguments in `slice_*()`

- NEWS.md
- R/if-else.R
- R/utils.R
- R/vec-case-when.R
- tests/testthat/_snaps/case-when.md
- tests/testthat/_snaps/if-else.md
- tests/testthat/_snaps/vec-case-when.md
- tests/testthat/test-case-when.R
- tests/testthat/test-if-else.R
- tests/testthat/test-vec-case-when.R
Closes https://github.com/tidyverse/dplyr/issues/6678
As mentioned in #6711, this also improves the performance of `case_when()` a little further:
``` r
library(dplyr)
x <- 1L
bench::mark(
one = case_when(x == 1L ~ TRUE), 
two = case_when(x == 1L ~ TRUE, x == 2L ~ NA),
three = case_when(x == 1L ~ TRUE, x == 2L ~ NA, TRUE ~ FALSE),
iterations = 50000,
check = FALSE
)
#> # A tibble: 3 × 6
#> 1 one           172µs    251µs     3851.   498.9KB     10.8
#> 2 two           212µs    268µs     3683.     1.3KB     13.6
#> 3 three         245µs    309µs     3214.     1.3KB     14.6
#> # A tibble: 3 × 6
#> …
```
> Use `check_logical()` rather than `vec_assert()` in `if_else()` and `vec_case_when()`

- NEWS.md
- R/conditions.R
- R/context.R
- R/data-mask.R
- src/chop.cpp
- src/dplyr.h
- src/init.cpp
This PR:
- Provides access to the current group size through `$get_current_group_size()`
- Uses this helper in `n()`, which makes it a little faster
This also gives us an easy private way to access the current group size for https://github.com/tidyverse/dplyr/issues/6685#issuecomment-1430392850
It also gets rid of the need to do `parent.env(chops)` internally, which always felt a little clunky to me.
``` r
library(dplyr)
set.seed(123)
x <- sample(1e5, 1e6, replace = TRUE)
df <- tibble(x = x)
df <- group_by(df, x)
df
#> # A tibble: 1,000,000 × 1
#> # Groups:   x [99,995]
#>        x
#>    <int>
#>  1 51663
#>  2 57870
#>  3  2986
#>  4 29925
#>  5 95246
#>  6 68293
#>  7 62555
#>  8 45404
#>  9 65161
#> 10 46435
#> # … with 999,990 more rows
bench::mark(summarise(df, n = n()), iterations = …
```
> Make the current group size a variable updated by reference

- R/desc.R
- R/lead-lag.R
- R/nth-value.R
- R/order-by.R
- R/slice.R
- R/vec-case-match.R
- R/vec-case-when.R
Closes https://github.com/tidyverse/dplyr/issues/6716
With a few more micro improvements in `case_when()`
```r
library(dplyr)
x <- 1L
bench::mark(
one = case_when(x == 1L ~ TRUE), 
two = case_when(x == 1L ~ TRUE, x == 2L ~ NA),
three = case_when(x == 1L ~ TRUE, x == 2L ~ NA, TRUE ~ FALSE),
iterations = 50000,
check = FALSE
)
#> # A tibble: 3 × 6
#> 1 one           161µs    212µs     4470.   524.3KB     11.2
#> 2 two           189µs    239µs     3960.     1.3KB     12.2
#> 3 three         212µs    277µs     3312.     1.3KB     12.0
#> # A tibble: 3 × 6
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> …
```
> Use `obj_check_vector()` and `vec_check_size()`

- R/across.R
CC @lionel-, found another place where this came up. I think I'll also do a follow up PR to change the implementation so the "auto name" is only generated on the fly when it is actually needed, which is typically only in `mutate()` or `summarise()` to name an unnamed expression to create a column for it, or right before an error. Which means `filter()` shouldn't have to pay this penalty at all.
CC @simonpcouch, should take off a little overhead from parsnip
```r
library(tidymodels)
bench::mark(
model = {
l <- linear_reg()
fit(l, hours ~ age + college, data = gss)
}, 
iterations = 100
)
#> # A tibble: 1 × 6
#> 1 model        51.3ms   56.4ms      17.5    9.18MB …
```
> Avoid infix slowdown in `dplyr_quosures()`

- NEWS.md
- R/group-data.R
And break `group_data.data.frame()` into multiple lines
This is used by `compute_by()` in the common case of an ungrouped data frame with no `.by` argument, so it is worth it to make it faster here:
``` r
library(dplyr)
df <- tibble(x = 1:5)
bench::mark(group_data(df))
#> # A tibble: 1 × 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 group_data(df)    155µs    173µs     5235.     179KB     8.19
#> # A tibble: 1 × 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 group_data(df)   22.5µs   24.8µs    37684.     105KB     11.3
```
<sup>Created on 2023-02-17 with [reprex …
> Avoid `as_tibble()` in `group_data.tbl_df()`

- R/by.R
~25% less overhead in `mutate()` now
``` r
library(dplyr)
df <- tibble(x = c(1, 2, 3, 4))
bench::mark(mutate(df, y = x + 1), iterations = 10000)
#> # A tibble: 1 × 6
#>   expression                 min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>            <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 mutate(df, y = x + 1)   1.72ms   1.96ms      483.    2.76MB     11.1
#> # A tibble: 1 × 6
#>   expression                 min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>            <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 mutate(df, y = x + 1)    986µs   1.42ms      678.    2.31MB     10.1
```
> Optimize `compute_by()` for the "no groups" case

- tests/testthat/_snaps/join-by.md
- tests/testthat/test-join-by.R
This has changed in dev rlang to not error. Instead `enquos()` seems to now drop embraced arguments that are missing arguments
```r
library(rlang)
fn <- function(x, y) {
fn2({{x}}, {{y}})
}
fn2 <- function(...) {
enquos(...)
}
fn(a)
#> <list_of<quosure>>
#> 
#> [[1]]
#> <quosure>
#> expr: ^a
#> env:  global
```
> Remove test related to embracing of unused missing argument

- tests/testthat/test-deprec-funs.R
We're testing names here, not values.
> Relax summarise_at() test

- R/bind-cols.R
- R/bind-rows.R
- R/filter.R
- R/utils.R
- tests/testthat/test-utils.R
CC @hadley @lionel- 
purrr doesn't really have any replacement for `flatten_if()` and the `squash*()` family yet.
I think this new `fn` argument could replace `flatten_if()`, and the `recursive` argument handles the squashing case.
Notably with `fn`, it is only applied to elements of the list that already pass a `vec_is_list()` check, so it just acts as a refinement of that.
---
Not really waiting on a review here, just letting you know about this in case we want to bring it to purrr too.
> Add `list_flatten()` helper to avoid rlang deprecations

- NEWS.md
- R/join-rows.R
- R/join.R
- man/mutate-joins.Rd
- tests/testthat/_snaps/join-rows.md
- tests/testthat/_snaps/join.md
- tests/testthat/test-group-by.R
- tests/testthat/test-join-rows.R
- tests/testthat/test-join.R
Closes https://github.com/tidyverse/dplyr/issues/6731
Closes https://github.com/tidyverse/dplyr/issues/6717
Joint PR on the vctrs side https://github.com/r-lib/vctrs/pull/1791, which contains even more detail
This PR hopefully fixes most of the complaints we've seen about the multiple match warning. At a high level:
- We previously warned on one-to-many and many-to-many relationships
- We now only warn on many-to-many relationships
As outlined in https://github.com/tidyverse/dplyr/issues/6731, only warning on many-to-many makes much more sense, as one-to-many is generally pretty useful, and is symmetric with many-to-one which we don't warn on, and that didn't make much sense. As further proof that we _should_ warn on many-to-many, most SQL dialects won't even let you create a many-to-many …
> Implement `relationship` and refine join match warning

- NEWS.md
- R/data-mask.R
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/summarise.md
- tests/testthat/test-filter.R
- tests/testthat/test-mutate.R
- tests/testthat/test-summarise.R
> Explicitly disallow data frames with `NA` or `""` names

- R/data-mask.R
- tests/testthat/test-mutate.R
Closes https://github.com/tidyverse/dplyr/issues/6762
@lionel- this was a new one for me. The issue in #6762 was caused by a nested `mutate()` getting a reference to the exact same `dplyr:::current_group_id` as the outer `mutate()`. It seems that the `0L` value we initialize the id and size with isn't created "fresh" in each DataMask, so that is how they can get shared. Super tricky, took a long time to debug 😅 
Does this make sense to you? (No rush since you are OOO, just letting you know really)
> Always duplicate variables we plan to modify by reference

- R/group-data.R
Only because 5 packages superclass `data.frame` rather than subclassing it, resulting in a scalar object error from vctrs
- autoReg
- mapping
- NetworkExtinction
- onemap
- PupillometryR
Really these are "bugs" from our perspective in those 5 packages, but we don't want to spend effort updating those for a patch release
> Use `nrow()` rather than `vec_size()` in `group_data()`

- vignettes/programming.Rmd
I think that the current example doesn't help understand fully where the injection happens by using the same variable `x` as the function argument symbol and as the value passed as this argument.
This edit hopefully makes it clearer. I tried to choose a neutral variable name but I'm happy to edit for any other name.
> Update variable name in name injection example

- R/utils-tidy-eval.R
- man/tidyeval-compat.Rd
This should avoid this CRAN check note on r-devel, but we can't seem to reproduce it
```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
'.data'
All user-level objects in a package should have documentation entries.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
```
Purposefully not adding a bullet for `.data` in the documentation page, as it isn't actually a helper that is "no longer for normal usage".
In the long term we should move this to its own help page, possibly with `.env`, or remove it entirely.
> Add an alias for `.data` so `?dplyr::.data` works

- tests/testthat/test-join.R
The coercion of two factors is behavior that is very specific to vctrs.
Reference: https://github.com/duckdb/duckdb/issues/7451.
> Split coercion tests

- R/sample.R
Should this be `deprecate_soft()` ?
> Add closing backtick in message

- tests/testthat/test-count-tally.R
Cases like this can cause mild confusion. Should testthat warn here?
> Fix duplicate test names

- tests/testthat/test-summarise.R
This behaves differently in duckplyr.
> Avoid relying on type stability in sum()

- tests/testthat/test-count-tally.R
None of the existing tests was triggered when the sort order wasn't established.
I see that `summarize(.by = ...)` has a different default (of returning in the order of appearance), I wonder what the long-term intention for `count()` is.
> Add tests for behavior of count()

- tests/testthat/test-across.R
Closes https://github.com/tidyverse/dplyr/issues/6895
@hadley I think this is a valid usage of `across()` + renaming-in-tidyselect, do you agree?
``` r
library(rlang)
df <- tibble::tibble(a = 1, b = 2, c = 3)
cols <- set_names(c("a", "b"), c("x", "y"))
df %>%
mutate(
across(
.cols = all_of(cols),
.fns = ~ .x + 10
)
)
#> # A tibble: 1 × 5
#>       a     b     c     x     y
#>   <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1     1     2     3    11    12
```
Extracted from https://github.com/tidyverse/dplyr/issues/6895#issuecomment-1660770953, adding a test because I didn't see any and want to ensure this continues to work.
> Add tests to ensure `across()` allows tidyselect renaming

- NEWS.md
- R/join-by.R
- tests/testthat/_snaps/join-by.md
- tests/testthat/test-join-by.R
Closes https://github.com/tidyverse/dplyr/issues/6838
@lionel- what do you think? This seemed pretty nice to me
> Allow for namespaced `join_by()` helpers

- NEWS.md
- R/slice.R
- tests/testthat/_snaps/slice.md
- tests/testthat/test-slice.R
Closes https://github.com/tidyverse/dplyr/issues/6946
> Ensure `slice_*()` family throw the right error when namespace prefixed

- DESCRIPTION
- tests/testthat/_snaps/context.md
- tests/testthat/_snaps/summarise.md
> Align snapshot tests

- DESCRIPTION
- R/generics.R
- man/dplyr_extending.Rd
- tests/testthat/_snaps/context.md
- tests/testthat/_snaps/summarise.md
- tests/testthat/test-summarise.R
I saw these tests in at least two tidyverse/tidymodels packages, but no equivalent test in dplyr. If this is intended, should we test and perhaps also document here?
> Test that `summarize()` strips off the subclass

- tests/testthat/test-group-by.R
Works better with testthat's ability to run an individual test based on `desc`
> Use a plain 'ol string here

- DESCRIPTION
- NEWS.md
- R/mutate.R
- R/slice.R
- tests/testthat/helper-lazy.R
Also closes #7022 - we can't remove all that code because we call those helpers in the tests, and I'd like to keep the "skip" in place in case we ever change things in vctrs (it is part of an unexported API so we aren't promising to keep it stable). But we can remove the version check there now.
> Bump minimum R version to 3.6.0 and make related tweaks

- NEWS.md
- R/all-equal.R
- R/arrange.R
- R/data-storms.R
- R/generics.R
- R/n-col.R
- R/ncol.R
- R/rows.R
- R/sets.R
- R/slice.R
- tests/testthat/test-across.R
- tests/testthat/test-colwise-mutate.R
- tests/testthat/test-deprec-context.R
- tests/testthat/test-deprec-do.R
- tests/testthat/test-distinct.R
- tests/testthat/test-select.R
This leads to premature materialization in `union_all()` and others with duckplyr 0.4.0 . I'll have to work around by vendoring everything that uses `ncol()` directly or indirectly into duckdb.
> Implement own `df_n_col()` to avoid calling `ncol()` (and `dim()`)

- NEWS.md
- R/across.R
- man/across.Rd
- man/select.Rd
- tests/testthat/test-across.R
Fixes #7059
This commit addresses the unexpected behavior of `if_any()` and `if_all()` when no columns are selected. Specifically, `if_any()` now returns `FALSE`, and `if_all()` returns `TRUE` in cases where no columns match the selection criteria.
Additionally, tests have been added to ensure the correct behavior of these functions in both `filter()` and `mutate()` contexts, including the scenarios highlighted by the `reprex` example. This ensures that empty selections behave consistently with the logical expectations.
> Fix `if_any()` and `if_all()` behavior with zero-column selections

- NEWS.md
- R/data-mask.R
- tests/testthat/_snaps/filter.md
- tests/testthat/_snaps/mutate.md
- tests/testthat/_snaps/summarise.md
- tests/testthat/test-data-mask.R
> Fix edge case when coercing data frames to matrices

- R/slice.R
- man/slice.Rd
Users may be led astray by the current language describing weighted sampling via `slice_sample()`. As discussed in https://stats.stackexchange.com/q/639211/ and elaborated on in issue #6848, there's more nuance to how weights might be used for sampling. The current base R algorithm which `slice_sample()` relies on does not use the sampling weights in a way that conform to how a user might suspect the weights ought to work, as in Horvitz Thompson estimation for example. 
I've added appropriate details here in the documentation including the above link for further details.
> Add documentation clarifying appropriate use of weights in `slice_sample()`

- man/rmd/select.Rmd
- man/select.Rd
> Remove `tidyr::pivot_longer()` examples in tidy selection documentation

- DESCRIPTION
- NEWS.md
- R/if-else.R
- man/if_else.Rd
- tests/testthat/_snaps/if-else.md
- tests/testthat/test-if-else.R
Branched from #7722 
See https://github.com/r-lib/vctrs/pull/2030 for benchmarks!
One thing of note is that `vec_if_else()` disallows arrays for `condition`. I am not yet sure if we are going to have to provide a compat layer for 1D arrays in `if_else()` itself. We will have to run revdeps, and then add a test on the dplyr side if we need this. `"c6431dd7-a51a-4fe5-81a9-b889d0a1510a"`
> Switch `if_else()` to `vec_if_else()`

- NEWS.md
- R/coalesce.R
- tests/testthat/_snaps/coalesce.md
- tests/testthat/test-coalesce.R
Five goals:
- Significantly speed up and reduce memory of `coalesce()` using `vctrs::vec_case_when()`
- Fix the error generated by `coalesce(1, NULL, "x")`, where the reported index was off due to compacting out `NULL` too early
- Give a better error when all inputs are `NULL`
- Get rid of usage of early-naming via `names_as_error_names()`, which is no longer required with the C impl of `vec_case_when()` (it falls out naturally when you rewrite in C)
- Improve on consistency regarding the output names generated by `coalesce()`
``` r
cross::bench_branches(\() {
library(dplyr)
set.seed(123)
x <- sample(c(1, NA, 2), size = 1e7, replace = TRUE)
bench::mark(coalesce(x, 0))
})
#> # A tibble: 2 × 7
#>   branch                    expression          min   median `itr/sec` mem_alloc `gc/sec`
#> …
```
> Refresh `coalesce()` on top of `vctrs::vec_case_when()`

- NEWS.md
- R/case-when.R
- man/case_when.Rd
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/_snaps/case-when.md
- tests/testthat/test-case-when.R
*This description is outdated but I've left it for historical purposes, see below comments*
Closes https://github.com/tidyverse/dplyr/issues/7082
This is a breaking change.
Motivating example with CRAN dplyr:
``` r
x <- 5
#
#
dplyr::case_when(
x == 5 ~ "hello",
x > 10 ~ character(),
.default = "other"
)
#> character(0)
```
With this PR
``` r
x <- 5
dplyr::case_when(
x == 5 ~ "hello",
x > 10 ~ character(),
.default = "other"
)
#> Error in `dplyr::case_when()`:
#> ! `..2 (right)` must have size 1, not size 0.
```
In https://github.com/tidyverse/dplyr/issues/7082#issuecomment-2334173589 I explained how changing to this behavior increases the safety of `case_when()` (as seen above) and brings us one step closer to my ideal `case_when()` behavior. Unfortunately, having to support `TRUE ~` will …
> Soft-deprecate `case_when()` with all size 1 LHS and any size >1 RHS
